// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Customizable screener to retrieve reference data : this is a prototype, to be completed

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/screener_data/v1/screener_data.proto (package systemathics.apis.services.screener_data.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import { file_systemathics_apis_services_static_data_v1_static_data } from "../../static_data/v1/static_data_pb";
import { file_systemathics_apis_type_shared_v1_option_type } from "../../../type/shared/v1/option_type_pb";

/**
 * Describes the file systemathics/apis/services/screener_data/v1/screener_data.proto.
 */
export const file_systemathics_apis_services_screener_data_v1_screener_data = /*@__PURE__*/
  fileDesc("Cj9zeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9zY3JlZW5lcl9kYXRhL3YxL3NjcmVlbmVyX2RhdGEucHJvdG8SK3N5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnNjcmVlbmVyX2RhdGEudjEijgYKD1NjcmVlbmVyUmVxdWVzdBIqCgVzdGFydBgBIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5JbnQzMlZhbHVlEioKBWNvdW50GAIgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDMyVmFsdWUSLgoIY3VycmVuY3kYAyABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSLgoIZXhjaGFuZ2UYBCABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSWAoOY2FwaXRhbGl6YXRpb24YBSABKAsyQC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zdGF0aWNfZGF0YS52MS5TdGF0aWNEYXRhRG91YmxlUmFuZ2USTgoGZXhwaXJ5GAYgASgLMj4uc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc3RhdGljX2RhdGEudjEuU3RhdGljRGF0YURhdGVSYW5nZRJBCgtvcHRpb25fdHlwZRgHIAEoDjIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLk9wdGlvblR5cGUSTgoNZXhlcmNpc2VfdHlwZRgIIAEoDjI3LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLkV4ZXJjaXNlVHlwZRJPCgVkZWx0YRgJIAEoCzJALnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLlN0YXRpY0RhdGFEb3VibGVSYW5nZRJcChJpbXBsaWVkX3ZvbGF0aWxpdHkYCiABKAsyQC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zdGF0aWNfZGF0YS52MS5TdGF0aWNEYXRhRG91YmxlUmFuZ2USVwoNb3Blbl9pbnRlcmVzdBgLIAEoCzJALnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLlN0YXRpY0RhdGFEb3VibGVSYW5nZSJdChBTY3JlZW5lclJlc3BvbnNlEkkKBmVxdWl0eRgBIAEoCzI5LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLkVxdWl0eVJlc3BvbnNlMrUBCg9TY3JlZW5lclNlcnZpY2USoQEKCFNjcmVlbmVyEjwuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc2NyZWVuZXJfZGF0YS52MS5TY3JlZW5lclJlcXVlc3QaPS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zY3JlZW5lcl9kYXRhLnYxLlNjcmVlbmVyUmVzcG9uc2UiGILT5JMCEhIQL3YxL3NjcmVlbmVyZGF0YWIGcHJvdG8z", [file_google_api_annotations, file_google_protobuf_wrappers, file_systemathics_apis_services_static_data_v1_static_data, file_systemathics_apis_type_shared_v1_option_type]);

/**
 * Describes the message systemathics.apis.services.screener_data.v1.ScreenerRequest.
 * Use `create(ScreenerRequestSchema)` to create a new message.
 */
export const ScreenerRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_screener_data_v1_screener_data, 0);

/**
 * Describes the message systemathics.apis.services.screener_data.v1.ScreenerResponse.
 * Use `create(ScreenerResponseSchema)` to create a new message.
 */
export const ScreenerResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_screener_data_v1_screener_data, 1);

/**
 * Called to request screener data.
 *
 * @generated from service systemathics.apis.services.screener_data.v1.ScreenerService
 */
export const ScreenerService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_screener_data_v1_screener_data, 0);

