// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Tick prices illustrates tick price movements for an instrument over a look back period.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/tick/v2/get_tick.proto (package systemathics.apis.services.tick.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { Constraints } from "../../../type/shared/v1/constraints_pb";
import type { DateTime } from "../../../../../google/type/datetime_pb";
import type { AssetType } from "../../../type/shared/v1/asset_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file systemathics/apis/services/tick/v2/get_tick.proto.
 */
export declare const file_systemathics_apis_services_tick_v2_get_tick: GenFile;

/**
 * The required input to request the GetTickByIdentifier endpoint
 *
 * @generated from message systemathics.apis.services.tick.v2.TickRequest
 */
export declare type TickRequest = Message<"systemathics.apis.services.tick.v2.TickRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] Fields/measures requested for tick data
   *
   * @generated from field: repeated string fields = 2;
   */
  fields: string[];

  /**
   * [Optional] The constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.Constraints constraints = 3;
   */
  constraints?: Constraints;
};

/**
 * Describes the message systemathics.apis.services.tick.v2.TickRequest.
 * Use `create(TickRequestSchema)` to create a new message.
 */
export declare const TickRequestSchema: GenMessage<TickRequest>;

/**
 * The required input to request the TickVectorKeyStream endpoint
 *
 * @generated from message systemathics.apis.services.tick.v2.TickVectorKeyRequest
 */
export declare type TickVectorKeyRequest = Message<"systemathics.apis.services.tick.v2.TickVectorKeyRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] Fields/measures requested for daily data
   *
   * @generated from field: repeated string fields = 2;
   */
  fields: string[];

  /**
   * [Mandatory] Key requested for daily data
   *
   * @generated from field: string key = 3;
   */
  key: string;

  /**
   * [Optional] The constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.Constraints constraints = 4;
   */
  constraints?: Constraints;
};

/**
 * Describes the message systemathics.apis.services.tick.v2.TickVectorKeyRequest.
 * Use `create(TickVectorKeyRequestSchema)` to create a new message.
 */
export declare const TickVectorKeyRequestSchema: GenMessage<TickVectorKeyRequest>;

/**
 * Represents the tick scalar stream response.
 *
 * @generated from message systemathics.apis.services.tick.v2.TickScalarStreamResponse
 */
export declare type TickScalarStreamResponse = Message<"systemathics.apis.services.tick.v2.TickScalarStreamResponse"> & {
  /**
   * @generated from oneof systemathics.apis.services.tick.v2.TickScalarStreamResponse.payload
   */
  payload: {
    /**
     * The tick fields. Issued in the first frame.
     *
     * @generated from field: systemathics.apis.services.tick.v2.TickStreamFields info = 1;
     */
    value: TickStreamFields;
    case: "info";
  } | {
    /**
     * The mapping data. Issued in the following frames.
     *
     * @generated from field: systemathics.apis.services.tick.v2.TickScalarStreamItem data = 2;
     */
    value: TickScalarStreamItem;
    case: "data";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.services.tick.v2.TickScalarStreamResponse.
 * Use `create(TickScalarStreamResponseSchema)` to create a new message.
 */
export declare const TickScalarStreamResponseSchema: GenMessage<TickScalarStreamResponse>;

/**
 * Represents the tick scalar stream response.
 *
 * @generated from message systemathics.apis.services.tick.v2.TickVectorStreamResponse
 */
export declare type TickVectorStreamResponse = Message<"systemathics.apis.services.tick.v2.TickVectorStreamResponse"> & {
  /**
   * @generated from oneof systemathics.apis.services.tick.v2.TickVectorStreamResponse.payload
   */
  payload: {
    /**
     * The tick fields. Issued in the first frame.
     *
     * @generated from field: systemathics.apis.services.tick.v2.TickStreamFields info = 1;
     */
    value: TickStreamFields;
    case: "info";
  } | {
    /**
     * The mapping data. Issued in the following frames.
     *
     * @generated from field: systemathics.apis.services.tick.v2.TickVectorStreamItem data = 2;
     */
    value: TickVectorStreamItem;
    case: "data";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.services.tick.v2.TickVectorStreamResponse.
 * Use `create(TickVectorStreamResponseSchema)` to create a new message.
 */
export declare const TickVectorStreamResponseSchema: GenMessage<TickVectorStreamResponse>;

/**
 * Represents all fields available in a tick scalar stream response.
 *
 * @generated from message systemathics.apis.services.tick.v2.TickStreamFields
 */
export declare type TickStreamFields = Message<"systemathics.apis.services.tick.v2.TickStreamFields"> & {
  /**
   * The collection containing fields/measures values.
   *
   * @generated from field: repeated string fields = 1;
   */
  fields: string[];
};

/**
 * Describes the message systemathics.apis.services.tick.v2.TickStreamFields.
 * Use `create(TickStreamFieldsSchema)` to create a new message.
 */
export declare const TickStreamFieldsSchema: GenMessage<TickStreamFields>;

/**
 * Represents the data part of a tick scalar stream response.
 *
 * @generated from message systemathics.apis.services.tick.v2.TickScalarStreamItem
 */
export declare type TickScalarStreamItem = Message<"systemathics.apis.services.tick.v2.TickScalarStreamItem"> & {
  /**
   * The data date.
   *
   * @generated from field: google.type.DateTime datetime = 1;
   */
  datetime?: DateTime;

  /**
   * The data. Lenght of the array is the same as the fields.
   *
   * @generated from field: repeated double data = 2;
   */
  data: number[];
};

/**
 * Describes the message systemathics.apis.services.tick.v2.TickScalarStreamItem.
 * Use `create(TickScalarStreamItemSchema)` to create a new message.
 */
export declare const TickScalarStreamItemSchema: GenMessage<TickScalarStreamItem>;

/**
 * Represents the data part of a tick scalar stream response.
 *
 * @generated from message systemathics.apis.services.tick.v2.TickVectorStreamItem
 */
export declare type TickVectorStreamItem = Message<"systemathics.apis.services.tick.v2.TickVectorStreamItem"> & {
  /**
   * The data date.
   *
   * @generated from field: google.type.DateTime datetime = 1;
   */
  datetime?: DateTime;

  /**
   * The vector key
   *
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * The data. Lenght of the array is the same as the fields.
   *
   * @generated from field: repeated double data = 3;
   */
  data: number[];
};

/**
 * Describes the message systemathics.apis.services.tick.v2.TickVectorStreamItem.
 * Use `create(TickVectorStreamItemSchema)` to create a new message.
 */
export declare const TickVectorStreamItemSchema: GenMessage<TickVectorStreamItem>;

/**
 * Represents a response containing an array of assets with all their providers
 *
 * @generated from message systemathics.apis.services.tick.v2.TickAssetProvidersResponse
 */
export declare type TickAssetProvidersResponse = Message<"systemathics.apis.services.tick.v2.TickAssetProvidersResponse"> & {
  /**
   * The asset type 
   *
   * @generated from field: repeated systemathics.apis.services.tick.v2.TickAssetProviderItemReponse assets = 1;
   */
  assets: TickAssetProviderItemReponse[];
};

/**
 * Describes the message systemathics.apis.services.tick.v2.TickAssetProvidersResponse.
 * Use `create(TickAssetProvidersResponseSchema)` to create a new message.
 */
export declare const TickAssetProvidersResponseSchema: GenMessage<TickAssetProvidersResponse>;

/**
 * Represents a links between an asset and a provider.
 *
 * @generated from message systemathics.apis.services.tick.v2.TickAssetProviderItemReponse
 */
export declare type TickAssetProviderItemReponse = Message<"systemathics.apis.services.tick.v2.TickAssetProviderItemReponse"> & {
  /**
   * The asset type 
   *
   * @generated from field: systemathics.apis.type.shared.v1.AssetType asset_type = 1;
   */
  assetType: AssetType;

  /**
   * The providers
   *
   * @generated from field: repeated string providers = 2;
   */
  providers: string[];
};

/**
 * Describes the message systemathics.apis.services.tick.v2.TickAssetProviderItemReponse.
 * Use `create(TickAssetProviderItemReponseSchema)` to create a new message.
 */
export declare const TickAssetProviderItemReponseSchema: GenMessage<TickAssetProviderItemReponse>;

/**
 * @generated from message systemathics.apis.services.tick.v2.TickFieldsResponse
 */
export declare type TickFieldsResponse = Message<"systemathics.apis.services.tick.v2.TickFieldsResponse"> & {
  /**
   * The collection containing items values for scalars.
   *
   * @generated from field: repeated systemathics.apis.services.tick.v2.TickFieldsItemResponse scalars = 1;
   */
  scalars: TickFieldsItemResponse[];

  /**
   * The collection containing items values for vectors.
   *
   * @generated from field: repeated systemathics.apis.services.tick.v2.TickFieldsItemResponse vectors = 2;
   */
  vectors: TickFieldsItemResponse[];
};

/**
 * Describes the message systemathics.apis.services.tick.v2.TickFieldsResponse.
 * Use `create(TickFieldsResponseSchema)` to create a new message.
 */
export declare const TickFieldsResponseSchema: GenMessage<TickFieldsResponse>;

/**
 * Represents a links between an asset and a provider.
 *
 * @generated from message systemathics.apis.services.tick.v2.TickFieldsItemResponse
 */
export declare type TickFieldsItemResponse = Message<"systemathics.apis.services.tick.v2.TickFieldsItemResponse"> & {
  /**
   * The asset type 
   *
   * @generated from field: systemathics.apis.type.shared.v1.AssetType asset_type = 1;
   */
  assetType: AssetType;

  /**
   * The provider
   *
   * @generated from field: string provider = 2;
   */
  provider: string;

  /**
   * The fields/measures
   *
   * @generated from field: repeated string fields = 3;
   */
  fields: string[];
};

/**
 * Describes the message systemathics.apis.services.tick.v2.TickFieldsItemResponse.
 * Use `create(TickFieldsItemResponseSchema)` to create a new message.
 */
export declare const TickFieldsItemResponseSchema: GenMessage<TickFieldsItemResponse>;

/**
 * Called to request tick prices data. 
 *
 * @generated from service systemathics.apis.services.tick.v2.TickService
 */
export declare const TickService: GenService<{
  /**
   * Gets tick historical data timeseries by identifier using streaming
   *
   * @generated from rpc systemathics.apis.services.tick.v2.TickService.TickScalarStream
   */
  tickScalarStream: {
    methodKind: "server_streaming";
    input: typeof TickRequestSchema;
    output: typeof TickScalarStreamResponseSchema;
  },
  /**
   * Gets tick historical data timeseries by identifier using streaming
   *
   * @generated from rpc systemathics.apis.services.tick.v2.TickService.TickVectorStream
   */
  tickVectorStream: {
    methodKind: "server_streaming";
    input: typeof TickRequestSchema;
    output: typeof TickVectorStreamResponseSchema;
  },
  /**
   * Gets tick historical data timeseries by identifier and key using streaming
   *
   * @generated from rpc systemathics.apis.services.tick.v2.TickService.TickVectorKeyStream
   */
  tickVectorKeyStream: {
    methodKind: "server_streaming";
    input: typeof TickVectorKeyRequestSchema;
    output: typeof TickVectorStreamResponseSchema;
  },
  /**
   * Gets all available fields by asset and provider.
   *
   * @generated from rpc systemathics.apis.services.tick.v2.TickService.TickFields
   */
  tickFields: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof TickFieldsResponseSchema;
  },
  /**
   * Gets all available provider by asset
   *
   * @generated from rpc systemathics.apis.services.tick.v2.TickService.TickAssetProviders
   */
  tickAssetProviders: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof TickAssetProvidersResponseSchema;
  },
}>;

