// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Tick prices illustrates tick price movements for an instrument over a look back period.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/tick/v2/set_tick.proto (package systemathics.apis.services.tick.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateTime } from "../../../../../google/type/datetime_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file systemathics/apis/services/tick/v2/set_tick.proto.
 */
export declare const file_systemathics_apis_services_tick_v2_set_tick: GenFile;

/**
 * The required input to request the SetTickScalar endpoint
 *
 * @generated from message systemathics.apis.services.tick.v2.SetTickScalarRequest
 */
export declare type SetTickScalarRequest = Message<"systemathics.apis.services.tick.v2.SetTickScalarRequest"> & {
  /**
   * [Mandatory] The instrument identifiers: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The date used to request data.
   *
   * @generated from field: google.type.DateTime datetime = 2;
   */
  datetime?: DateTime;

  /**
   * [Mandatory] The data with field as a key
   *
   * @generated from field: map<string, double> data = 3;
   */
  data: { [key: string]: number };
};

/**
 * Describes the message systemathics.apis.services.tick.v2.SetTickScalarRequest.
 * Use `create(SetTickScalarRequestSchema)` to create a new message.
 */
export declare const SetTickScalarRequestSchema: GenMessage<SetTickScalarRequest>;

/**
 * The required input to request the SetTickScalar endpoint
 *
 * @generated from message systemathics.apis.services.tick.v2.SetTickScalarStreamRequest
 */
export declare type SetTickScalarStreamRequest = Message<"systemathics.apis.services.tick.v2.SetTickScalarStreamRequest"> & {
  /**
   * @generated from oneof systemathics.apis.services.tick.v2.SetTickScalarStreamRequest.payload
   */
  payload: {
    /**
     * The tick info
     *
     * @generated from field: systemathics.apis.services.tick.v2.SetTickInfo info = 1;
     */
    value: SetTickInfo;
    case: "info";
  } | {
    /**
     * The mapping data
     *
     * @generated from field: systemathics.apis.services.tick.v2.SetTickScalarData data = 2;
     */
    value: SetTickScalarData;
    case: "data";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.services.tick.v2.SetTickScalarStreamRequest.
 * Use `create(SetTickScalarStreamRequestSchema)` to create a new message.
 */
export declare const SetTickScalarStreamRequestSchema: GenMessage<SetTickScalarStreamRequest>;

/**
 * The required input to request the SetTickScalar endpoint
 *
 * @generated from message systemathics.apis.services.tick.v2.SetTickVectorRequest
 */
export declare type SetTickVectorRequest = Message<"systemathics.apis.services.tick.v2.SetTickVectorRequest"> & {
  /**
   * [Mandatory] The instrument identifiers: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The date used to request data.
   *
   * @generated from field: google.type.DateTime datetime = 2;
   */
  datetime?: DateTime;

  /**
   * [Mandatory] The vector key.
   *
   * @generated from field: string key = 3;
   */
  key: string;

  /**
   * [Mandatory] The data with field as a key
   *
   * @generated from field: map<string, double> data = 4;
   */
  data: { [key: string]: number };
};

/**
 * Describes the message systemathics.apis.services.tick.v2.SetTickVectorRequest.
 * Use `create(SetTickVectorRequestSchema)` to create a new message.
 */
export declare const SetTickVectorRequestSchema: GenMessage<SetTickVectorRequest>;

/**
 * The required input to request the SetTickScalar endpoint
 *
 * @generated from message systemathics.apis.services.tick.v2.SetTickVectorStreamRequest
 */
export declare type SetTickVectorStreamRequest = Message<"systemathics.apis.services.tick.v2.SetTickVectorStreamRequest"> & {
  /**
   * @generated from oneof systemathics.apis.services.tick.v2.SetTickVectorStreamRequest.payload
   */
  payload: {
    /**
     * The tick info
     *
     * @generated from field: systemathics.apis.services.tick.v2.SetTickInfo info = 1;
     */
    value: SetTickInfo;
    case: "info";
  } | {
    /**
     * The mapping data
     *
     * @generated from field: systemathics.apis.services.tick.v2.SetTickVectorData data = 2;
     */
    value: SetTickVectorData;
    case: "data";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.services.tick.v2.SetTickVectorStreamRequest.
 * Use `create(SetTickVectorStreamRequestSchema)` to create a new message.
 */
export declare const SetTickVectorStreamRequestSchema: GenMessage<SetTickVectorStreamRequest>;

/**
 * The required input to request DeleteTickScalar.
 *
 * @generated from message systemathics.apis.services.tick.v2.DeleteTickScalarRequest
 */
export declare type DeleteTickScalarRequest = Message<"systemathics.apis.services.tick.v2.DeleteTickScalarRequest"> & {
  /**
   * [Mandatory] The instrument identifiers: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The fields to be deleted.
   *
   * @generated from field: repeated string fields = 2;
   */
  fields: string[];

  /**
   * [Mandatory] The dates to be deleted.
   *
   * @generated from field: repeated google.type.DateTime dates = 3;
   */
  dates: DateTime[];
};

/**
 * Describes the message systemathics.apis.services.tick.v2.DeleteTickScalarRequest.
 * Use `create(DeleteTickScalarRequestSchema)` to create a new message.
 */
export declare const DeleteTickScalarRequestSchema: GenMessage<DeleteTickScalarRequest>;

/**
 * The required input to request DeleteTickScalar.
 *
 * @generated from message systemathics.apis.services.tick.v2.DeleteTickVectorRequest
 */
export declare type DeleteTickVectorRequest = Message<"systemathics.apis.services.tick.v2.DeleteTickVectorRequest"> & {
  /**
   * [Mandatory] The instrument identifiers: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The fields to be deleted.
   *
   * @generated from field: repeated string fields = 2;
   */
  fields: string[];

  /**
   * [Mandatory] The keys to be deleted.
   *
   * @generated from field: repeated systemathics.apis.services.tick.v2.VectorKey keys = 3;
   */
  keys: VectorKey[];
};

/**
 * Describes the message systemathics.apis.services.tick.v2.DeleteTickVectorRequest.
 * Use `create(DeleteTickVectorRequestSchema)` to create a new message.
 */
export declare const DeleteTickVectorRequestSchema: GenMessage<DeleteTickVectorRequest>;

/**
 * The required input to request the GetTickByDate endpoint
 *
 * @generated from message systemathics.apis.services.tick.v2.SetTickInfo
 */
export declare type SetTickInfo = Message<"systemathics.apis.services.tick.v2.SetTickInfo"> & {
  /**
   * [Mandatory] The instrument identifiers: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The data names.
   *
   * @generated from field: repeated string fields = 2;
   */
  fields: string[];
};

/**
 * Describes the message systemathics.apis.services.tick.v2.SetTickInfo.
 * Use `create(SetTickInfoSchema)` to create a new message.
 */
export declare const SetTickInfoSchema: GenMessage<SetTickInfo>;

/**
 * Represent the data to be added to the data scalar timeseries.
 *
 * @generated from message systemathics.apis.services.tick.v2.SetTickScalarData
 */
export declare type SetTickScalarData = Message<"systemathics.apis.services.tick.v2.SetTickScalarData"> & {
  /**
   * [Mandatory] The date used to request data.
   *
   * @generated from field: google.type.DateTime datetime = 1;
   */
  datetime?: DateTime;

  /**
   * [Mandatory] The data.
   *
   * @generated from field: repeated double data = 2;
   */
  data: number[];
};

/**
 * Describes the message systemathics.apis.services.tick.v2.SetTickScalarData.
 * Use `create(SetTickScalarDataSchema)` to create a new message.
 */
export declare const SetTickScalarDataSchema: GenMessage<SetTickScalarData>;

/**
 * Represent the key for a vector.
 *
 * @generated from message systemathics.apis.services.tick.v2.VectorKey
 */
export declare type VectorKey = Message<"systemathics.apis.services.tick.v2.VectorKey"> & {
  /**
   * [Mandatory] The date used to request data.
   *
   * @generated from field: google.type.DateTime datetime = 1;
   */
  datetime?: DateTime;

  /**
   * [Mandatory] The vector key.
   *
   * @generated from field: string key = 2;
   */
  key: string;
};

/**
 * Describes the message systemathics.apis.services.tick.v2.VectorKey.
 * Use `create(VectorKeySchema)` to create a new message.
 */
export declare const VectorKeySchema: GenMessage<VectorKey>;

/**
 * Represent the data to be added to the data vector timeseries.
 *
 * @generated from message systemathics.apis.services.tick.v2.SetTickVectorData
 */
export declare type SetTickVectorData = Message<"systemathics.apis.services.tick.v2.SetTickVectorData"> & {
  /**
   * [Mandatory] The date used to request data.
   *
   * @generated from field: google.type.DateTime datetime = 1;
   */
  datetime?: DateTime;

  /**
   * [Mandatory] The vector key.
   *
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * [Mandatory] The data.
   *
   * @generated from field: repeated double data = 3;
   */
  data: number[];
};

/**
 * Describes the message systemathics.apis.services.tick.v2.SetTickVectorData.
 * Use `create(SetTickVectorDataSchema)` to create a new message.
 */
export declare const SetTickVectorDataSchema: GenMessage<SetTickVectorData>;

/**
 * Called to set tick prices data and clear. 
 *
 * @generated from service systemathics.apis.services.tick.v2.SetTickService
 */
export declare const SetTickService: GenService<{
  /**
   * Sets tick scalar timeseries.
   *
   * @generated from rpc systemathics.apis.services.tick.v2.SetTickService.WriteTickScalar
   */
  writeTickScalar: {
    methodKind: "unary";
    input: typeof SetTickScalarRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc systemathics.apis.services.tick.v2.SetTickService.WriteTickScalarStream
   */
  writeTickScalarStream: {
    methodKind: "client_streaming";
    input: typeof SetTickScalarStreamRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Sets tick vector timeseries.
   *
   * @generated from rpc systemathics.apis.services.tick.v2.SetTickService.WriteTickVector
   */
  writeTickVector: {
    methodKind: "unary";
    input: typeof SetTickVectorRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Sets tick vector timeseries.
   *
   * @generated from rpc systemathics.apis.services.tick.v2.SetTickService.WriteTickVectorStream
   */
  writeTickVectorStream: {
    methodKind: "client_streaming";
    input: typeof SetTickVectorStreamRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Update tick scalar timeseries.
   *
   * @generated from rpc systemathics.apis.services.tick.v2.SetTickService.UpdateTickScalar
   */
  updateTickScalar: {
    methodKind: "unary";
    input: typeof SetTickScalarRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Update tick scalar timeseries.
   *
   * @generated from rpc systemathics.apis.services.tick.v2.SetTickService.UpdateTickScalarStream
   */
  updateTickScalarStream: {
    methodKind: "client_streaming";
    input: typeof SetTickScalarStreamRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Update tick vectors timeseries.
   *
   * @generated from rpc systemathics.apis.services.tick.v2.SetTickService.UpdateTickVector
   */
  updateTickVector: {
    methodKind: "unary";
    input: typeof SetTickVectorRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Update tick vectors timeseries.
   *
   * @generated from rpc systemathics.apis.services.tick.v2.SetTickService.UpdateTickVectorStream
   */
  updateTickVectorStream: {
    methodKind: "client_streaming";
    input: typeof SetTickVectorStreamRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Delete tick scalar timeseries.
   *
   * @generated from rpc systemathics.apis.services.tick.v2.SetTickService.DeleteTickScalar
   */
  deleteTickScalar: {
    methodKind: "unary";
    input: typeof DeleteTickScalarRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Delete tick scalar timeseries.
   *
   * @generated from rpc systemathics.apis.services.tick.v2.SetTickService.DeleteTickVector
   */
  deleteTickVector: {
    methodKind: "unary";
    input: typeof DeleteTickVectorRequestSchema;
    output: typeof EmptySchema;
  },
}>;

