// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Daily bars are widely used to illustrate price movements for an instrument over a look back period. 
// Commonly used in financial analysis and trading strategies as a technical indicator.

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/daily/v1/daily_bars.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Date } from "../../../../../google/type/date_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_bars.proto.
 */
export const file_systemathics_apis_services_daily_v1_daily_bars: GenFile = /*@__PURE__*/
  fileDesc("CjRzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseS92MS9kYWlseV9iYXJzLnByb3RvEiNzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MSKvAQoQRGFpbHlCYXJzUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchJFCg1kYXRlX2ludGVydmFsGAIgASgLMi4uc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuRGF0ZUludGVydmFsEhIKCmFkanVzdG1lbnQYAyABKAgiUAoRRGFpbHlCYXJzUmVzcG9uc2USOwoEZGF0YRgBIAMoCzItLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5LnYxLkRhaWx5QmFyIoIBCghEYWlseUJhchIfCgRkYXRlGAEgASgLMhEuZ29vZ2xlLnR5cGUuRGF0ZRIMCgRvcGVuGAIgASgBEgwKBGhpZ2gYAyABKAESCwoDbG93GAQgASgBEg0KBWNsb3NlGAUgASgBEg4KBnZvbHVtZRgGIAEoARINCgVzY29yZRgHIAEoATKnAQoQRGFpbHlCYXJzU2VydmljZRKSAQoJRGFpbHlCYXJzEjUuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHkudjEuRGFpbHlCYXJzUmVxdWVzdBo2LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5LnYxLkRhaWx5QmFyc1Jlc3BvbnNlIhaC0+STAhASDi92MS9kYWlseS9iYXJzYgZwcm90bzM", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * The required input to request the DailyBarsService.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyBarsRequest
 */
export type DailyBarsRequest = Message<"systemathics.apis.services.daily.v1.DailyBarsRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The corporate action adjustment (dividends).
   * By default the value is set to false : the split is applied in all cases
   *
   * @generated from field: bool adjustment = 3;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyBarsRequest.
 * Use `create(DailyBarsRequestSchema)` to create a new message.
 */
export const DailyBarsRequestSchema: GenMessage<DailyBarsRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_bars, 0);

/**
 * The daily bars response contains an array of daily bars.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyBarsResponse
 */
export type DailyBarsResponse = Message<"systemathics.apis.services.daily.v1.DailyBarsResponse"> & {
  /**
   * The daily bars: an array of DailyBar objects
   *
   * @generated from field: repeated systemathics.apis.services.daily.v1.DailyBar data = 1;
   */
  data: DailyBar[];
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyBarsResponse.
 * Use `create(DailyBarsResponseSchema)` to create a new message.
 */
export const DailyBarsResponseSchema: GenMessage<DailyBarsResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_bars, 1);

/**
 * Contains the daily bar's data: date, open, high, low, close and volume.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyBar
 */
export type DailyBar = Message<"systemathics.apis.services.daily.v1.DailyBar"> & {
  /**
   * Date of the bar
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * Open price of the day
   *
   * @generated from field: double open = 2;
   */
  open: number;

  /**
   * Highest price of the day
   *
   * @generated from field: double high = 3;
   */
  high: number;

  /**
   * Lowest price of the day
   *
   * @generated from field: double low = 4;
   */
  low: number;

  /**
   * Close price of the day
   *
   * @generated from field: double close = 5;
   */
  close: number;

  /**
   * Total traded volume of the day
   *
   * @generated from field: double volume = 6;
   */
  volume: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 7;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyBar.
 * Use `create(DailyBarSchema)` to create a new message.
 */
export const DailyBarSchema: GenMessage<DailyBar> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_bars, 2);

/**
 * Called to request daily bars data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailyBarsService
 */
export const DailyBarsService: GenService<{
  /**
   * Gets daily historical data: date, open, high, low, close and volume
   *
   * @generated from rpc systemathics.apis.services.daily.v1.DailyBarsService.DailyBars
   */
  dailyBars: {
    methodKind: "unary";
    input: typeof DailyBarsRequestSchema;
    output: typeof DailyBarsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_v1_daily_bars, 0);

