// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Daily prices illustrates daily price movements for an instrument over a look back period.

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/daily/v1/daily_prices.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Date } from "../../../../../google/type/date_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_prices.proto.
 */
export const file_systemathics_apis_services_daily_v1_daily_prices: GenFile = /*@__PURE__*/
  fileDesc("CjZzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseS92MS9kYWlseV9wcmljZXMucHJvdG8SI3N5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5LnYxIrEBChJEYWlseVByaWNlc1JlcXVlc3QSQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISRQoNZGF0ZV9pbnRlcnZhbBgCIAEoCzIuLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLkRhdGVJbnRlcnZhbBISCgphZGp1c3RtZW50GAMgASgIIlQKE0RhaWx5UHJpY2VzUmVzcG9uc2USPQoEZGF0YRgBIAMoCzIvLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5LnYxLkRhaWx5UHJpY2UiWwoKRGFpbHlQcmljZRIfCgRkYXRlGAEgASgLMhEuZ29vZ2xlLnR5cGUuRGF0ZRINCgVwcmljZRgCIAEoARIOCgZ2b2x1bWUYAyABKAESDQoFc2NvcmUYBCABKAEysQEKEkRhaWx5UHJpY2VzU2VydmljZRKaAQoLRGFpbHlQcmljZXMSNy5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MS5EYWlseVByaWNlc1JlcXVlc3QaOC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MS5EYWlseVByaWNlc1Jlc3BvbnNlIhiC0+STAhISEC92MS9kYWlseS9wcmljZXNiBnByb3RvMw", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * The required input to request the DailyPricesService
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyPricesRequest
 */
export type DailyPricesRequest = Message<"systemathics.apis.services.daily.v1.DailyPricesRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The corporate action adjustment (dividends).
   * By default the value is set to false : the split is applied in all cases
   *
   * @generated from field: bool adjustment = 3;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyPricesRequest.
 * Use `create(DailyPricesRequestSchema)` to create a new message.
 */
export const DailyPricesRequestSchema: GenMessage<DailyPricesRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_prices, 0);

/**
 * Represents a daily prices response.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyPricesResponse
 */
export type DailyPricesResponse = Message<"systemathics.apis.services.daily.v1.DailyPricesResponse"> & {
  /**
   * The daily prices: an array of DailyPrice objects
   *
   * @generated from field: repeated systemathics.apis.services.daily.v1.DailyPrice data = 1;
   */
  data: DailyPrice[];
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyPricesResponse.
 * Use `create(DailyPricesResponseSchema)` to create a new message.
 */
export const DailyPricesResponseSchema: GenMessage<DailyPricesResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_prices, 1);

/**
 * Contains the daily prices data: date, price and volume.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyPrice
 */
export type DailyPrice = Message<"systemathics.apis.services.daily.v1.DailyPrice"> & {
  /**
   * Date of the price
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * Last price of the day
   *
   * @generated from field: double price = 2;
   */
  price: number;

  /**
   * Total traded volume of the day
   *
   * @generated from field: double volume = 3;
   */
  volume: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 4;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyPrice.
 * Use `create(DailyPriceSchema)` to create a new message.
 */
export const DailyPriceSchema: GenMessage<DailyPrice> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_prices, 2);

/**
 * Called to request daily prices data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailyPricesService
 */
export const DailyPricesService: GenService<{
  /**
   * Gets daily historical prices
   *
   * @generated from rpc systemathics.apis.services.daily.v1.DailyPricesService.DailyPrices
   */
  dailyPrices: {
    methodKind: "unary";
    input: typeof DailyPricesRequestSchema;
    output: typeof DailyPricesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_v1_daily_prices, 0);

