// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The settlement price </i>is the official price at which a financial instrument is settled at the end of a trading day.
//<br> The settlement refers to the process of transferring securities or funds to fulfill the terms of a trade.
//<br> In futures and options markets, the settlement price is often determined by a specific mechanism outlined by the exchange and may not necessarily be the same as the closing price.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily/v1/daily_settlement.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { Date } from "../../../../../google/type/date_pb";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_settlement.proto.
 */
export declare const file_systemathics_apis_services_daily_v1_daily_settlement: GenFile;

/**
 * The required input to request the DailySettlementsService
 *
 * @generated from message systemathics.apis.services.daily.v1.DailySettlementsRequest
 */
export declare type DailySettlementsRequest = Message<"systemathics.apis.services.daily.v1.DailySettlementsRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a ticker and exchange 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The corporate action adjustment (dividends).
   * By default the value is set to false : the split is applied in all cases
   *
   * @generated from field: bool adjustment = 3;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailySettlementsRequest.
 * Use `create(DailySettlementsRequestSchema)` to create a new message.
 */
export declare const DailySettlementsRequestSchema: GenMessage<DailySettlementsRequest>;

/**
 * Represents a daily settlements response.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailySettlementsResponse
 */
export declare type DailySettlementsResponse = Message<"systemathics.apis.services.daily.v1.DailySettlementsResponse"> & {
  /**
   * The daily settlement prices: an array of DailySettlement objects
   *
   * @generated from field: repeated systemathics.apis.services.daily.v1.DailySettlement data = 1;
   */
  data: DailySettlement[];
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailySettlementsResponse.
 * Use `create(DailySettlementsResponseSchema)` to create a new message.
 */
export declare const DailySettlementsResponseSchema: GenMessage<DailySettlementsResponse>;

/**
 * Contains the daily settlements data: date, price and volume.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailySettlement
 */
export declare type DailySettlement = Message<"systemathics.apis.services.daily.v1.DailySettlement"> & {
  /**
   * Date of the settlement
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * Settlement of the day
   *
   * @generated from field: double price = 2;
   */
  price: number;

  /**
   * Total traded volume of the day
   *
   * @generated from field: double volume = 3;
   */
  volume: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 4;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailySettlement.
 * Use `create(DailySettlementSchema)` to create a new message.
 */
export declare const DailySettlementSchema: GenMessage<DailySettlement>;

/**
 * Called to request daily Settlement price data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailySettlementsService
 */
export declare const DailySettlementsService: GenService<{
  /**
   * Gets daily historical settlement prices
   *
   * @generated from rpc systemathics.apis.services.daily.v1.DailySettlementsService.DailySettlements
   */
  dailySettlements: {
    methodKind: "unary";
    input: typeof DailySettlementsRequestSchema;
    output: typeof DailySettlementsResponseSchema;
  },
}>;

