// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Daily calendars illustrates daily holidays for an instrument over a look back period.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily/v1/daily_calendars.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_calendars.proto.
 */
export const file_systemathics_apis_services_daily_v1_daily_calendars = /*@__PURE__*/
  fileDesc("CjlzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseS92MS9kYWlseV9jYWxlbmRhcnMucHJvdG8SI3N5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5LnYxIqABChVEYWlseUNhbGVuZGFyc1JlcXVlc3QSQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISRQoNZGF0ZV9pbnRlcnZhbBgCIAEoCzIuLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLkRhdGVJbnRlcnZhbCJaChZEYWlseUNhbGVuZGFyc1Jlc3BvbnNlEkAKBGRhdGEYASADKAsyMi5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MS5EYWlseUNhbGVuZGFyInYKDURhaWx5Q2FsZW5kYXISHwoEZGF0ZRgBIAEoCzIRLmdvb2dsZS50eXBlLkRhdGUSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRISCgppc19ob2xpZGF5GAQgASgIEg0KBXNjb3JlGAUgASgBMsABChVEYWlseUNhbGVuZGFyc1NlcnZpY2USpgEKDkRhaWx5Q2FsZW5kYXJzEjouc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHkudjEuRGFpbHlDYWxlbmRhcnNSZXF1ZXN0Gjsuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHkudjEuRGFpbHlDYWxlbmRhcnNSZXNwb25zZSIbgtPkkwIVEhMvdjEvZGFpbHkvY2FsZW5kYXJzYgZwcm90bzM", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyCalendarsRequest.
 * Use `create(DailyCalendarsRequestSchema)` to create a new message.
 */
export const DailyCalendarsRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_calendars, 0);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyCalendarsResponse.
 * Use `create(DailyCalendarsResponseSchema)` to create a new message.
 */
export const DailyCalendarsResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_calendars, 1);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyCalendar.
 * Use `create(DailyCalendarSchema)` to create a new message.
 */
export const DailyCalendarSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_calendars, 2);

/**
 * Called to request daily calendars data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailyCalendarsService
 */
export const DailyCalendarsService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_v1_daily_calendars, 0);

