// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Daily calendars illustrates daily holidays for an instrument over a look back period.

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/daily/v1/daily_calendars.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Date } from "../../../../../google/type/date_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_calendars.proto.
 */
export const file_systemathics_apis_services_daily_v1_daily_calendars: GenFile = /*@__PURE__*/
  fileDesc("CjlzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseS92MS9kYWlseV9jYWxlbmRhcnMucHJvdG8SI3N5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5LnYxIqABChVEYWlseUNhbGVuZGFyc1JlcXVlc3QSQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISRQoNZGF0ZV9pbnRlcnZhbBgCIAEoCzIuLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLkRhdGVJbnRlcnZhbCJaChZEYWlseUNhbGVuZGFyc1Jlc3BvbnNlEkAKBGRhdGEYASADKAsyMi5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MS5EYWlseUNhbGVuZGFyInYKDURhaWx5Q2FsZW5kYXISHwoEZGF0ZRgBIAEoCzIRLmdvb2dsZS50eXBlLkRhdGUSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRISCgppc19ob2xpZGF5GAQgASgIEg0KBXNjb3JlGAUgASgBMsABChVEYWlseUNhbGVuZGFyc1NlcnZpY2USpgEKDkRhaWx5Q2FsZW5kYXJzEjouc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHkudjEuRGFpbHlDYWxlbmRhcnNSZXF1ZXN0Gjsuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHkudjEuRGFpbHlDYWxlbmRhcnNSZXNwb25zZSIbgtPkkwIVEhMvdjEvZGFpbHkvY2FsZW5kYXJzYgZwcm90bzM", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * The required input to request the DailyCalendarsService
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyCalendarsRequest
 */
export type DailyCalendarsRequest = Message<"systemathics.apis.services.daily.v1.DailyCalendarsRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyCalendarsRequest.
 * Use `create(DailyCalendarsRequestSchema)` to create a new message.
 */
export const DailyCalendarsRequestSchema: GenMessage<DailyCalendarsRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_calendars, 0);

/**
 * Represents a daily calendars response.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyCalendarsResponse
 */
export type DailyCalendarsResponse = Message<"systemathics.apis.services.daily.v1.DailyCalendarsResponse"> & {
  /**
   * The daily calendars: an array of DailyCalendar objects
   *
   * @generated from field: repeated systemathics.apis.services.daily.v1.DailyCalendar data = 1;
   */
  data: DailyCalendar[];
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyCalendarsResponse.
 * Use `create(DailyCalendarsResponseSchema)` to create a new message.
 */
export const DailyCalendarsResponseSchema: GenMessage<DailyCalendarsResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_calendars, 1);

/**
 * Contains the daily calendars data: date, name, description and isholiday.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyCalendar
 */
export type DailyCalendar = Message<"systemathics.apis.services.daily.v1.DailyCalendar"> & {
  /**
   * Date of the calendar
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * The calendar's name
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * The additional information to describe the calendar
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * The value indicating whether the day is holiday (market closed)
   *
   * @generated from field: bool is_holiday = 4;
   */
  isHoliday: boolean;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 5;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyCalendar.
 * Use `create(DailyCalendarSchema)` to create a new message.
 */
export const DailyCalendarSchema: GenMessage<DailyCalendar> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_calendars, 2);

/**
 * Called to request daily calendars data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailyCalendarsService
 */
export const DailyCalendarsService: GenService<{
  /**
   * Gets daily historical calendars
   *
   * @generated from rpc systemathics.apis.services.daily.v1.DailyCalendarsService.DailyCalendars
   */
  dailyCalendars: {
    methodKind: "unary";
    input: typeof DailyCalendarsRequestSchema;
    output: typeof DailyCalendarsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_v1_daily_calendars, 0);

