// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The Implied Volatility</i> is the estimated volatility of the option strike over the period of the option.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily/v1/daily_implied_volatility.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_implied_volatility.proto.
 */
export const file_systemathics_apis_services_daily_v1_daily_implied_volatility = /*@__PURE__*/
  fileDesc("CkJzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseS92MS9kYWlseV9pbXBsaWVkX3ZvbGF0aWxpdHkucHJvdG8SI3N5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5LnYxIqoBCh9EYWlseUltcGxpZWRWb2xhdGlsaXRpZXNSZXF1ZXN0EkAKCmlkZW50aWZpZXIYASABKAsyLC5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5JZGVudGlmaWVyEkUKDWRhdGVfaW50ZXJ2YWwYAiABKAsyLi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5EYXRlSW50ZXJ2YWwibQogRGFpbHlJbXBsaWVkVm9sYXRpbGl0aWVzUmVzcG9uc2USSQoEZGF0YRgBIAMoCzI7LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5LnYxLkRhaWx5SW1wbGllZFZvbGF0aWxpdHkiVwoWRGFpbHlJbXBsaWVkVm9sYXRpbGl0eRIfCgRkYXRlGAEgASgLMhEuZ29vZ2xlLnR5cGUuRGF0ZRINCgV2YWx1ZRgCIAEoARINCgVzY29yZRgDIAEoATLyAQofRGFpbHlJbXBsaWVkVm9sYXRpbGl0aWVzU2VydmljZRLOAQoYRGFpbHlJbXBsaWVkVm9sYXRpbGl0aWVzEkQuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHkudjEuRGFpbHlJbXBsaWVkVm9sYXRpbGl0aWVzUmVxdWVzdBpFLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5LnYxLkRhaWx5SW1wbGllZFZvbGF0aWxpdGllc1Jlc3BvbnNlIiWC0+STAh8SHS92MS9kYWlseS9pbXBsaWVkdm9sYXRpbGl0aWVzYgZwcm90bzM", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyImpliedVolatilitiesRequest.
 * Use `create(DailyImpliedVolatilitiesRequestSchema)` to create a new message.
 */
export const DailyImpliedVolatilitiesRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_implied_volatility, 0);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyImpliedVolatilitiesResponse.
 * Use `create(DailyImpliedVolatilitiesResponseSchema)` to create a new message.
 */
export const DailyImpliedVolatilitiesResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_implied_volatility, 1);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyImpliedVolatility.
 * Use `create(DailyImpliedVolatilitySchema)` to create a new message.
 */
export const DailyImpliedVolatilitySchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_implied_volatility, 2);

/**
 * Called to request daily ImpliedVolatility data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailyImpliedVolatilitiesService
 */
export const DailyImpliedVolatilitiesService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_v1_daily_implied_volatility, 0);

