// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This service provides access to an daily marketdata market data service,
// enabling users to retrieve historical market data for various financial instruments.
// MarketData represents a comprehensive aggregation of all pertinent market information, 
// encompassing various data points such as bar data, best limit data, Greeks, and more.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily/v1/daily_market_data_by_underlying.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_option_type } from "../../../type/shared/v1/option_type_pb";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_market_data_by_underlying.proto.
 */
export const file_systemathics_apis_services_daily_v1_daily_market_data_by_underlying = /*@__PURE__*/
  fileDesc("CklzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseS92MS9kYWlseV9tYXJrZXRfZGF0YV9ieV91bmRlcmx5aW5nLnByb3RvEiNzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MSKSAQoiRGFpbHlNYXJrZXREYXRhQnlVbmRlcmx5aW5nUmVxdWVzdBJLChV1bmRlcmx5aW5nX2lkZW50aWZpZXIYASABKAsyLC5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5JZGVudGlmaWVyEh8KBGRhdGUYAiABKAsyES5nb29nbGUudHlwZS5EYXRlInUKI0RhaWx5TWFya2V0RGF0YUJ5VW5kZXJseWluZ1Jlc3BvbnNlEk4KBGRhdGEYASADKAsyQC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MS5EYWlseU1hcmtldERhdGFCeVVuZGVybHlpbmcirgQKG0RhaWx5TWFya2V0RGF0YUJ5VW5kZXJseWluZxIfCgRkYXRlGAEgASgLMhEuZ29vZ2xlLnR5cGUuRGF0ZRIZChF1bmRlcmx5aW5nX3N5bWJvbBgCIAEoCRIYChB1bmRlcmx5aW5nX3ByaWNlGAMgASgBEhUKDW9wdGlvbl9zeW1ib2wYBCABKAkSQQoLb3B0aW9uX3R5cGUYBSABKA4yLC5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5PcHRpb25UeXBlEhUKDW9wdGlvbl9zdHJpa2UYBiABKAESMQoWb3B0aW9uX2V4cGlyYXRpb25fZGF0ZRgHIAEoCzIRLmdvb2dsZS50eXBlLkRhdGUSEgoKbGFzdF9wcmljZRgIIAEoARIRCgliaWRfcHJpY2UYCSABKAESEQoJYXNrX3ByaWNlGAogASgBEg4KBnZvbHVtZRgLIAEoARIVCg1vcGVuX2ludGVyZXN0GAwgASgBEhgKEHQxX29wZW5faW50ZXJlc3QYDSABKAESDQoFZGVsdGEYDiABKAESDQoFZ2FtbWEYDyABKAESDQoFdGhldGEYECABKAESDAoEdmVnYRgRIAEoARIeChZpbXBsaWVkX3ZvbGF0aWxpdHlfYmlkGBIgASgBEh4KFmltcGxpZWRfdm9sYXRpbGl0eV9hc2sYEyABKAESHwoXaW1wbGllZF92b2xhdGlsaXR5X21lYW4YFCABKAEygwIKIkRhaWx5TWFya2V0RGF0YUJ5VW5kZXJseWluZ1NlcnZpY2US3AEKG0RhaWx5TWFya2V0RGF0YUJ5VW5kZXJseWluZxJHLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5LnYxLkRhaWx5TWFya2V0RGF0YUJ5VW5kZXJseWluZ1JlcXVlc3QaSC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MS5EYWlseU1hcmtldERhdGFCeVVuZGVybHlpbmdSZXNwb25zZSIqgtPkkwIkEiIvdjEvZGFpbHkvbWFya2V0ZGF0YV9ieV91bmRlcmx5aW5nYgZwcm90bzM", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_option_type]);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingRequest.
 * Use `create(DailyMarketDataByUnderlyingRequestSchema)` to create a new message.
 */
export const DailyMarketDataByUnderlyingRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_market_data_by_underlying, 0);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingResponse.
 * Use `create(DailyMarketDataByUnderlyingResponseSchema)` to create a new message.
 */
export const DailyMarketDataByUnderlyingResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_market_data_by_underlying, 1);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyMarketDataByUnderlying.
 * Use `create(DailyMarketDataByUnderlyingSchema)` to create a new message.
 */
export const DailyMarketDataByUnderlyingSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_market_data_by_underlying, 2);

/**
 * Called to request daily MarketData data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingService
 */
export const DailyMarketDataByUnderlyingService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_v1_daily_market_data_by_underlying, 0);

