// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The settlement price </i>is the official price at which a financial instrument is settled at the end of a trading day.
//<br> The settlement refers to the process of transferring securities or funds to fulfill the terms of a trade.
//<br> In futures and options markets, the settlement price is often determined by a specific mechanism outlined by the exchange and may not necessarily be the same as the closing price.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily/v1/daily_settlement.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_settlement.proto.
 */
export const file_systemathics_apis_services_daily_v1_daily_settlement = /*@__PURE__*/
  fileDesc("CjpzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseS92MS9kYWlseV9zZXR0bGVtZW50LnByb3RvEiNzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MSK2AQoXRGFpbHlTZXR0bGVtZW50c1JlcXVlc3QSQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISRQoNZGF0ZV9pbnRlcnZhbBgCIAEoCzIuLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLkRhdGVJbnRlcnZhbBISCgphZGp1c3RtZW50GAMgASgIIl4KGERhaWx5U2V0dGxlbWVudHNSZXNwb25zZRJCCgRkYXRhGAEgAygLMjQuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHkudjEuRGFpbHlTZXR0bGVtZW50ImAKD0RhaWx5U2V0dGxlbWVudBIfCgRkYXRlGAEgASgLMhEuZ29vZ2xlLnR5cGUuRGF0ZRINCgVwcmljZRgCIAEoARIOCgZ2b2x1bWUYAyABKAESDQoFc2NvcmUYBCABKAEyygEKF0RhaWx5U2V0dGxlbWVudHNTZXJ2aWNlEq4BChBEYWlseVNldHRsZW1lbnRzEjwuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHkudjEuRGFpbHlTZXR0bGVtZW50c1JlcXVlc3QaPS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MS5EYWlseVNldHRsZW1lbnRzUmVzcG9uc2UiHYLT5JMCFxIVL3YxL2RhaWx5L3NldHRsZW1lbnRzYgZwcm90bzM", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailySettlementsRequest.
 * Use `create(DailySettlementsRequestSchema)` to create a new message.
 */
export const DailySettlementsRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_settlement, 0);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailySettlementsResponse.
 * Use `create(DailySettlementsResponseSchema)` to create a new message.
 */
export const DailySettlementsResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_settlement, 1);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailySettlement.
 * Use `create(DailySettlementSchema)` to create a new message.
 */
export const DailySettlementSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_settlement, 2);

/**
 * Called to request daily Settlement price data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailySettlementsService
 */
export const DailySettlementsService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_v1_daily_settlement, 0);

