// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// The <i>Greeks</i> are a set of risk measures or sensitivities used in options trading to assess the various factors that can influence the price of an option.

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/daily/v1/daily_greeks.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Date } from "../../../../../google/type/date_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_greeks.proto.
 */
export const file_systemathics_apis_services_daily_v1_daily_greeks: GenFile = /*@__PURE__*/
  fileDesc("CjZzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseS92MS9kYWlseV9ncmVla3MucHJvdG8SI3N5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5LnYxIp0BChJEYWlseUdyZWVrc1JlcXVlc3QSQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISRQoNZGF0ZV9pbnRlcnZhbBgCIAEoCzIuLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLkRhdGVJbnRlcnZhbCJVChNEYWlseUdyZWVrc1Jlc3BvbnNlEj4KBGRhdGEYASADKAsyMC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MS5EYWlseUdyZWVrcyKFAQoLRGFpbHlHcmVla3MSHwoEZGF0ZRgBIAEoCzIRLmdvb2dsZS50eXBlLkRhdGUSDQoFZGVsdGEYAiABKAESDQoFZ2FtbWEYAyABKAESDQoFdGhldGEYBCABKAESDAoEdmVnYRgFIAEoARILCgNyaG8YBiABKAESDQoFc2NvcmUYByABKAEysQEKEkRhaWx5R3JlZWtzU2VydmljZRKaAQoLRGFpbHlHcmVla3MSNy5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MS5EYWlseUdyZWVrc1JlcXVlc3QaOC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MS5EYWlseUdyZWVrc1Jlc3BvbnNlIhiC0+STAhISEC92MS9kYWlseS9ncmVla3NiBnByb3RvMw", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * The required input to request the DailyGreeksService
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyGreeksRequest
 */
export type DailyGreeksRequest = Message<"systemathics.apis.services.daily.v1.DailyGreeksRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a ticker and exchange 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyGreeksRequest.
 * Use `create(DailyGreeksRequestSchema)` to create a new message.
 */
export const DailyGreeksRequestSchema: GenMessage<DailyGreeksRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_greeks, 0);

/**
 * Represents a daily greeks response.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyGreeksResponse
 */
export type DailyGreeksResponse = Message<"systemathics.apis.services.daily.v1.DailyGreeksResponse"> & {
  /**
   * The daily greeks: an array of DailyGreeks objects
   *
   * @generated from field: repeated systemathics.apis.services.daily.v1.DailyGreeks data = 1;
   */
  data: DailyGreeks[];
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyGreeksResponse.
 * Use `create(DailyGreeksResponseSchema)` to create a new message.
 */
export const DailyGreeksResponseSchema: GenMessage<DailyGreeksResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_greeks, 1);

/**
 * Contains the daily greeks data.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyGreeks
 */
export type DailyGreeks = Message<"systemathics.apis.services.daily.v1.DailyGreeks"> & {
  /**
   * Date of the greeks
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * Measures the sensitivity of an option's theoretical value to a change in the price of the underlying asset.
   * <br>It indicates the expected change in the option price for a one-point change in the underlying asset. 
   * <br>For example, if an option has a delta of 0.7, it suggests that the option's price will increase by $0.70 for every $1 increase in the underlying asset.
   *
   * @generated from field: double delta = 2;
   */
  delta: number;

  /**
   * Measeure sthe rate of change in the delta for each one-point increase in the underlying asset.
   * <br>It measures how much the delta of an option will change as the price of the underlying asset changes. 
   * <br>Gamma is particularly important for assessing how delta might change as the underlying asset's price fluctuates.
   *
   * @generated from field: double gamma = 3;
   */
  gamma: number;

  /**
   * A measure of the time decay on an option, the amount that an option willl lose each day due to the passage of time.
   * <br>It represents the change in the option price for a one-day decrease in the time to expiration. 
   * <br>Theta is often referred to as time decay. As the expiration date approaches, the time value of an option tends to decrease, and theta quantifies that decay.
   *
   * @generated from field: double theta = 4;
   */
  theta: number;

  /**
   * Measures the sensitivity of the price of an option to changes in implied volatility. 
   * <br>Implied volatility reflects the market's expectations for future price fluctuations. 
   * <br>Vega indicates how much the option price is expected to change for a one-percentage-point change in implied volatility.
   *
   * @generated from field: double vega = 5;
   */
  vega: number;

  /**
   * The rate at which the price of a derivative changes relative to a change in the risk-free rate of interest. 
   * <br>It represents the change in the option price for a one-percentage-point change in interest rates. 
   * <br>Rho is more relevant for options with longer time to expiration.
   *
   * @generated from field: double rho = 6;
   */
  rho: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 7;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyGreeks.
 * Use `create(DailyGreeksSchema)` to create a new message.
 */
export const DailyGreeksSchema: GenMessage<DailyGreeks> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_greeks, 2);

/**
 * Called to request daily greeks data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailyGreeksService
 */
export const DailyGreeksService: GenService<{
  /**
   * Gets daily historical greeks
   *
   * @generated from rpc systemathics.apis.services.daily.v1.DailyGreeksService.DailyGreeks
   */
  dailyGreeks: {
    methodKind: "unary";
    input: typeof DailyGreeksRequestSchema;
    output: typeof DailyGreeksResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_v1_daily_greeks, 0);

