// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The Volume Weighted Average Price</i> is similar to a moving average, except volume is included to weight the average price over a one trading day period.
// <br>It serves as a reference point for one trading day prices. Comparing current prices with the VWAP values enables to:
// <br>- mesure trading efficiency by comparing individual trades to VWAP
// <br>- highlight liquidity points as vwap reflects prices levels weighted by volume
// <br>- determine the market trend, etc.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily/v1/daily_vwap.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { Date } from "../../../../../google/type/date_pb";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_vwap.proto.
 */
export declare const file_systemathics_apis_services_daily_v1_daily_vwap: GenFile;

/**
 * The required input to request the DailyVwapsService
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyVwapsRequest
 */
export declare type DailyVwapsRequest = Message<"systemathics.apis.services.daily.v1.DailyVwapsRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a ticker and exchange 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The corporate action adjustment (dividends).
   * By default the value is set to false : the split is applied in all cases
   *
   * @generated from field: bool adjustment = 3;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyVwapsRequest.
 * Use `create(DailyVwapsRequestSchema)` to create a new message.
 */
export declare const DailyVwapsRequestSchema: GenMessage<DailyVwapsRequest>;

/**
 * Represents a daily VWAPs response.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyVwapsResponse
 */
export declare type DailyVwapsResponse = Message<"systemathics.apis.services.daily.v1.DailyVwapsResponse"> & {
  /**
   * The daily vwaps: an array of DailyVwap objects
   *
   * @generated from field: repeated systemathics.apis.services.daily.v1.DailyVwap data = 1;
   */
  data: DailyVwap[];
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyVwapsResponse.
 * Use `create(DailyVwapsResponseSchema)` to create a new message.
 */
export declare const DailyVwapsResponseSchema: GenMessage<DailyVwapsResponse>;

/**
 * Contains the daily vwaps data: date, vwap and volume.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyVwap
 */
export declare type DailyVwap = Message<"systemathics.apis.services.daily.v1.DailyVwap"> & {
  /**
   * Date of the vwap
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * Vwap of the day
   *
   * @generated from field: double price = 2;
   */
  price: number;

  /**
   * Total traded volume of the day
   *
   * @generated from field: double volume = 3;
   */
  volume: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 4;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyVwap.
 * Use `create(DailyVwapSchema)` to create a new message.
 */
export declare const DailyVwapSchema: GenMessage<DailyVwap>;

/**
 * Called to request daily VWAP data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailyVwapsService
 */
export declare const DailyVwapsService: GenService<{
  /**
   * Gets daily historical VWAPs
   *
   * @generated from rpc systemathics.apis.services.daily.v1.DailyVwapsService.DailyVwaps
   */
  dailyVwaps: {
    methodKind: "unary";
    input: typeof DailyVwapsRequestSchema;
    output: typeof DailyVwapsResponseSchema;
  },
}>;

