// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This service provides access to an daily marketdata market data service,
// enabling users to retrieve historical market data for various financial instruments.
// MarketData represents a comprehensive aggregation of all pertinent market information, 
// encompassing various data points such as bar data, best limit data, Greeks, and more.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily/v1/daily_market_data_by_underlying.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { Date } from "../../../../../google/type/date_pb";
import type { OptionType } from "../../../type/shared/v1/option_type_pb";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_market_data_by_underlying.proto.
 */
export declare const file_systemathics_apis_services_daily_v1_daily_market_data_by_underlying: GenFile;

/**
 * @generated from message systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingRequest
 */
export declare type DailyMarketDataByUnderlyingRequest = Message<"systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingRequest"> & {
  /**
   * [Mandatory] The underlying instrument identifier: a bloomberg ticker and an asset type 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier underlying_identifier = 1;
   */
  underlyingIdentifier?: Identifier;

  /**
   * [Mandatory] The date used.
   *
   * @generated from field: google.type.Date date = 2;
   */
  date?: Date;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingRequest.
 * Use `create(DailyMarketDataByUnderlyingRequestSchema)` to create a new message.
 */
export declare const DailyMarketDataByUnderlyingRequestSchema: GenMessage<DailyMarketDataByUnderlyingRequest>;

/**
 * Represents a daily marketdata by underlying response.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingResponse
 */
export declare type DailyMarketDataByUnderlyingResponse = Message<"systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingResponse"> & {
  /**
   * The daily marketdata : an array of DailyMarketDataByUnderlying objects
   *
   * @generated from field: repeated systemathics.apis.services.daily.v1.DailyMarketDataByUnderlying data = 1;
   */
  data: DailyMarketDataByUnderlying[];
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingResponse.
 * Use `create(DailyMarketDataByUnderlyingResponseSchema)` to create a new message.
 */
export declare const DailyMarketDataByUnderlyingResponseSchema: GenMessage<DailyMarketDataByUnderlyingResponse>;

/**
 * Contains the daily marketdatas information by underlying.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyMarketDataByUnderlying
 */
export declare type DailyMarketDataByUnderlying = Message<"systemathics.apis.services.daily.v1.DailyMarketDataByUnderlying"> & {
  /**
   * Date of the marketdata
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * Underlying symbol
   *
   * @generated from field: string underlying_symbol = 2;
   */
  underlyingSymbol: string;

  /**
   * Underlying price
   *
   * @generated from field: double underlying_price = 3;
   */
  underlyingPrice: number;

  /**
   * Option symbol (OPRA)
   *
   * @generated from field: string option_symbol = 4;
   */
  optionSymbol: string;

  /**
   * Option type
   *
   * @generated from field: systemathics.apis.type.shared.v1.OptionType option_type = 5;
   */
  optionType: OptionType;

  /**
   * Option strike
   *
   * @generated from field: double option_strike = 6;
   */
  optionStrike: number;

  /**
   * Option expiration date.
   *
   * @generated from field: google.type.Date option_expiration_date = 7;
   */
  optionExpirationDate?: Date;

  /**
   * The last price.
   *
   * @generated from field: double last_price = 8;
   */
  lastPrice: number;

  /**
   * The bid price.
   *
   * @generated from field: double bid_price = 9;
   */
  bidPrice: number;

  /**
   * The ask price.
   *
   * @generated from field: double ask_price = 10;
   */
  askPrice: number;

  /**
   * The volume of options traded.
   *
   * @generated from field: double volume = 11;
   */
  volume: number;

  /**
   * Open interest value.
   *
   * @generated from field: double open_interest = 12;
   */
  openInterest: number;

  /**
   * The total number of outstanding options contracts that have not been exercised or expired yet, as of the next trading day.
   *
   * @generated from field: double t1_open_interest = 13;
   */
  t1OpenInterest: number;

  /**
   * Measures the sensitivity of an option's theoretical value to a change in the price of the underlying asset.
   * <br>It indicates the expected change in the option price for a one-point change in the underlying asset. 
   * <br>For example, if an option has a delta of 0.7, it suggests that the option's price will increase by $0.70 for every $1 increase in the underlying asset.
   *
   * @generated from field: double delta = 14;
   */
  delta: number;

  /**
   * Measeure sthe rate of change in the delta for each one-point increase in the underlying asset.
   * <br>It measures how much the delta of an option will change as the price of the underlying asset changes. 
   * <br>Gamma is particularly important for assessing how delta might change as the underlying asset's price fluctuates.
   *
   * @generated from field: double gamma = 15;
   */
  gamma: number;

  /**
   * A measure of the time decay on an option, the amount that an option willl lose each day due to the passage of time.
   * <br>It represents the change in the option price for a one-day decrease in the time to expiration. 
   * <br>Theta is often referred to as time decay. As the expiration date approaches, the time value of an option tends to decrease, and theta quantifies that decay.
   *
   * @generated from field: double theta = 16;
   */
  theta: number;

  /**
   * Measures the sensitivity of the price of an option to changes in implied volatility. 
   * <br>Implied volatility reflects the market's expectations for future price fluctuations. 
   * <br>Vega indicates how much the option price is expected to change for a one-percentage-point change in implied volatility.
   *
   * @generated from field: double vega = 17;
   */
  vega: number;

  /**
   * The implied volatility bid.
   *
   * @generated from field: double implied_volatility_bid = 18;
   */
  impliedVolatilityBid: number;

  /**
   * The implied volatility ask.
   *
   * @generated from field: double implied_volatility_ask = 19;
   */
  impliedVolatilityAsk: number;

  /**
   * The implied volatility mean.
   *
   * @generated from field: double implied_volatility_mean = 20;
   */
  impliedVolatilityMean: number;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyMarketDataByUnderlying.
 * Use `create(DailyMarketDataByUnderlyingSchema)` to create a new message.
 */
export declare const DailyMarketDataByUnderlyingSchema: GenMessage<DailyMarketDataByUnderlying>;

/**
 * Called to request daily MarketData data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingService
 */
export declare const DailyMarketDataByUnderlyingService: GenService<{
  /**
   * @generated from rpc systemathics.apis.services.daily.v1.DailyMarketDataByUnderlyingService.DailyMarketDataByUnderlying
   */
  dailyMarketDataByUnderlying: {
    methodKind: "unary";
    input: typeof DailyMarketDataByUnderlyingRequestSchema;
    output: typeof DailyMarketDataByUnderlyingResponseSchema;
  },
}>;

