// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The Implied Volatility</i> is the estimated volatility of the option strike over the period of the option.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily/v1/daily_implied_volatility.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { Date } from "../../../../../google/type/date_pb";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_implied_volatility.proto.
 */
export declare const file_systemathics_apis_services_daily_v1_daily_implied_volatility: GenFile;

/**
 * The required input to request the DailyImpliedVolatilitiesService
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyImpliedVolatilitiesRequest
 */
export declare type DailyImpliedVolatilitiesRequest = Message<"systemathics.apis.services.daily.v1.DailyImpliedVolatilitiesRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyImpliedVolatilitiesRequest.
 * Use `create(DailyImpliedVolatilitiesRequestSchema)` to create a new message.
 */
export declare const DailyImpliedVolatilitiesRequestSchema: GenMessage<DailyImpliedVolatilitiesRequest>;

/**
 * Represents a daily implied volatility response.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyImpliedVolatilitiesResponse
 */
export declare type DailyImpliedVolatilitiesResponse = Message<"systemathics.apis.services.daily.v1.DailyImpliedVolatilitiesResponse"> & {
  /**
   * The daily implied volatility: an array of DailyImpliedVolatility objects
   *
   * @generated from field: repeated systemathics.apis.services.daily.v1.DailyImpliedVolatility data = 1;
   */
  data: DailyImpliedVolatility[];
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyImpliedVolatilitiesResponse.
 * Use `create(DailyImpliedVolatilitiesResponseSchema)` to create a new message.
 */
export declare const DailyImpliedVolatilitiesResponseSchema: GenMessage<DailyImpliedVolatilitiesResponse>;

/**
 * Contains the daily implied volatility data: date and value.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyImpliedVolatility
 */
export declare type DailyImpliedVolatility = Message<"systemathics.apis.services.daily.v1.DailyImpliedVolatility"> & {
  /**
   * Date of the implied volatility
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * The implied volatility of the day
   *
   * @generated from field: double implied_volatility = 2;
   */
  impliedVolatility: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 3;
   */
  score: number;

  /**
   * The implied volatility for a 30-day call option
   *
   * @generated from field: double implied_volatility_30_call = 4;
   */
  impliedVolatility30Call: number;

  /**
   * The implied volatility for a 30-day put option
   *
   * @generated from field: double implied_volatility_30_put = 5;
   */
  impliedVolatility30Put: number;

  /**
   * The mean implied volatility for a 30-day period.
   *
   * @generated from field: double implied_volatility_30_mean = 6;
   */
  impliedVolatility30Mean: number;

  /**
   * The implied volatility for a 60-day call option
   *
   * @generated from field: double implied_volatility_60_call = 7;
   */
  impliedVolatility60Call: number;

  /**
   * The implied volatility for a 60-day put option
   *
   * @generated from field: double implied_volatility_60_put = 8;
   */
  impliedVolatility60Put: number;

  /**
   * The mean implied volatility for a 60-day period.
   *
   * @generated from field: double implied_volatility_60_mean = 9;
   */
  impliedVolatility60Mean: number;

  /**
   * The implied volatility for a 90-day call option
   *
   * @generated from field: double implied_volatility_90_call = 10;
   */
  impliedVolatility90Call: number;

  /**
   * The implied volatility for a 90-day put option
   *
   * @generated from field: double implied_volatility_90_put = 11;
   */
  impliedVolatility90Put: number;

  /**
   * The mean implied volatility for a 90-day period.
   *
   * @generated from field: double implied_volatility_90_mean = 12;
   */
  impliedVolatility90Mean: number;

  /**
   * The implied volatility for a 120-day call option
   *
   * @generated from field: double implied_volatility_120_call = 13;
   */
  impliedVolatility120Call: number;

  /**
   * The implied volatility for a 120-day put option
   *
   * @generated from field: double implied_volatility_120_put = 14;
   */
  impliedVolatility120Put: number;

  /**
   * The mean implied volatility for a 120-day period.
   *
   * @generated from field: double implied_volatility_120_mean = 15;
   */
  impliedVolatility120Mean: number;

  /**
   * The implied volatility for a 150-day call option
   *
   * @generated from field: double implied_volatility_150_call = 16;
   */
  impliedVolatility150Call: number;

  /**
   * The implied volatility for a 150-day put option
   *
   * @generated from field: double implied_volatility_150_put = 17;
   */
  impliedVolatility150Put: number;

  /**
   * The mean implied volatility for a 150-day period.
   *
   * @generated from field: double implied_volatility_150_mean = 18;
   */
  impliedVolatility150Mean: number;

  /**
   * The implied volatility for a 180-day call option
   *
   * @generated from field: double implied_volatility_180_call = 19;
   */
  impliedVolatility180Call: number;

  /**
   * The implied volatility for a 180-day put option
   *
   * @generated from field: double implied_volatility_180_put = 20;
   */
  impliedVolatility180Put: number;

  /**
   * The mean implied volatility for a 180-day period.
   *
   * @generated from field: double implied_volatility_180_mean = 21;
   */
  impliedVolatility180Mean: number;

  /**
   * The implied volatility for a 360-day call option
   *
   * @generated from field: double implied_volatility_360_call = 22;
   */
  impliedVolatility360Call: number;

  /**
   * The implied volatility for a 360-day put option
   *
   * @generated from field: double implied_volatility_360_put = 23;
   */
  impliedVolatility360Put: number;

  /**
   * The mean implied volatility for a 360-day period.
   *
   * @generated from field: double implied_volatility_360_mean = 24;
   */
  impliedVolatility360Mean: number;

  /**
   * The implied volatility bid.
   *
   * @generated from field: double implied_volatility_bid = 25;
   */
  impliedVolatilityBid: number;

  /**
   * The implied volatility ask.
   *
   * @generated from field: double implied_volatility_ask = 26;
   */
  impliedVolatilityAsk: number;

  /**
   * The implied volatility mean.
   *
   * @generated from field: double implied_volatility_mean = 27;
   */
  impliedVolatilityMean: number;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyImpliedVolatility.
 * Use `create(DailyImpliedVolatilitySchema)` to create a new message.
 */
export declare const DailyImpliedVolatilitySchema: GenMessage<DailyImpliedVolatility>;

/**
 * Called to request daily ImpliedVolatility data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailyImpliedVolatilitiesService
 */
export declare const DailyImpliedVolatilitiesService: GenService<{
  /**
   * Gets daily historical implied volatility
   *
   * @generated from rpc systemathics.apis.services.daily.v1.DailyImpliedVolatilitiesService.DailyImpliedVolatilities
   */
  dailyImpliedVolatilities: {
    methodKind: "unary";
    input: typeof DailyImpliedVolatilitiesRequestSchema;
    output: typeof DailyImpliedVolatilitiesResponseSchema;
  },
}>;

