// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The Volume Weighted Average Price</i> is similar to a moving average, except volume is included to weight the average price over a one trading day period.
// <br>It serves as a reference point for one trading day prices. Comparing current prices with the VWAP values enables to:
// <br>- mesure trading efficiency by comparing individual trades to VWAP
// <br>- highlight liquidity points as vwap reflects prices levels weighted by volume
// <br>- determine the market trend, etc.

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/daily/v1/daily_vwap.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Date } from "../../../../../google/type/date_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_vwap.proto.
 */
export const file_systemathics_apis_services_daily_v1_daily_vwap: GenFile = /*@__PURE__*/
  fileDesc("CjRzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseS92MS9kYWlseV92d2FwLnByb3RvEiNzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MSKwAQoRRGFpbHlWd2Fwc1JlcXVlc3QSQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISRQoNZGF0ZV9pbnRlcnZhbBgCIAEoCzIuLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLkRhdGVJbnRlcnZhbBISCgphZGp1c3RtZW50GAMgASgIIlIKEkRhaWx5VndhcHNSZXNwb25zZRI8CgRkYXRhGAEgAygLMi4uc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHkudjEuRGFpbHlWd2FwIloKCURhaWx5VndhcBIfCgRkYXRlGAEgASgLMhEuZ29vZ2xlLnR5cGUuRGF0ZRINCgVwcmljZRgCIAEoARIOCgZ2b2x1bWUYAyABKAESDQoFc2NvcmUYBCABKAEyrAEKEURhaWx5VndhcHNTZXJ2aWNlEpYBCgpEYWlseVZ3YXBzEjYuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHkudjEuRGFpbHlWd2Fwc1JlcXVlc3QaNy5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MS5EYWlseVZ3YXBzUmVzcG9uc2UiF4LT5JMCERIPL3YxL2RhaWx5L3Z3YXBzYgZwcm90bzM", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * The required input to request the DailyVwapsService
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyVwapsRequest
 */
export type DailyVwapsRequest = Message<"systemathics.apis.services.daily.v1.DailyVwapsRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a ticker and exchange 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The corporate action adjustment (dividends).
   * By default the value is set to false : the split is applied in all cases
   *
   * @generated from field: bool adjustment = 3;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyVwapsRequest.
 * Use `create(DailyVwapsRequestSchema)` to create a new message.
 */
export const DailyVwapsRequestSchema: GenMessage<DailyVwapsRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_vwap, 0);

/**
 * Represents a daily VWAPs response.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyVwapsResponse
 */
export type DailyVwapsResponse = Message<"systemathics.apis.services.daily.v1.DailyVwapsResponse"> & {
  /**
   * The daily vwaps: an array of DailyVwap objects
   *
   * @generated from field: repeated systemathics.apis.services.daily.v1.DailyVwap data = 1;
   */
  data: DailyVwap[];
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyVwapsResponse.
 * Use `create(DailyVwapsResponseSchema)` to create a new message.
 */
export const DailyVwapsResponseSchema: GenMessage<DailyVwapsResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_vwap, 1);

/**
 * Contains the daily vwaps data: date, vwap and volume.
 *
 * @generated from message systemathics.apis.services.daily.v1.DailyVwap
 */
export type DailyVwap = Message<"systemathics.apis.services.daily.v1.DailyVwap"> & {
  /**
   * Date of the vwap
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * Vwap of the day
   *
   * @generated from field: double price = 2;
   */
  price: number;

  /**
   * Total traded volume of the day
   *
   * @generated from field: double volume = 3;
   */
  volume: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 4;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyVwap.
 * Use `create(DailyVwapSchema)` to create a new message.
 */
export const DailyVwapSchema: GenMessage<DailyVwap> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_vwap, 2);

/**
 * Called to request daily VWAP data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailyVwapsService
 */
export const DailyVwapsService: GenService<{
  /**
   * Gets daily historical VWAPs
   *
   * @generated from rpc systemathics.apis.services.daily.v1.DailyVwapsService.DailyVwaps
   */
  dailyVwaps: {
    methodKind: "unary";
    input: typeof DailyVwapsRequestSchema;
    output: typeof DailyVwapsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_v1_daily_vwap, 0);

