// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Daily prices illustrates daily price movements for an instrument over a look back period.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily/v1/daily_prices.proto (package systemathics.apis.services.daily.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";

/**
 * Describes the file systemathics/apis/services/daily/v1/daily_prices.proto.
 */
export const file_systemathics_apis_services_daily_v1_daily_prices = /*@__PURE__*/
  fileDesc("CjZzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseS92MS9kYWlseV9wcmljZXMucHJvdG8SI3N5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5LnYxIrEBChJEYWlseVByaWNlc1JlcXVlc3QSQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISRQoNZGF0ZV9pbnRlcnZhbBgCIAEoCzIuLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLkRhdGVJbnRlcnZhbBISCgphZGp1c3RtZW50GAMgASgIIlQKE0RhaWx5UHJpY2VzUmVzcG9uc2USPQoEZGF0YRgBIAMoCzIvLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5LnYxLkRhaWx5UHJpY2UiWwoKRGFpbHlQcmljZRIfCgRkYXRlGAEgASgLMhEuZ29vZ2xlLnR5cGUuRGF0ZRINCgVwcmljZRgCIAEoARIOCgZ2b2x1bWUYAyABKAESDQoFc2NvcmUYBCABKAEysQEKEkRhaWx5UHJpY2VzU2VydmljZRKaAQoLRGFpbHlQcmljZXMSNy5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MS5EYWlseVByaWNlc1JlcXVlc3QaOC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseS52MS5EYWlseVByaWNlc1Jlc3BvbnNlIhiC0+STAhISEC92MS9kYWlseS9wcmljZXNiBnByb3RvMw", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyPricesRequest.
 * Use `create(DailyPricesRequestSchema)` to create a new message.
 */
export const DailyPricesRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_prices, 0);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyPricesResponse.
 * Use `create(DailyPricesResponseSchema)` to create a new message.
 */
export const DailyPricesResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_prices, 1);

/**
 * Describes the message systemathics.apis.services.daily.v1.DailyPrice.
 * Use `create(DailyPriceSchema)` to create a new message.
 */
export const DailyPriceSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_v1_daily_prices, 2);

/**
 * Called to request daily prices data. 
 *
 * @generated from service systemathics.apis.services.daily.v1.DailyPricesService
 */
export const DailyPricesService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_v1_daily_prices, 0);

