// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// SMA is formed by computing the average price of a security over a specific number of points. 
// <br>As its name implies, simple moving average is an average that moves. Old data is dropped and new data becomes available, causing the average to move along the time.
// <br><i>N-points SMA data point</i> is computed by adding up the last N period's trade prices and then dividing by N as follows: $$ SMA = \frac{\Sigma Close_n}{N} $$
// <br>Where:
// <br>- <i>Close n</i> is the close price of the <i>period n</i>
// <br>- <i>N</i> is the count of time periods

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/daily_analytics/v1/daily_sma.proto (package systemathics.apis.services.daily_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { Date } from "../../../../../google/type/date_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/daily_analytics/v1/daily_sma.proto.
 */
export const file_systemathics_apis_services_daily_analytics_v1_daily_sma: GenFile = /*@__PURE__*/
  fileDesc("Cj1zeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseV9hbmFseXRpY3MvdjEvZGFpbHlfc21hLnByb3RvEi1zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEivgEKD0RhaWx5U21hUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchJFCg1kYXRlX2ludGVydmFsGAIgASgLMi4uc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuRGF0ZUludGVydmFsEg4KBmxlbmd0aBgDIAEoBRISCgphZGp1c3RtZW50GAQgASgIIl0KEERhaWx5U21hUmVzcG9uc2USSQoEZGF0YRgBIAMoCzI7LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5X2FuYWx5dGljcy52MS5EYWlseVNtYURhdGEibQoMRGFpbHlTbWFEYXRhEh8KBGRhdGUYASABKAsyES5nb29nbGUudHlwZS5EYXRlEg0KBXZhbHVlGAIgASgBEi0KB2F2ZXJhZ2UYAyABKAsyHC5nb29nbGUucHJvdG9idWYuRG91YmxlVmFsdWUywAEKD0RhaWx5U21hU2VydmljZRKsAQoIRGFpbHlTbWESPi5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEuRGFpbHlTbWFSZXF1ZXN0Gj8uc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHlfYW5hbHl0aWNzLnYxLkRhaWx5U21hUmVzcG9uc2UiH4LT5JMCGRIXL3YxL2RhaWx5LWFuYWx5dGljcy9zbWFiBnByb3RvMw", [file_google_api_annotations, file_google_protobuf_wrappers, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * The required input to request the DailySmaService.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailySmaRequest
 */
export type DailySmaRequest = Message<"systemathics.apis.services.daily_analytics.v1.DailySmaRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;

  /**
   * [Mandatory] The simple moving average window length (period : points number)
   *
   * @generated from field: int32 length = 3;
   */
  length: number;

  /**
   * [Optional] The corporate action adjustment (dividends).
   * By default the value is set to false : the split is applied in all cases
   *
   * @generated from field: bool adjustment = 4;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailySmaRequest.
 * Use `create(DailySmaRequestSchema)` to create a new message.
 */
export const DailySmaRequestSchema: GenMessage<DailySmaRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_sma, 0);

/**
 * Represents a daily simple moving average response.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailySmaResponse
 */
export type DailySmaResponse = Message<"systemathics.apis.services.daily_analytics.v1.DailySmaResponse"> & {
  /**
   * The daily simple moving averages: an array of DailySmaData objects
   *
   * @generated from field: repeated systemathics.apis.services.daily_analytics.v1.DailySmaData data = 1;
   */
  data: DailySmaData[];
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailySmaResponse.
 * Use `create(DailySmaResponseSchema)` to create a new message.
 */
export const DailySmaResponseSchema: GenMessage<DailySmaResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_sma, 1);

/**
 * Contains the daily simple moving average data: date and value.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailySmaData
 */
export type DailySmaData = Message<"systemathics.apis.services.daily_analytics.v1.DailySmaData"> & {
  /**
   * Date of the simple moving average
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * The data used to calculate the average of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * The simple moving average value of the day for the last n data points (length)
   *
   * @generated from field: google.protobuf.DoubleValue average = 3;
   */
  average?: number;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailySmaData.
 * Use `create(DailySmaDataSchema)` to create a new message.
 */
export const DailySmaDataSchema: GenMessage<DailySmaData> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_sma, 2);

/**
 * Called to request daily simple moving average data. 
 *
 * @generated from service systemathics.apis.services.daily_analytics.v1.DailySmaService
 */
export const DailySmaService: GenService<{
  /**
   * Gets daily simple moving average data
   *
   * @generated from rpc systemathics.apis.services.daily_analytics.v1.DailySmaService.DailySma
   */
  dailySma: {
    methodKind: "unary";
    input: typeof DailySmaRequestSchema;
    output: typeof DailySmaResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_analytics_v1_daily_sma, 0);

