// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// EMA reduces the lag by applying greater weight to recent data points.
// <br>The weighting applied to the most recent price depends on the number of points in the moving average; The smaller the point count is, the more weight is applied to the most recent price.
// <br><i>N-points EMA data point</i> is computed using the previous' EMA value and the weighting multiplier as follows: $$ EMA = (Close-EMAp)*k+EMAp $$ Where:
// <br>- <i>Close</i> is the close price
// <br>- <i>EMAp</i> is the previous point' EMA value; SMA is used as the EMAp in the first calculation
// <br>- <i>N</i> is the count of points
// <br>- <i>k = 2 / N+1</i> is the Weighting Multiplier

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily_analytics/v1/daily_ema.proto (package systemathics.apis.services.daily_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { Date } from "../../../../../google/type/date_pb";

/**
 * Describes the file systemathics/apis/services/daily_analytics/v1/daily_ema.proto.
 */
export declare const file_systemathics_apis_services_daily_analytics_v1_daily_ema: GenFile;

/**
 * The required input to request the DailyEmaService.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyEmaRequest
 */
export declare type DailyEmaRequest = Message<"systemathics.apis.services.daily_analytics.v1.DailyEmaRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;

  /**
   * [Mandatory] The exponential moving average window length (period : points number)
   *
   * @generated from field: int32 length = 3;
   */
  length: number;

  /**
   * [Optional] The corporate action adjustment (dividends).
   * By default the value is set to false : the split is applied in all cases
   *
   * @generated from field: bool adjustment = 4;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyEmaRequest.
 * Use `create(DailyEmaRequestSchema)` to create a new message.
 */
export declare const DailyEmaRequestSchema: GenMessage<DailyEmaRequest>;

/**
 * Represents a daily exponential moving average response.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyEmaResponse
 */
export declare type DailyEmaResponse = Message<"systemathics.apis.services.daily_analytics.v1.DailyEmaResponse"> & {
  /**
   * The daily exponential moving averages: an array of DailyEmaData objects
   *
   * @generated from field: repeated systemathics.apis.services.daily_analytics.v1.DailyEmaData data = 1;
   */
  data: DailyEmaData[];
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyEmaResponse.
 * Use `create(DailyEmaResponseSchema)` to create a new message.
 */
export declare const DailyEmaResponseSchema: GenMessage<DailyEmaResponse>;

/**
 * Contains the daily exponential moving average data: date and value.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyEmaData
 */
export declare type DailyEmaData = Message<"systemathics.apis.services.daily_analytics.v1.DailyEmaData"> & {
  /**
   * Date of the exponential moving average
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * The data used to calculate the average of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * The exponential moving average value of the day
   *
   * @generated from field: double average = 3;
   */
  average: number;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyEmaData.
 * Use `create(DailyEmaDataSchema)` to create a new message.
 */
export declare const DailyEmaDataSchema: GenMessage<DailyEmaData>;

/**
 * Called to request daily exponential moving average data. 
 *
 * @generated from service systemathics.apis.services.daily_analytics.v1.DailyEmaService
 */
export declare const DailyEmaService: GenService<{
  /**
   * Gets daily exponential moving average data
   *
   * @generated from rpc systemathics.apis.services.daily_analytics.v1.DailyEmaService.DailyEma
   */
  dailyEma: {
    methodKind: "unary";
    input: typeof DailyEmaRequestSchema;
    output: typeof DailyEmaResponseSchema;
  },
}>;

