// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>Moving Average Convergence/Divergence Oscillator</i> was developed by Gerald Appel and represents the difference between two moving averages of different lengths.
// <br>As its name implies, MACD is all about convergence and divergence of the two moving averages. MACD oscilaltes around the zero line as follows:
// <br>- positive values increase as the shorter moving average diverges further from the longer one
// <br>- negative values indicate that the shorter moving average is below the longer one
// <br><br>MACD is computed as follows: $$ MACD = short EMA - long EMA $$

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily_analytics/v1/daily_macd.proto (package systemathics.apis.services.daily_analytics.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";

/**
 * Describes the file systemathics/apis/services/daily_analytics/v1/daily_macd.proto.
 */
export const file_systemathics_apis_services_daily_analytics_v1_daily_macd = /*@__PURE__*/
  fileDesc("Cj5zeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseV9hbmFseXRpY3MvdjEvZGFpbHlfbWFjZC5wcm90bxItc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHlfYW5hbHl0aWNzLnYxIswBChBEYWlseU1hY2RSZXF1ZXN0EkAKCmlkZW50aWZpZXIYASABKAsyLC5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5JZGVudGlmaWVyEkUKDWRhdGVfaW50ZXJ2YWwYAiABKAsyLi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5EYXRlSW50ZXJ2YWwSDAoEbG9uZxgDIAEoBRINCgVzaG9ydBgEIAEoBRISCgphZGp1c3RtZW50GAUgASgIIl8KEURhaWx5TWFjZFJlc3BvbnNlEkoKBGRhdGEYASADKAsyPC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEuRGFpbHlNYWNkRGF0YSJqCg1EYWlseU1hY2REYXRhEh8KBGRhdGUYASABKAsyES5nb29nbGUudHlwZS5EYXRlEg0KBXZhbHVlGAIgASgBEgwKBG1hY2QYAyABKAESDQoFc2hvcnQYBCABKAESDAoEbG9uZxgFIAEoATLFAQoQRGFpbHlNYWNkU2VydmljZRKwAQoJRGFpbHlNYWNkEj8uc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHlfYW5hbHl0aWNzLnYxLkRhaWx5TWFjZFJlcXVlc3QaQC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEuRGFpbHlNYWNkUmVzcG9uc2UiIILT5JMCGhIYL3YxL2RhaWx5LWFuYWx5dGljcy9tYWNkYgZwcm90bzM", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyMacdRequest.
 * Use `create(DailyMacdRequestSchema)` to create a new message.
 */
export const DailyMacdRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_macd, 0);

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyMacdResponse.
 * Use `create(DailyMacdResponseSchema)` to create a new message.
 */
export const DailyMacdResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_macd, 1);

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyMacdData.
 * Use `create(DailyMacdDataSchema)` to create a new message.
 */
export const DailyMacdDataSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_macd, 2);

/**
 * Called to request daily moving average convergence divergence data. 
 *
 * @generated from service systemathics.apis.services.daily_analytics.v1.DailyMacdService
 */
export const DailyMacdService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_analytics_v1_daily_macd, 0);

