// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// EMA reduces the lag by applying greater weight to recent data points.
// <br>The weighting applied to the most recent price depends on the number of points in the moving average; The smaller the point count is, the more weight is applied to the most recent price.
// <br><i>N-points EMA data point</i> is computed using the previous' EMA value and the weighting multiplier as follows: $$ EMA = (Close-EMAp)*k+EMAp $$ Where:
// <br>- <i>Close</i> is the close price
// <br>- <i>EMAp</i> is the previous point' EMA value; SMA is used as the EMAp in the first calculation
// <br>- <i>N</i> is the count of points
// <br>- <i>k = 2 / N+1</i> is the Weighting Multiplier

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/daily_analytics/v1/daily_ema.proto (package systemathics.apis.services.daily_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Date } from "../../../../../google/type/date_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/daily_analytics/v1/daily_ema.proto.
 */
export const file_systemathics_apis_services_daily_analytics_v1_daily_ema: GenFile = /*@__PURE__*/
  fileDesc("Cj1zeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseV9hbmFseXRpY3MvdjEvZGFpbHlfZW1hLnByb3RvEi1zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEivgEKD0RhaWx5RW1hUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchJFCg1kYXRlX2ludGVydmFsGAIgASgLMi4uc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuRGF0ZUludGVydmFsEg4KBmxlbmd0aBgDIAEoBRISCgphZGp1c3RtZW50GAQgASgIIl0KEERhaWx5RW1hUmVzcG9uc2USSQoEZGF0YRgBIAMoCzI7LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5X2FuYWx5dGljcy52MS5EYWlseUVtYURhdGEiTwoMRGFpbHlFbWFEYXRhEh8KBGRhdGUYASABKAsyES5nb29nbGUudHlwZS5EYXRlEg0KBXZhbHVlGAIgASgBEg8KB2F2ZXJhZ2UYAyABKAEywAEKD0RhaWx5RW1hU2VydmljZRKsAQoIRGFpbHlFbWESPi5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEuRGFpbHlFbWFSZXF1ZXN0Gj8uc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHlfYW5hbHl0aWNzLnYxLkRhaWx5RW1hUmVzcG9uc2UiH4LT5JMCGRIXL3YxL2RhaWx5LWFuYWx5dGljcy9lbWFiBnByb3RvMw", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * The required input to request the DailyEmaService.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyEmaRequest
 */
export type DailyEmaRequest = Message<"systemathics.apis.services.daily_analytics.v1.DailyEmaRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;

  /**
   * [Mandatory] The exponential moving average window length (period : points number)
   *
   * @generated from field: int32 length = 3;
   */
  length: number;

  /**
   * [Optional] The corporate action adjustment (dividends).
   * By default the value is set to false : the split is applied in all cases
   *
   * @generated from field: bool adjustment = 4;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyEmaRequest.
 * Use `create(DailyEmaRequestSchema)` to create a new message.
 */
export const DailyEmaRequestSchema: GenMessage<DailyEmaRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_ema, 0);

/**
 * Represents a daily exponential moving average response.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyEmaResponse
 */
export type DailyEmaResponse = Message<"systemathics.apis.services.daily_analytics.v1.DailyEmaResponse"> & {
  /**
   * The daily exponential moving averages: an array of DailyEmaData objects
   *
   * @generated from field: repeated systemathics.apis.services.daily_analytics.v1.DailyEmaData data = 1;
   */
  data: DailyEmaData[];
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyEmaResponse.
 * Use `create(DailyEmaResponseSchema)` to create a new message.
 */
export const DailyEmaResponseSchema: GenMessage<DailyEmaResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_ema, 1);

/**
 * Contains the daily exponential moving average data: date and value.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyEmaData
 */
export type DailyEmaData = Message<"systemathics.apis.services.daily_analytics.v1.DailyEmaData"> & {
  /**
   * Date of the exponential moving average
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * The data used to calculate the average of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * The exponential moving average value of the day
   *
   * @generated from field: double average = 3;
   */
  average: number;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyEmaData.
 * Use `create(DailyEmaDataSchema)` to create a new message.
 */
export const DailyEmaDataSchema: GenMessage<DailyEmaData> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_ema, 2);

/**
 * Called to request daily exponential moving average data. 
 *
 * @generated from service systemathics.apis.services.daily_analytics.v1.DailyEmaService
 */
export const DailyEmaService: GenService<{
  /**
   * Gets daily exponential moving average data
   *
   * @generated from rpc systemathics.apis.services.daily_analytics.v1.DailyEmaService.DailyEma
   */
  dailyEma: {
    methodKind: "unary";
    input: typeof DailyEmaRequestSchema;
    output: typeof DailyEmaResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_analytics_v1_daily_ema, 0);

