// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Bollinger bands were created by John Bollinger, they are envelopes and plotted around the moving average. 
// <br> The width of the bands is based on the standard deviaton of the closing prices from a moving average as follows:
// <br><i>- Middle band = n-period moving average</i>
// <br><i>- Upper band = Middle band + (k * n-period standard deviation)</i>
// <br><i>- Lower band = Middle band - (k * n-period standard deviation)</i>
// <br><i> Where n is the number of periods and k is factor to apply to the standard deviation value, k=2 as default value.</i>

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily_analytics/v1/daily_bollinger.proto (package systemathics.apis.services.daily_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { Date } from "../../../../../google/type/date_pb";

/**
 * Describes the file systemathics/apis/services/daily_analytics/v1/daily_bollinger.proto.
 */
export declare const file_systemathics_apis_services_daily_analytics_v1_daily_bollinger: GenFile;

/**
 * The required input to request the DailyBollingerService.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyBollingerRequest
 */
export declare type DailyBollingerRequest = Message<"systemathics.apis.services.daily_analytics.v1.DailyBollingerRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;

  /**
   * [Mandatory] The simple moving average window length (period: data points number)
   *
   * @generated from field: int32 length = 3;
   */
  length: number;

  /**
   * [Mandatory] The standard deviation window length
   *
   * @generated from field: double deviation = 4;
   */
  deviation: number;

  /**
   * [Optional] The corporate action adjustment (dividends).
   * By default the value is set to false : the split is applied in all cases
   *
   * @generated from field: bool adjustment = 5;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyBollingerRequest.
 * Use `create(DailyBollingerRequestSchema)` to create a new message.
 */
export declare const DailyBollingerRequestSchema: GenMessage<DailyBollingerRequest>;

/**
 * The daily bars response contains an array of Bollinger bands.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyBollingerResponse
 */
export declare type DailyBollingerResponse = Message<"systemathics.apis.services.daily_analytics.v1.DailyBollingerResponse"> & {
  /**
   * The daily Bollinger bands: an array of DailyBollingerData objects
   *
   * @generated from field: repeated systemathics.apis.services.daily_analytics.v1.DailyBollingerData data = 1;
   */
  data: DailyBollingerData[];
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyBollingerResponse.
 * Use `create(DailyBollingerResponseSchema)` to create a new message.
 */
export declare const DailyBollingerResponseSchema: GenMessage<DailyBollingerResponse>;

/**
 * Contains the daily Bollinger bands data: date, lower, middle and upper.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyBollingerData
 */
export declare type DailyBollingerData = Message<"systemathics.apis.services.daily_analytics.v1.DailyBollingerData"> & {
  /**
   * Date of Bollinger bands
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * The data used to calculate the Bollinger bands of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * Bollinger lower band value of the day
   * <br><i>Lower band = Middle band - (k * n-period standard deviation)</i>
   *
   * @generated from field: google.protobuf.DoubleValue lower = 3;
   */
  lower?: number;

  /**
   * Bollinger upper band value of the day
   * <br><i>Upper band = Middle band + (k * n-period standard deviation)</i>
   *
   * @generated from field: google.protobuf.DoubleValue upper = 4;
   */
  upper?: number;

  /**
   * Bollinger middle band value of the day
   * <br><i>Middle band = n-period moving average</i>
   *
   * @generated from field: google.protobuf.DoubleValue middle = 5;
   */
  middle?: number;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyBollingerData.
 * Use `create(DailyBollingerDataSchema)` to create a new message.
 */
export declare const DailyBollingerDataSchema: GenMessage<DailyBollingerData>;

/**
 * Called to request daily Bollinger bands data. 
 *
 * @generated from service systemathics.apis.services.daily_analytics.v1.DailyBollingerService
 */
export declare const DailyBollingerService: GenService<{
  /**
   * Gets daily Bollinger bands data
   *
   * @generated from rpc systemathics.apis.services.daily_analytics.v1.DailyBollingerService.DailyBollinger
   */
  dailyBollinger: {
    methodKind: "unary";
    input: typeof DailyBollingerRequestSchema;
    output: typeof DailyBollingerResponseSchema;
  },
}>;

