// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The Relative Strength Index</i>, developed by J. Welles Wilder measures the speed and change of price movements.
// <br>RSI oscillates between zero and 100. Traditionally the RSI is considered <i>overbought</i> when above 70 and <i>oversold</i> when below 30.
// <br><br>RSI is computed as follows: $$ RSI = 100 - \frac{100}{1 + RS} $$ Where:
// <br>- <i>RS = AvgU/AvgD</i> is the <i>relative strength
// <br>- <i>AvgU</i> average of last <i>N close prices</i> up moves
// <br>- <i>AvgD</i> average of last <i>N close prices</i> down moves
// <br>- <i>N</i> is the period of the RSI

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily_analytics/v1/daily_rsi.proto (package systemathics.apis.services.daily_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { Date } from "../../../../../google/type/date_pb";

/**
 * Describes the file systemathics/apis/services/daily_analytics/v1/daily_rsi.proto.
 */
export declare const file_systemathics_apis_services_daily_analytics_v1_daily_rsi: GenFile;

/**
 * The required input to request the DailyRsiService.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyRsiRequest
 */
export declare type DailyRsiRequest = Message<"systemathics.apis.services.daily_analytics.v1.DailyRsiRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;

  /**
   * [Mandatory] The relative strength index window length (period: points number)
   *
   * @generated from field: int32 length = 3;
   */
  length: number;

  /**
   * [Optional] The corporate action adjustment (dividends).
   * By default the value is set to false : the split is applied in all cases
   *
   * @generated from field: bool adjustment = 4;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyRsiRequest.
 * Use `create(DailyRsiRequestSchema)` to create a new message.
 */
export declare const DailyRsiRequestSchema: GenMessage<DailyRsiRequest>;

/**
 * Represents a daily relative strength index response.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyRsiResponse
 */
export declare type DailyRsiResponse = Message<"systemathics.apis.services.daily_analytics.v1.DailyRsiResponse"> & {
  /**
   * The daily relative strength index: an array of DailyRsiData objects
   *
   * @generated from field: repeated systemathics.apis.services.daily_analytics.v1.DailyRsiData data = 1;
   */
  data: DailyRsiData[];
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyRsiResponse.
 * Use `create(DailyRsiResponseSchema)` to create a new message.
 */
export declare const DailyRsiResponseSchema: GenMessage<DailyRsiResponse>;

/**
 * Contains the daily relative strength index data: date and value.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyRsiData
 */
export declare type DailyRsiData = Message<"systemathics.apis.services.daily_analytics.v1.DailyRsiData"> & {
  /**
   * Date of the relative strength index
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * The data used to calculate the relative strength index of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * Relative strength index value of the day
   *
   * @generated from field: double rsi = 3;
   */
  rsi: number;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyRsiData.
 * Use `create(DailyRsiDataSchema)` to create a new message.
 */
export declare const DailyRsiDataSchema: GenMessage<DailyRsiData>;

/**
 * Called to request daily relative strength index data. 
 *
 * @generated from service systemathics.apis.services.daily_analytics.v1.DailyRsiService
 */
export declare const DailyRsiService: GenService<{
  /**
   * Gets daily relative strength index data
   *
   * @generated from rpc systemathics.apis.services.daily_analytics.v1.DailyRsiService.DailyRsi
   */
  dailyRsi: {
    methodKind: "unary";
    input: typeof DailyRsiRequestSchema;
    output: typeof DailyRsiResponseSchema;
  },
}>;

