// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Moving averages smooth the price movements by filtering out the "noise" caused by short-term price fluctuations. 
// <br>They also form the building blocks for a wide range of technical indicators. Computing moving averages over a defined number of time periods is useful to:
// <br>- identify the trend direction
// <br>- determine support and resistance levels
// <br>CMA is the average of all the data points.

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/daily_analytics/v1/daily_cma.proto (package systemathics.apis.services.daily_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Date } from "../../../../../google/type/date_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/daily_analytics/v1/daily_cma.proto.
 */
export const file_systemathics_apis_services_daily_analytics_v1_daily_cma: GenFile = /*@__PURE__*/
  fileDesc("Cj1zeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseV9hbmFseXRpY3MvdjEvZGFpbHlfY21hLnByb3RvEi1zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEirgEKD0RhaWx5Q21hUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchJFCg1kYXRlX2ludGVydmFsGAIgASgLMi4uc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuRGF0ZUludGVydmFsEhIKCmFkanVzdG1lbnQYAyABKAgiXQoQRGFpbHlDbWFSZXNwb25zZRJJCgRkYXRhGAEgAygLMjsuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHlfYW5hbHl0aWNzLnYxLkRhaWx5Q21hRGF0YSJPCgxEYWlseUNtYURhdGESHwoEZGF0ZRgBIAEoCzIRLmdvb2dsZS50eXBlLkRhdGUSDQoFdmFsdWUYAiABKAESDwoHYXZlcmFnZRgDIAEoATLAAQoPRGFpbHlDbWFTZXJ2aWNlEqwBCghEYWlseUNtYRI+LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5X2FuYWx5dGljcy52MS5EYWlseUNtYVJlcXVlc3QaPy5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEuRGFpbHlDbWFSZXNwb25zZSIfgtPkkwIZEhcvdjEvZGFpbHktYW5hbHl0aWNzL2NtYWIGcHJvdG8z", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * The required input to request the DailyCmaService.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyCmaRequest
 */
export type DailyCmaRequest = Message<"systemathics.apis.services.daily_analytics.v1.DailyCmaRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The corporate action adjustment (dividends).
   * By default the value is set to false : the split is applied in all cases
   *
   * @generated from field: bool adjustment = 3;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyCmaRequest.
 * Use `create(DailyCmaRequestSchema)` to create a new message.
 */
export const DailyCmaRequestSchema: GenMessage<DailyCmaRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_cma, 0);

/**
 * Represents a daily cumulative moving average response.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyCmaResponse
 */
export type DailyCmaResponse = Message<"systemathics.apis.services.daily_analytics.v1.DailyCmaResponse"> & {
  /**
   * The daily cumulative moving averages: an array of DailyCmaData objects
   *
   * @generated from field: repeated systemathics.apis.services.daily_analytics.v1.DailyCmaData data = 1;
   */
  data: DailyCmaData[];
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyCmaResponse.
 * Use `create(DailyCmaResponseSchema)` to create a new message.
 */
export const DailyCmaResponseSchema: GenMessage<DailyCmaResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_cma, 1);

/**
 * Contains the daily cumulative moving average data: date and value.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyCmaData
 */
export type DailyCmaData = Message<"systemathics.apis.services.daily_analytics.v1.DailyCmaData"> & {
  /**
   * Date of the cumulative moving average
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * The data used to calculate the average of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * The cumulative moving average value of the day for all the data points
   *
   * @generated from field: double average = 3;
   */
  average: number;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyCmaData.
 * Use `create(DailyCmaDataSchema)` to create a new message.
 */
export const DailyCmaDataSchema: GenMessage<DailyCmaData> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_cma, 2);

/**
 * Called to request daily cumulative moving average data. 
 *
 * @generated from service systemathics.apis.services.daily_analytics.v1.DailyCmaService
 */
export const DailyCmaService: GenService<{
  /**
   * Gets daily cumulative moving average data
   *
   * @generated from rpc systemathics.apis.services.daily_analytics.v1.DailyCmaService.DailyCma
   */
  dailyCma: {
    methodKind: "unary";
    input: typeof DailyCmaRequestSchema;
    output: typeof DailyCmaResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_analytics_v1_daily_cma, 0);

