// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Bollinger bands were created by John Bollinger, they are envelopes and plotted around the moving average. 
// <br> The width of the bands is based on the standard deviaton of the closing prices from a moving average as follows:
// <br><i>- Middle band = n-period moving average</i>
// <br><i>- Upper band = Middle band + (k * n-period standard deviation)</i>
// <br><i>- Lower band = Middle band - (k * n-period standard deviation)</i>
// <br><i> Where n is the number of periods and k is factor to apply to the standard deviation value, k=2 as default value.</i>

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/daily_analytics/v1/daily_bollinger.proto (package systemathics.apis.services.daily_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { Date } from "../../../../../google/type/date_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/daily_analytics/v1/daily_bollinger.proto.
 */
export const file_systemathics_apis_services_daily_analytics_v1_daily_bollinger: GenFile = /*@__PURE__*/
  fileDesc("CkNzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseV9hbmFseXRpY3MvdjEvZGFpbHlfYm9sbGluZ2VyLnByb3RvEi1zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEi1wEKFURhaWx5Qm9sbGluZ2VyUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchJFCg1kYXRlX2ludGVydmFsGAIgASgLMi4uc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuRGF0ZUludGVydmFsEg4KBmxlbmd0aBgDIAEoBRIRCglkZXZpYXRpb24YBCABKAESEgoKYWRqdXN0bWVudBgFIAEoCCJpChZEYWlseUJvbGxpbmdlclJlc3BvbnNlEk8KBGRhdGEYASADKAsyQS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEuRGFpbHlCb2xsaW5nZXJEYXRhIswBChJEYWlseUJvbGxpbmdlckRhdGESHwoEZGF0ZRgBIAEoCzIRLmdvb2dsZS50eXBlLkRhdGUSDQoFdmFsdWUYAiABKAESKwoFbG93ZXIYAyABKAsyHC5nb29nbGUucHJvdG9idWYuRG91YmxlVmFsdWUSKwoFdXBwZXIYBCABKAsyHC5nb29nbGUucHJvdG9idWYuRG91YmxlVmFsdWUSLAoGbWlkZGxlGAUgASgLMhwuZ29vZ2xlLnByb3RvYnVmLkRvdWJsZVZhbHVlMt4BChVEYWlseUJvbGxpbmdlclNlcnZpY2USxAEKDkRhaWx5Qm9sbGluZ2VyEkQuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHlfYW5hbHl0aWNzLnYxLkRhaWx5Qm9sbGluZ2VyUmVxdWVzdBpFLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5X2FuYWx5dGljcy52MS5EYWlseUJvbGxpbmdlclJlc3BvbnNlIiWC0+STAh8SHS92MS9kYWlseS1hbmFseXRpY3MvYm9sbGluZ2VyYgZwcm90bzM", [file_google_api_annotations, file_google_protobuf_wrappers, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * The required input to request the DailyBollingerService.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyBollingerRequest
 */
export type DailyBollingerRequest = Message<"systemathics.apis.services.daily_analytics.v1.DailyBollingerRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;

  /**
   * [Mandatory] The simple moving average window length (period: data points number)
   *
   * @generated from field: int32 length = 3;
   */
  length: number;

  /**
   * [Mandatory] The standard deviation window length
   *
   * @generated from field: double deviation = 4;
   */
  deviation: number;

  /**
   * [Optional] The corporate action adjustment (dividends).
   * By default the value is set to false : the split is applied in all cases
   *
   * @generated from field: bool adjustment = 5;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyBollingerRequest.
 * Use `create(DailyBollingerRequestSchema)` to create a new message.
 */
export const DailyBollingerRequestSchema: GenMessage<DailyBollingerRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_bollinger, 0);

/**
 * The daily bars response contains an array of Bollinger bands.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyBollingerResponse
 */
export type DailyBollingerResponse = Message<"systemathics.apis.services.daily_analytics.v1.DailyBollingerResponse"> & {
  /**
   * The daily Bollinger bands: an array of DailyBollingerData objects
   *
   * @generated from field: repeated systemathics.apis.services.daily_analytics.v1.DailyBollingerData data = 1;
   */
  data: DailyBollingerData[];
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyBollingerResponse.
 * Use `create(DailyBollingerResponseSchema)` to create a new message.
 */
export const DailyBollingerResponseSchema: GenMessage<DailyBollingerResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_bollinger, 1);

/**
 * Contains the daily Bollinger bands data: date, lower, middle and upper.
 *
 * @generated from message systemathics.apis.services.daily_analytics.v1.DailyBollingerData
 */
export type DailyBollingerData = Message<"systemathics.apis.services.daily_analytics.v1.DailyBollingerData"> & {
  /**
   * Date of Bollinger bands
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * The data used to calculate the Bollinger bands of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * Bollinger lower band value of the day
   * <br><i>Lower band = Middle band - (k * n-period standard deviation)</i>
   *
   * @generated from field: google.protobuf.DoubleValue lower = 3;
   */
  lower?: number;

  /**
   * Bollinger upper band value of the day
   * <br><i>Upper band = Middle band + (k * n-period standard deviation)</i>
   *
   * @generated from field: google.protobuf.DoubleValue upper = 4;
   */
  upper?: number;

  /**
   * Bollinger middle band value of the day
   * <br><i>Middle band = n-period moving average</i>
   *
   * @generated from field: google.protobuf.DoubleValue middle = 5;
   */
  middle?: number;
};

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyBollingerData.
 * Use `create(DailyBollingerDataSchema)` to create a new message.
 */
export const DailyBollingerDataSchema: GenMessage<DailyBollingerData> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_bollinger, 2);

/**
 * Called to request daily Bollinger bands data. 
 *
 * @generated from service systemathics.apis.services.daily_analytics.v1.DailyBollingerService
 */
export const DailyBollingerService: GenService<{
  /**
   * Gets daily Bollinger bands data
   *
   * @generated from rpc systemathics.apis.services.daily_analytics.v1.DailyBollingerService.DailyBollinger
   */
  dailyBollinger: {
    methodKind: "unary";
    input: typeof DailyBollingerRequestSchema;
    output: typeof DailyBollingerResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_analytics_v1_daily_bollinger, 0);

