// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// SMA is formed by computing the average price of a security over a specific number of points. 
// <br>As its name implies, simple moving average is an average that moves. Old data is dropped and new data becomes available, causing the average to move along the time.
// <br><i>N-points SMA data point</i> is computed by adding up the last N period's trade prices and then dividing by N as follows: $$ SMA = \frac{\Sigma Close_n}{N} $$
// <br>Where:
// <br>- <i>Close n</i> is the close price of the <i>period n</i>
// <br>- <i>N</i> is the count of time periods

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily_analytics/v1/daily_sma.proto (package systemathics.apis.services.daily_analytics.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";

/**
 * Describes the file systemathics/apis/services/daily_analytics/v1/daily_sma.proto.
 */
export const file_systemathics_apis_services_daily_analytics_v1_daily_sma = /*@__PURE__*/
  fileDesc("Cj1zeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseV9hbmFseXRpY3MvdjEvZGFpbHlfc21hLnByb3RvEi1zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEivgEKD0RhaWx5U21hUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchJFCg1kYXRlX2ludGVydmFsGAIgASgLMi4uc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuRGF0ZUludGVydmFsEg4KBmxlbmd0aBgDIAEoBRISCgphZGp1c3RtZW50GAQgASgIIl0KEERhaWx5U21hUmVzcG9uc2USSQoEZGF0YRgBIAMoCzI7LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5X2FuYWx5dGljcy52MS5EYWlseVNtYURhdGEibQoMRGFpbHlTbWFEYXRhEh8KBGRhdGUYASABKAsyES5nb29nbGUudHlwZS5EYXRlEg0KBXZhbHVlGAIgASgBEi0KB2F2ZXJhZ2UYAyABKAsyHC5nb29nbGUucHJvdG9idWYuRG91YmxlVmFsdWUywAEKD0RhaWx5U21hU2VydmljZRKsAQoIRGFpbHlTbWESPi5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEuRGFpbHlTbWFSZXF1ZXN0Gj8uc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuZGFpbHlfYW5hbHl0aWNzLnYxLkRhaWx5U21hUmVzcG9uc2UiH4LT5JMCGRIXL3YxL2RhaWx5LWFuYWx5dGljcy9zbWFiBnByb3RvMw", [file_google_api_annotations, file_google_protobuf_wrappers, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailySmaRequest.
 * Use `create(DailySmaRequestSchema)` to create a new message.
 */
export const DailySmaRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_sma, 0);

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailySmaResponse.
 * Use `create(DailySmaResponseSchema)` to create a new message.
 */
export const DailySmaResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_sma, 1);

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailySmaData.
 * Use `create(DailySmaDataSchema)` to create a new message.
 */
export const DailySmaDataSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_sma, 2);

/**
 * Called to request daily simple moving average data. 
 *
 * @generated from service systemathics.apis.services.daily_analytics.v1.DailySmaService
 */
export const DailySmaService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_analytics_v1_daily_sma, 0);

