// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The Relative Strength Index</i>, developed by J. Welles Wilder measures the speed and change of price movements.
// <br>RSI oscillates between zero and 100. Traditionally the RSI is considered <i>overbought</i> when above 70 and <i>oversold</i> when below 30.
// <br><br>RSI is computed as follows: $$ RSI = 100 - \frac{100}{1 + RS} $$ Where:
// <br>- <i>RS = AvgU/AvgD</i> is the <i>relative strength
// <br>- <i>AvgU</i> average of last <i>N close prices</i> up moves
// <br>- <i>AvgD</i> average of last <i>N close prices</i> down moves
// <br>- <i>N</i> is the period of the RSI

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/daily_analytics/v1/daily_rsi.proto (package systemathics.apis.services.daily_analytics.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";

/**
 * Describes the file systemathics/apis/services/daily_analytics/v1/daily_rsi.proto.
 */
export const file_systemathics_apis_services_daily_analytics_v1_daily_rsi = /*@__PURE__*/
  fileDesc("Cj1zeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9kYWlseV9hbmFseXRpY3MvdjEvZGFpbHlfcnNpLnByb3RvEi1zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEivgEKD0RhaWx5UnNpUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchJFCg1kYXRlX2ludGVydmFsGAIgASgLMi4uc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuRGF0ZUludGVydmFsEg4KBmxlbmd0aBgDIAEoBRISCgphZGp1c3RtZW50GAQgASgIIl0KEERhaWx5UnNpUmVzcG9uc2USSQoEZGF0YRgBIAMoCzI7LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5X2FuYWx5dGljcy52MS5EYWlseVJzaURhdGEiSwoMRGFpbHlSc2lEYXRhEh8KBGRhdGUYASABKAsyES5nb29nbGUudHlwZS5EYXRlEg0KBXZhbHVlGAIgASgBEgsKA3JzaRgDIAEoATLAAQoPRGFpbHlSc2lTZXJ2aWNlEqwBCghEYWlseVJzaRI+LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmRhaWx5X2FuYWx5dGljcy52MS5EYWlseVJzaVJlcXVlc3QaPy5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5kYWlseV9hbmFseXRpY3MudjEuRGFpbHlSc2lSZXNwb25zZSIfgtPkkwIZEhcvdjEvZGFpbHktYW5hbHl0aWNzL3JzaWIGcHJvdG8z", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyRsiRequest.
 * Use `create(DailyRsiRequestSchema)` to create a new message.
 */
export const DailyRsiRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_rsi, 0);

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyRsiResponse.
 * Use `create(DailyRsiResponseSchema)` to create a new message.
 */
export const DailyRsiResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_rsi, 1);

/**
 * Describes the message systemathics.apis.services.daily_analytics.v1.DailyRsiData.
 * Use `create(DailyRsiDataSchema)` to create a new message.
 */
export const DailyRsiDataSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_daily_analytics_v1_daily_rsi, 2);

/**
 * Called to request daily relative strength index data. 
 *
 * @generated from service systemathics.apis.services.daily_analytics.v1.DailyRsiService
 */
export const DailyRsiService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_daily_analytics_v1_daily_rsi, 0);

