// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// The sector and industry classification decoder.
// <br>Available classifications :
// <br>- ICB : Industry Classification Benchmark is a comprehensive and rules based, transparent classification methodology based on research and market trends designed to support investment solutions. It was launched in 2005 and enhanced in 2019 with the integration of the Russell Global Sectors (RGS) classification scheme and additional structural enhancements.
// <br>- SIC : The Standard Industrial Classification is a system for classifying industries by a four-digit code. Established in the United States in 1937, it is used by government agencies to classify industry areas. The SIC system is also used by agencies in other countries, e.g., by the United Kingdom's Companies House.
// <br>- TRBC : The Refinitiv Business Classification is an industry classification of global companies. It was developed by the Reuters Group under the name Reuters Business Sector Scheme (RBSS), was rebranded to Thomson Reuters Business Classification (TRBC) when the Thomson Corporation acquired the Reuters Group in 2008, forming Thomson Reuters, and was rebranded again, to The Refinitiv Business Classification (TRBC), in 2020. Since the creation of Refinitiv in October 2018, TRBC has been owned and operated by Refinitiv and is the basis for Refinitiv Indices.
// <br>- GICS : In 1999, MSCI and S&P Dow Jones Indices developed the Global Industry Classification Standard, seeking to offer an efficient investment tool to capture the breadth, depth and evolution of industry sectors.GICS is a four-tiered, hierarchical industry classification system. Companies are classified quantitatively and qualitatively. Each company is assigned a single GICS classification at the Sub-Industry level according to its principal business activity. MSCI and S&P Dow Jones Indices use revenues as a key factor in determining a firm s principal business activity. Earnings and market perception, however, are also recognized as important and relevant information for classification purposes, and are taken into account during the annual review process.

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/static_data/v1/sector.proto (package systemathics.apis.services.static_data.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/static_data/v1/sector.proto.
 */
export const file_systemathics_apis_services_static_data_v1_sector: GenFile = /*@__PURE__*/
  fileDesc("CjZzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9zdGF0aWNfZGF0YS92MS9zZWN0b3IucHJvdG8SKXN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxIksKDVNlY3RvclJlcXVlc3QSEAoIcHJvdmlkZXIYASABKAkSDgoEY29kZRgCIAEoCUgAEg8KBWxldmVsGAMgASgFSABCBwoFdmFsdWUiegoOU2VjdG9yUmVzcG9uc2USRAoEZGF0YRgBIAMoCzI2LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLlNlY3RvckxldmVsEhMKC2Rlc2NyaXB0aW9uGAIgASgJEg0KBWNvdW50GAMgASgFIlsKC1NlY3RvckxldmVsEgwKBG5hbWUYASABKAkSDQoFaW5kZXgYAiABKAUSDAoEY29kZRgDIAEoCRISCgpkZWZpbml0aW9uGAQgASgJEg0KBWxhYmVsGAUgASgJMq4BCg1TZWN0b3JTZXJ2aWNlEpwBCgZTZWN0b3ISOC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zdGF0aWNfZGF0YS52MS5TZWN0b3JSZXF1ZXN0Gjkuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc3RhdGljX2RhdGEudjEuU2VjdG9yUmVzcG9uc2UiHYLT5JMCFxIVL3YxL3N0YXRpY2RhdGEvc2VjdG9yYgZwcm90bzM", [file_google_api_annotations]);

/**
 * The required inputs to request the SectorService.
 *
 * @generated from message systemathics.apis.services.static_data.v1.SectorRequest
 */
export type SectorRequest = Message<"systemathics.apis.services.static_data.v1.SectorRequest"> & {
  /**
   * [Mandatory] The classification provider or taxonomy
   * <br>Available classifications : ICB, SIC, TRBC and GICS
   *
   * @generated from field: string provider = 1;
   */
  provider: string;

  /**
   * @generated from oneof systemathics.apis.services.static_data.v1.SectorRequest.value
   */
  value: {
    /**
     * [Mandatory] The classification code
     *
     * @generated from field: string code = 2;
     */
    value: string;
    case: "code";
  } | {
    /**
     * [Mandatory] The classification level (strating from 0 : the top structure or group)
     *
     * @generated from field: int32 level = 3;
     */
    value: number;
    case: "level";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.SectorRequest.
 * Use `create(SectorRequestSchema)` to create a new message.
 */
export const SectorRequestSchema: GenMessage<SectorRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_sector, 0);

/**
 * Represents a sector classifcation response.
 *
 * @generated from message systemathics.apis.services.static_data.v1.SectorResponse
 */
export type SectorResponse = Message<"systemathics.apis.services.static_data.v1.SectorResponse"> & {
  /**
   * The sector classification levels: an array of Level objects
   *
   * @generated from field: repeated systemathics.apis.services.static_data.v1.SectorLevel data = 1;
   */
  data: SectorLevel[];

  /**
   * The classification description
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * The classification levels count
   *
   * @generated from field: int32 count = 3;
   */
  count: number;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.SectorResponse.
 * Use `create(SectorResponseSchema)` to create a new message.
 */
export const SectorResponseSchema: GenMessage<SectorResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_sector, 1);

/**
 * Contains the sector classification structure at a specified level.
 *
 * @generated from message systemathics.apis.services.static_data.v1.SectorLevel
 */
export type SectorLevel = Message<"systemathics.apis.services.static_data.v1.SectorLevel"> & {
  /**
   * The sector classification level's name
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The sector classification level's index (order of the strcture)
   *
   * @generated from field: int32 index = 2;
   */
  index: number;

  /**
   * The sector classification level's code
   *
   * @generated from field: string code = 3;
   */
  code: string;

  /**
   * The sector classification level's definition
   *
   * @generated from field: string definition = 4;
   */
  definition: string;

  /**
   * The sector classification level's label
   *
   * @generated from field: string label = 5;
   */
  label: string;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.SectorLevel.
 * Use `create(SectorLevelSchema)` to create a new message.
 */
export const SectorLevelSchema: GenMessage<SectorLevel> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_sector, 2);

/**
 * Called to request sector and industry classification data.
 *
 * @generated from service systemathics.apis.services.static_data.v1.SectorService
 */
export const SectorService: GenService<{
  /**
   * Gets static sector and industry data
   *
   * @generated from rpc systemathics.apis.services.static_data.v1.SectorService.Sector
   */
  sector: {
    methodKind: "unary";
    input: typeof SectorRequestSchema;
    output: typeof SectorResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_static_data_v1_sector, 0);

