// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Reference data encompasses a wide range of specification data about:
// <br>- financial instrument such as asset class, symbol, maturity, etc.
// <br>- counterparties such as issuer information.
// <br>- pricing such as open, high low and close prices.
// <br>- The challenge with reference data is that it tends to be sourced from multiple sources: internal, counterparties and providers.
// <br>- Reference data dedicated service is a result of various data sources and fields sourcing, validation, cross-checking and normalization.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/static_data/v1/set_static_data.proto (package systemathics.apis.services.set_static_data.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AssetType, AssetTypeRequestSchema } from "../../../type/shared/v1/asset_pb";
import type { Date } from "../../../../../google/type/date_pb";
import type { CdsIndexEntry } from "./static_data_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file systemathics/apis/services/static_data/v1/set_static_data.proto.
 */
export declare const file_systemathics_apis_services_static_data_v1_set_static_data: GenFile;

/**
 * @generated from message systemathics.apis.services.set_static_data.v1.AssetIdRequest
 */
export declare type AssetIdRequest = Message<"systemathics.apis.services.set_static_data.v1.AssetIdRequest"> & {
  /**
   * [Mandatory] The Id of the static data.
   *
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * [Mandatory] The asset type of the static data.
   *
   * @generated from field: systemathics.apis.type.shared.v1.AssetType asset_type = 2;
   */
  assetType: AssetType;
};

/**
 * Describes the message systemathics.apis.services.set_static_data.v1.AssetIdRequest.
 * Use `create(AssetIdRequestSchema)` to create a new message.
 */
export declare const AssetIdRequestSchema: GenMessage<AssetIdRequest>;

/**
 * @generated from message systemathics.apis.services.set_static_data.v1.CreateAssetRequest
 */
export declare type CreateAssetRequest = Message<"systemathics.apis.services.set_static_data.v1.CreateAssetRequest"> & {
  /**
   * Validity Date
   *
   * @generated from field: google.type.Date validity = 1;
   */
  validity?: Date;

  /**
   * @generated from oneof systemathics.apis.services.set_static_data.v1.CreateAssetRequest.asset
   */
  asset: {
    /**
     * @generated from field: systemathics.apis.services.static_data.v1.CdsIndexEntry cds_index = 2;
     */
    value: CdsIndexEntry;
    case: "cdsIndex";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.services.set_static_data.v1.CreateAssetRequest.
 * Use `create(CreateAssetRequestSchema)` to create a new message.
 */
export declare const CreateAssetRequestSchema: GenMessage<CreateAssetRequest>;

/**
 * @generated from message systemathics.apis.services.set_static_data.v1.Asset
 */
export declare type Asset = Message<"systemathics.apis.services.set_static_data.v1.Asset"> & {
  /**
   * Id
   *
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * Validity Date
   *
   * @generated from field: google.type.Date validity = 2;
   */
  validity?: Date;

  /**
   * @generated from oneof systemathics.apis.services.set_static_data.v1.Asset.asset
   */
  asset: {
    /**
     * @generated from field: systemathics.apis.services.static_data.v1.CdsIndexEntry cds_index = 3;
     */
    value: CdsIndexEntry;
    case: "cdsIndex";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.services.set_static_data.v1.Asset.
 * Use `create(AssetSchema)` to create a new message.
 */
export declare const AssetSchema: GenMessage<Asset>;

/**
 * Called to set static data.
 *
 * @generated from service systemathics.apis.services.set_static_data.v1.SetStaticDataService
 */
export declare const SetStaticDataService: GenService<{
  /**
   * Create Cds Index Option Static data 
   *
   * @generated from rpc systemathics.apis.services.set_static_data.v1.SetStaticDataService.Create
   */
  create: {
    methodKind: "unary";
    input: typeof CreateAssetRequestSchema;
    output: typeof AssetSchema;
  },
  /**
   * Get Cds Index Option Static data by Id
   *
   * @generated from rpc systemathics.apis.services.set_static_data.v1.SetStaticDataService.GetOne
   */
  getOne: {
    methodKind: "unary";
    input: typeof AssetIdRequestSchema;
    output: typeof AssetSchema;
  },
  /**
   * Get all Cds Index Option Static data
   *
   * @generated from rpc systemathics.apis.services.set_static_data.v1.SetStaticDataService.GetAll
   */
  getAll: {
    methodKind: "server_streaming";
    input: typeof AssetTypeRequestSchema;
    output: typeof AssetSchema;
  },
  /**
   * Update an Asset by Id
   *
   * @generated from rpc systemathics.apis.services.set_static_data.v1.SetStaticDataService.Update
   */
  update: {
    methodKind: "unary";
    input: typeof AssetSchema;
    output: typeof AssetSchema;
  },
  /**
   * Get Option Static data from OTC Streaming by Id
   *
   * @generated from rpc systemathics.apis.services.set_static_data.v1.SetStaticDataService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof AssetIdRequestSchema;
    output: typeof EmptySchema;
  },
}>;

