// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Reference data encompasses a wide range of specification data about:
// <br>- financial instrument such as asset class, symbol, maturity, etc.
// <br>- counterparties such as issuer information.
// <br>- pricing such as open, high low and close prices.
// <br>- The challenge with reference data is that it tends to be sourced from multiple sources: internal, counterparties and providers.
// <br>- Reference data dedicated service is a result of various data sources and fields sourcing, validation, cross-checking and normalization.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/static_data/v1/set_static_data.proto (package systemathics.apis.services.set_static_data.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_type_datetime } from "../../../../../google/type/datetime_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import { file_google_protobuf_empty, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import { file_systemathics_apis_services_static_data_v1_static_data } from "./static_data_pb";
import { file_systemathics_apis_type_shared_v1_asset } from "../../../type/shared/v1/asset_pb";

/**
 * Describes the file systemathics/apis/services/static_data/v1/set_static_data.proto.
 */
export const file_systemathics_apis_services_static_data_v1_set_static_data = /*@__PURE__*/
  fileDesc("Cj9zeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9zdGF0aWNfZGF0YS92MS9zZXRfc3RhdGljX2RhdGEucHJvdG8SLXN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnNldF9zdGF0aWNfZGF0YS52MSJdCg5Bc3NldElkUmVxdWVzdBIKCgJpZBgBIAEoAxI/Cgphc3NldF90eXBlGAIgASgOMisuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuQXNzZXRUeXBlIpEBChJDcmVhdGVBc3NldFJlcXVlc3QSIwoIdmFsaWRpdHkYASABKAsyES5nb29nbGUudHlwZS5EYXRlEk0KCWNkc19pbmRleBgCIAEoCzI4LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLkNkc0luZGV4RW50cnlIAEIHCgVhc3NldCKQAQoFQXNzZXQSCgoCaWQYASABKAMSIwoIdmFsaWRpdHkYAiABKAsyES5nb29nbGUudHlwZS5EYXRlEk0KCWNkc19pbmRleBgDIAEoCzI4LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLkNkc0luZGV4RW50cnlIAEIHCgVhc3NldDKZBgoUU2V0U3RhdGljRGF0YVNlcnZpY2USoQEKBkNyZWF0ZRJBLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnNldF9zdGF0aWNfZGF0YS52MS5DcmVhdGVBc3NldFJlcXVlc3QaNC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zZXRfc3RhdGljX2RhdGEudjEuQXNzZXQiHoLT5JMCGCIWL3YxL3N0YXRpY2RhdGEve2Fzc2V0fRKiAQoGR2V0T25lEj0uc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc2V0X3N0YXRpY19kYXRhLnYxLkFzc2V0SWRSZXF1ZXN0GjQuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc2V0X3N0YXRpY19kYXRhLnYxLkFzc2V0IiOC0+STAh0SGy92MS9zdGF0aWNkYXRhL3thc3NldH0ve2lkfRKUAQoGR2V0QWxsEjIuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuQXNzZXRUeXBlUmVxdWVzdBo0LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnNldF9zdGF0aWNfZGF0YS52MS5Bc3NldCIegtPkkwIYEhYvdjEvc3RhdGljZGF0YS97YXNzZXR9MAESmQEKBlVwZGF0ZRI0LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnNldF9zdGF0aWNfZGF0YS52MS5Bc3NldBo0LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnNldF9zdGF0aWNfZGF0YS52MS5Bc3NldCIjgtPkkwIdGhsvdjEvc3RhdGljZGF0YS97YXNzZXR9L3tpZH0ShAEKBkRlbGV0ZRI9LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnNldF9zdGF0aWNfZGF0YS52MS5Bc3NldElkUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIjgtPkkwIdKhsvdjEvc3RhdGljZGF0YS97YXNzZXR9L3tpZH1iBnByb3RvMw", [file_google_api_annotations, file_google_type_datetime, file_google_type_date, file_google_protobuf_empty, file_google_protobuf_wrappers, file_systemathics_apis_services_static_data_v1_static_data, file_systemathics_apis_type_shared_v1_asset]);

/**
 * Describes the message systemathics.apis.services.set_static_data.v1.AssetIdRequest.
 * Use `create(AssetIdRequestSchema)` to create a new message.
 */
export const AssetIdRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_set_static_data, 0);

/**
 * Describes the message systemathics.apis.services.set_static_data.v1.CreateAssetRequest.
 * Use `create(CreateAssetRequestSchema)` to create a new message.
 */
export const CreateAssetRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_set_static_data, 1);

/**
 * Describes the message systemathics.apis.services.set_static_data.v1.Asset.
 * Use `create(AssetSchema)` to create a new message.
 */
export const AssetSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_set_static_data, 2);

/**
 * Called to set static data.
 *
 * @generated from service systemathics.apis.services.set_static_data.v1.SetStaticDataService
 */
export const SetStaticDataService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_static_data_v1_set_static_data, 0);

