// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Reference data encompasses a wide range of specification data about:
// <br>- financial instrument such as asset class, symbol, maturity, etc.
// <br>- counterparties such as issuer information.
// <br>- pricing such as open, high low and close prices.
// <br>- The challenge with reference data is that it tends to be sourced from multiple sources: internal, counterparties and providers.
// <br>- Reference data dedicated service is a result of various data sources and fields sourcing, validation, cross-checking and normalization.

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/static_data/v1/static_data.proto (package systemathics.apis.services.static_data.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Date } from "../../../../../google/type/date_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import type { TimeOfDay } from "../../../../../google/type/timeofday_pb";
import { file_google_type_timeofday } from "../../../../../google/type/timeofday_pb";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { AssetType } from "../../../type/shared/v1/asset_pb";
import { file_systemathics_apis_type_shared_v1_asset } from "../../../type/shared/v1/asset_pb";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/static_data/v1/static_data.proto.
 */
export const file_systemathics_apis_services_static_data_v1_static_data: GenFile = /*@__PURE__*/
  fileDesc("CjtzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9zdGF0aWNfZGF0YS92MS9zdGF0aWNfZGF0YS5wcm90bxIpc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc3RhdGljX2RhdGEudjEi1goKF1N0YXRpY0RhdGFTZWFyY2hSZXF1ZXN0Ej8KCmFzc2V0X3R5cGUYASABKA4yKy5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5Bc3NldFR5cGUSDQoFc3RhcnQYAiABKAUSDQoFY291bnQYAyABKAUSLAoGdGlja2VyGAQgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEi4KCGV4Y2hhbmdlGAUgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEioKBmFjdGl2ZRgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5Cb29sVmFsdWUSLQoHcHJpbWFyeRgHIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIvCglvcGVyYXRpbmcYCCABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSKgoEbmFtZRgJIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIuCghjdXJyZW5jeRgKIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRItCgdjb3VudHJ5GAsgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEi8KCWJsb29tYmVyZxgMIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRItCgdyZXV0ZXJzGA0gASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEjEKC21vcm5pbmdzdGFyGA4gASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEiwKBm1hcmtpdBgPIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIqCgRmaWdpGBAgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEjQKDmNvbXBvc2l0ZV9maWdpGBEgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEjEKC3NoYXJlZF9maWdpGBIgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEioKBGlzaW4YEyABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSKwoFc2Vkb2wYFCABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSLgoIY29udHJhY3QYFSABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSKwoFY3VzaXAYFiABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSMQoLZGVzY3JpcHRpb24YFyABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSLAoGc2VjdG9yGBggASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEjAKCnVuZGVybHlpbmcYGSABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSSwoIbWF0dXJpdHkYGiABKAsyOS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zdGF0aWNfZGF0YS52MS5TdGF0aWNEYXRhRGF0ZRJQCg5jYXBpdGFsaXphdGlvbhgbIAEoCzI4LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLlN0YXRpY0RhdGFJbnQSKQoDY2lrGBwgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlIo4BCg5TdGF0aWNEYXRhRGF0ZRIiCgVleGFjdBgBIAEoCzIRLmdvb2dsZS50eXBlLkRhdGVIABJPCgVyYW5nZRgCIAEoCzI+LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLlN0YXRpY0RhdGFEYXRlUmFuZ2VIAEIHCgVvbmVvZiJtChNTdGF0aWNEYXRhRGF0ZVJhbmdlEiQKCWxlc3NfdGhhbhgBIAEoCzIRLmdvb2dsZS50eXBlLkRhdGUSMAoVZ3JlYXRlcl9vcl9lcXVhbF90aGFuGAIgASgLMhEuZ29vZ2xlLnR5cGUuRGF0ZSJ/ChBTdGF0aWNEYXRhRG91YmxlEg8KBWV4YWN0GAEgASgBSAASUQoFcmFuZ2UYAiABKAsyQC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zdGF0aWNfZGF0YS52MS5TdGF0aWNEYXRhRG91YmxlUmFuZ2VIAEIHCgVvbmVvZiKFAQoVU3RhdGljRGF0YURvdWJsZVJhbmdlEi8KCWxlc3NfdGhhbhgBIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5Eb3VibGVWYWx1ZRI7ChVncmVhdGVyX29yX2VxdWFsX3RoYW4YAiABKAsyHC5nb29nbGUucHJvdG9idWYuRG91YmxlVmFsdWUieQoNU3RhdGljRGF0YUludBIPCgVleGFjdBgBIAEoA0gAEk4KBXJhbmdlGAIgASgLMj0uc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc3RhdGljX2RhdGEudjEuU3RhdGljRGF0YUludFJhbmdlSABCBwoFb25lb2YigAEKElN0YXRpY0RhdGFJbnRSYW5nZRIuCglsZXNzX3RoYW4YASABKAsyGy5nb29nbGUucHJvdG9idWYuSW50NjRWYWx1ZRI6ChVncmVhdGVyX29yX2VxdWFsX3RoYW4YAiABKAsyGy5nb29nbGUucHJvdG9idWYuSW50NjRWYWx1ZSL1AQoSU3RhdGljRGF0YVJlc3BvbnNlEkkKBmZ1dHVyZRgBIAEoCzI5LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLkZ1dHVyZVJlc3BvbnNlEkkKBmVxdWl0eRgCIAEoCzI5LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLkVxdWl0eVJlc3BvbnNlEkkKBmNyeXB0bxgDIAEoCzI5LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLkNyeXB0b1Jlc3BvbnNlIm0KDkNyeXB0b1Jlc3BvbnNlEkYKBmFzc2V0cxgBIAMoCzI2LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLkNyeXB0b0VudHJ5EhMKC3RvdGFsX2NvdW50GAIgASgDIm0KDkVxdWl0eVJlc3BvbnNlEkYKBmFzc2V0cxgBIAMoCzI2LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLkVxdWl0eUVudHJ5EhMKC3RvdGFsX2NvdW50GAIgASgDIm0KDkZ1dHVyZVJlc3BvbnNlEkYKBmFzc2V0cxgBIAMoCzI2LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN0YXRpY19kYXRhLnYxLkZ1dHVyZUVudHJ5EhMKC3RvdGFsX2NvdW50GAIgASgDIr4ICgtFcXVpdHlFbnRyeRJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchIfCgRkYXRlGAIgASgLMhEuZ29vZ2xlLnR5cGUuRGF0ZRIMCgR0eXBlGAMgASgJEg4KBmFjdGl2ZRgEIAEoCBIPCgdwcmltYXJ5GAUgASgJEhEKCW9wZXJhdGluZxgGIAEoCRIMCgRuYW1lGAcgASgJEhAKCGN1cnJlbmN5GAggASgJEg8KB2NvdW50cnkYCSABKAkSSwoOdGlja19zaXplX3J1bGUYCiADKAsyMy5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zdGF0aWNfZGF0YS52MS5UaWNrU2l6ZRINCgVpbmRleBgLIAMoCRIQCghjYWxlbmRhchgMIAEoCRITCgtkZXNjcmlwdGlvbhgNIAEoCRIkCgRvcGVuGA4gASgLMhYuZ29vZ2xlLnR5cGUuVGltZU9mRGF5EiUKBWNsb3NlGA8gASgLMhYuZ29vZ2xlLnR5cGUuVGltZU9mRGF5EhEKCXRpbWVfem9uZRgQIAEoCRIQCghsb3Rfc2l6ZRgRIAEoAxITCgtwb2ludF92YWx1ZRgSIAEoARINCgVwcmljZRgTIAEoARIOCgZ2b2x1bWUYFCABKAMSDwoHc291cmNlcxgVIAEoBRJUCgdtYXBwaW5nGBYgAygLMkMuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc3RhdGljX2RhdGEudjEuRXF1aXR5RW50cnkuTWFwcGluZ0VudHJ5EhEKCWJsb29tYmVyZxgXIAEoCRIPCgdyZXV0ZXJzGBggASgJEhQKDG1vcm5pbmdfc3RhchgZIAEoCRIOCgZtYXJraXQYGiABKAkSDAoEZmlnaRgbIAEoCRIWCg5jb21wb3NpdGVfZmlnaRgcIAEoCRIMCgRpc2luGB0gASgJEg0KBWN1c2lwGB4gASgJEg0KBXNlZG9sGB8gASgJEhYKDmNsYXNzaWZpY2F0aW9uGCAgASgJEgsKA2NpaxghIAEoCRJUCgdzZWN0b3JzGCIgAygLMkMuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc3RhdGljX2RhdGEudjEuRXF1aXR5RW50cnkuU2VjdG9yc0VudHJ5EhYKDmNhcGl0YWxpemF0aW9uGCMgASgDEg8KB2FkZHJlc3MYJCABKAkSDQoFcGhvbmUYJSABKAkSDQoFZW1haWwYJiABKAkSCwoDdXJsGCcgASgJGi4KDE1hcHBpbmdFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBGi4KDFNlY3RvcnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBItcICgtGdXR1cmVFbnRyeRJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchIfCgRkYXRlGAIgASgLMhEuZ29vZ2xlLnR5cGUuRGF0ZRIMCgR0eXBlGAMgASgJEg4KBmFjdGl2ZRgEIAEoCBIPCgdwcmltYXJ5GAUgASgJEhEKCW9wZXJhdGluZxgGIAEoCRIMCgRuYW1lGAcgASgJEhAKCGN1cnJlbmN5GAggASgJEg8KB2NvdW50cnkYCSABKAkSSwoOdGlja19zaXplX3J1bGUYCiADKAsyMy5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zdGF0aWNfZGF0YS52MS5UaWNrU2l6ZRINCgVpbmRleBgLIAMoCRIQCghjYWxlbmRhchgMIAEoCRITCgtkZXNjcmlwdGlvbhgNIAEoCRIkCgRvcGVuGA4gASgLMhYuZ29vZ2xlLnR5cGUuVGltZU9mRGF5EiUKBWNsb3NlGA8gASgLMhYuZ29vZ2xlLnR5cGUuVGltZU9mRGF5EhEKCXRpbWVfem9uZRgQIAEoCRIQCghsb3Rfc2l6ZRgRIAEoAxITCgtwb2ludF92YWx1ZRgSIAEoARINCgVwcmljZRgTIAEoARIOCgZ2b2x1bWUYFCABKAMSDwoHc291cmNlcxgVIAEoBRJUCgdtYXBwaW5nGBYgAygLMkMuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc3RhdGljX2RhdGEudjEuRnV0dXJlRW50cnkuTWFwcGluZ0VudHJ5EhEKCWJsb29tYmVyZxgXIAEoCRIPCgdyZXV0ZXJzGBggASgJEhQKDG1vcm5pbmdfc3RhchgZIAEoCRIOCgZtYXJraXQYGiABKAkSDAoEZmlnaRgbIAEoCRIWCg5jb21wb3NpdGVfZmlnaRgcIAEoCRIMCgRpc2luGB0gASgJEg0KBWN1c2lwGB4gASgJEg0KBXNlZG9sGB8gASgJEhYKDmNsYXNzaWZpY2F0aW9uGCAgASgJEhIKCnVuZGVybHlpbmcYISABKAkSEAoIY29udHJhY3QYIiABKAkSVgoIY2F0ZWdvcnkYIyADKAsyRC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zdGF0aWNfZGF0YS52MS5GdXR1cmVFbnRyeS5DYXRlZ29yeUVudHJ5Eg0KBWNoYWluGCQgASgJEiMKCG1hdHVyaXR5GCUgASgLMhEuZ29vZ2xlLnR5cGUuRGF0ZRINCgVtb250aBgmIAEoCRIMCgR5ZWFyGCcgASgFGi4KDE1hcHBpbmdFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBGi8KDUNhdGVnb3J5RW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASKMCAoLQ3J5cHRvRW50cnkSQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISHwoEZGF0ZRgCIAEoCzIRLmdvb2dsZS50eXBlLkRhdGUSDAoEdHlwZRgDIAEoCRIOCgZhY3RpdmUYBCABKAgSDwoHcHJpbWFyeRgFIAEoCRIRCglvcGVyYXRpbmcYBiABKAkSDAoEbmFtZRgHIAEoCRIVCg1iYXNlX2N1cnJlbmN5GAggASgJEg8KB2NvdW50cnkYCSABKAkSSwoOdGlja19zaXplX3J1bGUYCiADKAsyMy5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zdGF0aWNfZGF0YS52MS5UaWNrU2l6ZRINCgVpbmRleBgLIAMoCRIQCghjYWxlbmRhchgMIAEoCRITCgtkZXNjcmlwdGlvbhgNIAEoCRIkCgRvcGVuGA4gASgLMhYuZ29vZ2xlLnR5cGUuVGltZU9mRGF5EiUKBWNsb3NlGA8gASgLMhYuZ29vZ2xlLnR5cGUuVGltZU9mRGF5EhEKCXRpbWVfem9uZRgQIAEoCRIQCghsb3Rfc2l6ZRgRIAEoAxITCgtwb2ludF92YWx1ZRgSIAEoARINCgVwcmljZRgTIAEoARIOCgZ2b2x1bWUYFCABKAMSDwoHc291cmNlcxgVIAEoBRJUCgdtYXBwaW5nGBYgAygLMkMuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc3RhdGljX2RhdGEudjEuQ3J5cHRvRW50cnkuTWFwcGluZ0VudHJ5EhEKCWJsb29tYmVyZxgXIAEoCRIPCgdyZXV0ZXJzGBggASgJEhQKDG1vcm5pbmdfc3RhchgZIAEoCRIOCgZtYXJraXQYGiABKAkSDAoEZmlnaRgbIAEoCRIWCg5jb21wb3NpdGVfZmlnaRgcIAEoCRIMCgRpc2luGB0gASgJEg0KBWN1c2lwGB4gASgJEg0KBXNlZG9sGB8gASgJEhYKDmNsYXNzaWZpY2F0aW9uGCAgASgJEhYKDnF1b3RlX2N1cnJlbmN5GCEgASgJEhEKCWNvbnNlbnN1cxgiIAMoCRIlCgppc3N1ZV9kYXRlGCMgASgLMhEuZ29vZ2xlLnR5cGUuRGF0ZRIWCg5jYXBpdGFsaXphdGlvbhgkIAEoAxIaChJjaXJjdWxhdGluZ19zdXBwbHkYJSABKAMSEgoKbWF4X3N1cHBseRgmIAEoAxIUCgx0b3RhbF9zdXBwbHkYJyABKAMaLgoMTWFwcGluZ0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEibQoVU3RhdGljRGF0YUlkZW50aWZpZXJzElQKC2lkZW50aWZpZXJzGAEgAygLMj8uc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc3RhdGljX2RhdGEudjEuU3RhdGljRGF0YUlkZW50aWZpZXIieQoUU3RhdGljRGF0YUlkZW50aWZpZXISQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISHwoEZGF0ZRgCIAEoCzIRLmdvb2dsZS50eXBlLkRhdGUiJwoIVGlja1NpemUSDQoFcHJpY2UYASABKAESDAoEdGljaxgCIAEoASqGAgoNRnJlcXVlbmN5VHlwZRIeChpGUkVRVUVOQ1lfVFlQRV9VTlNQRUNJRklFRBAAEhcKE0ZSRVFVRU5DWV9UWVBFX05PTkUQARIWChJGUkVRVUVOQ1lfVFlQRV9EQVkQAhIXChNGUkVRVUVOQ1lfVFlQRV9XRUVLEAMSGAoURlJFUVVFTkNZX1RZUEVfTU9OVEgQBBIaChZGUkVRVUVOQ1lfVFlQRV9RVUFSVEVSEAUSHQoZRlJFUVVFTkNZX1RZUEVfU0VNSUFOTlVBTBAGEhkKFUZSRVFVRU5DWV9UWVBFX0FOTlVBTBAHEhsKF0ZSRVFVRU5DWV9UWVBFX0JJQU5OVUFMEAgqgQEKDEV4ZXJjaXNlVHlwZRIdChlFWEVSQ0lTRV9UWVBFX1VOU1BFQ0lGSUVEEAASGgoWRVhFUkNJU0VfVFlQRV9BTUVSSUNBThABEhoKFkVYRVJDSVNFX1RZUEVfRVVST1BFQU4QAhIaChZFWEVSQ0lTRV9UWVBFX0JFUk1VREFOEAMq7QEKD0NvdXBvbkZyZXF1ZW5jeRIgChxDT1VQT05fRlJFUVVFTkNZX1VOU1BFQ0lGSUVEEAASGwoXQ09VUE9OX0ZSRVFVRU5DWV9BTk5VQUwQARIgChxDT1VQT05fRlJFUVVFTkNZX1NFTUlfQU5OVUFMEAISHQoZQ09VUE9OX0ZSRVFVRU5DWV9RVUFURVJMWRAEEh8KG0NPVVBPTl9GUkVRVUVOQ1lfQklfTU9OVEhMWRAGEhwKGENPVVBPTl9GUkVRVUVOQ1lfTU9OVEhMWRAMEhsKF0NPVVBPTl9GUkVRVUVOQ1lfV0VFS0xZEDQq4RAKCERheUNvdW50EhkKFURBWV9DT1VOVF9VTlNQRUNJRklFRBAAEhUKEURBWV9DT1VOVF9BQ1RfQUNUEAESFQoRREFZX0NPVU5UX0FDVF8zNjAQAhIVChFEQVlfQ09VTlRfQUNUXzM2NRADEhQKEERBWV9DT1VOVF8zMF9BQ1QQBBIUChBEQVlfQ09VTlRfMzBfMzYwEAUSFAoQREFZX0NPVU5UXzMwXzM2NRAGEhQKEERBWV9DT1VOVF9OTF9BQ1QQBxIUChBEQVlfQ09VTlRfTkxfMzYwEAgSFAoQREFZX0NPVU5UX05MXzM2NRAJEh0KGURBWV9DT1VOVF9BQ1RfQUNUX05PTl9FT00QChIdChlEQVlfQ09VTlRfQUNUXzM2MF9OT05fRU9NEAsSHQoZREFZX0NPVU5UX0FDVF8zNjVfTk9OX0VPTRAMEhwKGERBWV9DT1VOVF8zMF9BQ1RfTk9OX0VPTRANEhwKGERBWV9DT1VOVF8zMF8zNjBfTk9OX0VPTRAOEhwKGERBWV9DT1VOVF8zMF8zNjVfTk9OX0VPTRAPEhwKGERBWV9DT1VOVF9OTF9BQ1RfTk9OX0VPTRAQEhwKGERBWV9DT1VOVF9OTF8zNjBfTk9OX0VPTRAREhwKGERBWV9DT1VOVF9OTF8zNjVfTk9OX0VPTRASEhkKFURBWV9DT1VOVF9JU01BXzMwX0FDVBATEhkKFURBWV9DT1VOVF9JU01BXzMwXzM2MBAUEhkKFURBWV9DT1VOVF9JU01BXzMwXzM2NRAVEiAKHERBWV9DT1VOVF9JU01BMzBfQUNUX05PTl9FT00QFhIgChxEQVlfQ09VTlRfSVNNQV8zMF8zNjBfTk9ORU9NEBcSIAocREFZX0NPVU5UX0lTTUEzMF8zNjVfTk9OX0VPTRAYEhUKEURBWV9DT1VOVF9BQ1RfMzY0EBsSGAoUREFZX0NPVU5UX0FDVF8zNjVfNjYQHBIcChhEQVlfQ09VTlRfVVNfTVVOSV8zMF8zNjAQHRIdChlEQVlfQ09VTlRfQUNUXzM2NF9OT05fRU9NEB4SIAocREFZX0NPVU5UX01VTkkzMF8zNjBfTk9OX0VPTRAgEhoKFkRBWV9DT1VOVF9CVVNfREFZU18yNTIQIRIbChdEQVlfQ09VTlRfR0VSTUFOXzMwXzM2MBAjEiAKHERBWV9DT1VOVF9CVVNfREFZXzI1Mk5PTl9FT00QJBIgChxEQVlfQ09VTlRfQUNUXzM2NV82Nl9OT05fRU9NECUSIAocREFZX0NPVU5UX0dFUl8zMF8zNjBfTk9OX0VPTRAmEhwKGERBWV9DT1VOVF9VU19XSVRfQUNUX0FDVBAoEhwKGERBWV9DT1VOVF9VU19XSUJfQUNUXzM2MBApEh8KG0RBWV9DT1VOVF9JU0RBX1NXQVBTXzMwXzM2MBAsEh8KG0RBWV9DT1VOVF9JU0RBX1NXQVBTXzMwXzM2NRAtEiAKHERBWV9DT1VOVF9JU0RBMzBfMzYwX05PTl9FT00QLxIgChxEQVlfQ09VTlRfSVNEQTMwXzM2NV9OT05fRU9NEDASIAocREFZX0NPVU5UX0lTREEzMF9BQ1RfTk9OX0VPTRAxEhoKFkRBWV9DT1VOVF9JU0RBXzMwRV8zNjAQMhIaChZEQVlfQ09VTlRfSVNEQV8zMEVfMzY1EDMSGgoWREFZX0NPVU5UX0lTREFfMzBFX0FDVBA0EiAKHERBWV9DT1VOVF9JU0RBXzMwRV8zNjBfTl9FT00QNRIgChxEQVlfQ09VTlRfSVNEQV8zMEVfMzY1X05fRU9NEDYSGgoWREFZX0NPVU5UX0lTREFfQUNUX0FDVBA6EiAKHERBWV9DT1VOVF9JU0RBX0FDVF9BQ1RfTl9FT00QPRIUChBEQVlfQ09VTlRfMjhfMzYwED4SFAoQREFZX0NPVU5UX0JEXzI1MhBjEhkKFURBWV9DT1VOVF9BQ1RfQUNUXzEwMRBlEhkKFURBWV9DT1VOVF9BQ1RfMzYwXzEwMhBmEhkKFURBWV9DT1VOVF9BQ1RfMzY1XzEwMxBnEhgKFERBWV9DT1VOVF8zMF8zNjBfMTA0EGgSHQoZREFZX0NPVU5UX0FDVF9BQ1RfTk9NXzEwNRBpEh0KGURBWV9DT1VOVF9BQ1RfMzYwX05PTV8xMDYQahIdChlEQVlfQ09VTlRfQUNUXzM2NV9OT01fMTA3EGsSHgoZREFZX0NPVU5UX0lTTUFfMzBfMzYwXzEzMRCDARIfChpEQVlfQ09VTlRfSVNEQV9BQ1RfQUNUXzIwMRDJARIeChlEQVlfQ09VTlRfQUZCX0FDVF9BQ1RfMjAyEMoBEiMKHkRBWV9DT1VOVF9JU0RBX0FDVF9BQ1RfTk9NXzIwMxDLARIiCh1EQVlfQ09VTlRfQUZCX0FDVF9BQ1RfTk9NXzIwNBDMARIgChtEQVlfQ09VTlRfSVNNQV9BQ1RfQUNUX18yMDYQzgESIwoeREFZX0NPVU5UX0lTTUFfQUNUX0FDVF9OT01fMjA3EM8BEhsKFkRBWV9DT1VOVF9CVVNJTkVTU18yNTIQ/AESFgoRREFZX0NPVU5UXzMwRV8zNjAQ3gcSFgoRREFZX0NPVU5UXzMwRV8zNjUQ3wcSFgoRREFZX0NPVU5UXzMwRV9BQ1QQ4AcSFgoRREFZX0NPVU5UXzMwR18zNjAQ4QcSFgoRREFZX0NPVU5UXzMwMV8zNjAQ4gcSFgoRREFZX0NPVU5UXzMwMV8zNjUQ4wcSFgoRREFZX0NPVU5UXzMwSV9BQ1QQ5AcSFgoRREFZX0NPVU5UXzMwTV8zNjAQ5QcqYgoMU3dhcHRpb25UeXBlEh0KGVNXQVBUSU9OX1RZUEVfVU5TUEVDSUZJRUQQABIXChNTV0FQVElPTl9UWVBFX1BBWUVSEAESGgoWU1dBUFRJT05fVFlQRV9SRUNFSVZFUhACMvMCChFTdGF0aWNEYXRhU2VydmljZRKjAQoGU2VhcmNoEkIuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc3RhdGljX2RhdGEudjEuU3RhdGljRGF0YVNlYXJjaFJlcXVlc3QaPS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zdGF0aWNfZGF0YS52MS5TdGF0aWNEYXRhUmVzcG9uc2UiFoLT5JMCEBIOL3YxL3N0YXRpY2RhdGEStwEKEEdldEJ5SWRlbnRpZmllcnMSQC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zdGF0aWNfZGF0YS52MS5TdGF0aWNEYXRhSWRlbnRpZmllcnMaPS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5zdGF0aWNfZGF0YS52MS5TdGF0aWNEYXRhUmVzcG9uc2UiIoLT5JMCHBIaL3YxL3N0YXRpY2RhdGEvaWRlbnRpZmllcnNiBnByb3RvMw", [file_google_api_annotations, file_google_type_date, file_google_type_timeofday, file_google_protobuf_wrappers, file_systemathics_apis_type_shared_v1_asset, file_systemathics_apis_type_shared_v1_identifier]);

/**
 * The required input to request the StaticDataService.
 *
 * @generated from message systemathics.apis.services.static_data.v1.StaticDataSearchRequest
 */
export type StaticDataSearchRequest = Message<"systemathics.apis.services.static_data.v1.StaticDataSearchRequest"> & {
  /**
   * [Optional] Asset Type
   *
   * @generated from field: systemathics.apis.type.shared.v1.AssetType asset_type = 1;
   */
  assetType: AssetType;

  /**
   * [Optional] Define the first element index to be retrieved
   *
   * @generated from field: int32 start = 2;
   */
  start: number;

  /**
   * [Optional] Select the first elements retrieved, by default count is set to 500, and the max count value is set to 500
   *
   * @generated from field: int32 count = 3;
   */
  count: number;

  /**
   * [Optional] Ticker
   *
   * @generated from field: google.protobuf.StringValue ticker = 4;
   */
  ticker?: string;

  /**
   * [Optional] Exchange
   *
   * @generated from field: google.protobuf.StringValue exchange = 5;
   */
  exchange?: string;

  /**
   * [Optional] Active
   *
   * @generated from field: google.protobuf.BoolValue active = 6;
   */
  active?: boolean;

  /**
   * [Optional] Primary
   *
   * @generated from field: google.protobuf.StringValue primary = 7;
   */
  primary?: string;

  /**
   * [Optional] Operating
   *
   * @generated from field: google.protobuf.StringValue operating = 8;
   */
  operating?: string;

  /**
   * [Optional] Name
   *
   * @generated from field: google.protobuf.StringValue name = 9;
   */
  name?: string;

  /**
   * [Optional] Currency
   *
   * @generated from field: google.protobuf.StringValue currency = 10;
   */
  currency?: string;

  /**
   * [Optional] Country
   *
   * @generated from field: google.protobuf.StringValue country = 11;
   */
  country?: string;

  /**
   * [Optional] Bloomberg
   *
   * @generated from field: google.protobuf.StringValue bloomberg = 12;
   */
  bloomberg?: string;

  /**
   * [Optional] Reuters
   *
   * @generated from field: google.protobuf.StringValue reuters = 13;
   */
  reuters?: string;

  /**
   * [Optional] Morningstar
   *
   * @generated from field: google.protobuf.StringValue morningstar = 14;
   */
  morningstar?: string;

  /**
   * [Optional] Markit
   *
   * @generated from field: google.protobuf.StringValue markit = 15;
   */
  markit?: string;

  /**
   * [Optional] Figi - Exchange Level
   *
   * @generated from field: google.protobuf.StringValue figi = 16;
   */
  figi?: string;

  /**
   * [Optional] Composite Figi - Country Level
   *
   * @generated from field: google.protobuf.StringValue composite_figi = 17;
   */
  compositeFigi?: string;

  /**
   * [Optional] Shared Figi - Global Level
   *
   * @generated from field: google.protobuf.StringValue shared_figi = 18;
   */
  sharedFigi?: string;

  /**
   * [Optional] Isin
   *
   * @generated from field: google.protobuf.StringValue isin = 19;
   */
  isin?: string;

  /**
   * [Optional] Sedol
   *
   * @generated from field: google.protobuf.StringValue sedol = 20;
   */
  sedol?: string;

  /**
   * [Optional] Contract
   *
   * @generated from field: google.protobuf.StringValue contract = 21;
   */
  contract?: string;

  /**
   * [Optional] Cusip
   *
   * @generated from field: google.protobuf.StringValue cusip = 22;
   */
  cusip?: string;

  /**
   * [Optional] Description
   *
   * @generated from field: google.protobuf.StringValue description = 23;
   */
  description?: string;

  /**
   * [Optional] Sector
   *
   * @generated from field: google.protobuf.StringValue sector = 24;
   */
  sector?: string;

  /**
   * [Optional] Underlying
   *
   * @generated from field: google.protobuf.StringValue underlying = 25;
   */
  underlying?: string;

  /**
   * [Optional] Maturity for future.
   *
   * @generated from field: systemathics.apis.services.static_data.v1.StaticDataDate maturity = 26;
   */
  maturity?: StaticDataDate;

  /**
   * [Optional] Capitalization for equity
   *
   * @generated from field: systemathics.apis.services.static_data.v1.StaticDataInt capitalization = 27;
   */
  capitalization?: StaticDataInt;

  /**
   * [Optional] Cik
   *
   * @generated from field: google.protobuf.StringValue cik = 28;
   */
  cik?: string;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.StaticDataSearchRequest.
 * Use `create(StaticDataSearchRequestSchema)` to create a new message.
 */
export const StaticDataSearchRequestSchema: GenMessage<StaticDataSearchRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 0);

/**
 * @generated from message systemathics.apis.services.static_data.v1.StaticDataDate
 */
export type StaticDataDate = Message<"systemathics.apis.services.static_data.v1.StaticDataDate"> & {
  /**
   * @generated from oneof systemathics.apis.services.static_data.v1.StaticDataDate.oneof
   */
  oneof: {
    /**
     * @generated from field: google.type.Date exact = 1;
     */
    value: Date;
    case: "exact";
  } | {
    /**
     * @generated from field: systemathics.apis.services.static_data.v1.StaticDataDateRange range = 2;
     */
    value: StaticDataDateRange;
    case: "range";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.StaticDataDate.
 * Use `create(StaticDataDateSchema)` to create a new message.
 */
export const StaticDataDateSchema: GenMessage<StaticDataDate> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 1);

/**
 * Used to specify a date range search
 *
 * @generated from message systemathics.apis.services.static_data.v1.StaticDataDateRange
 */
export type StaticDataDateRange = Message<"systemathics.apis.services.static_data.v1.StaticDataDateRange"> & {
  /**
   * The upper bound date (excluded)
   *
   * @generated from field: google.type.Date less_than = 1;
   */
  lessThan?: Date;

  /**
   * The lower bound date (included)
   *
   * @generated from field: google.type.Date greater_or_equal_than = 2;
   */
  greaterOrEqualThan?: Date;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.StaticDataDateRange.
 * Use `create(StaticDataDateRangeSchema)` to create a new message.
 */
export const StaticDataDateRangeSchema: GenMessage<StaticDataDateRange> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 2);

/**
 * @generated from message systemathics.apis.services.static_data.v1.StaticDataDouble
 */
export type StaticDataDouble = Message<"systemathics.apis.services.static_data.v1.StaticDataDouble"> & {
  /**
   * @generated from oneof systemathics.apis.services.static_data.v1.StaticDataDouble.oneof
   */
  oneof: {
    /**
     * @generated from field: double exact = 1;
     */
    value: number;
    case: "exact";
  } | {
    /**
     * @generated from field: systemathics.apis.services.static_data.v1.StaticDataDoubleRange range = 2;
     */
    value: StaticDataDoubleRange;
    case: "range";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.StaticDataDouble.
 * Use `create(StaticDataDoubleSchema)` to create a new message.
 */
export const StaticDataDoubleSchema: GenMessage<StaticDataDouble> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 3);

/**
 * Used to specify either a specific double od a date range
 *
 * @generated from message systemathics.apis.services.static_data.v1.StaticDataDoubleRange
 */
export type StaticDataDoubleRange = Message<"systemathics.apis.services.static_data.v1.StaticDataDoubleRange"> & {
  /**
   * The upper bound value (excluded)
   *
   * @generated from field: google.protobuf.DoubleValue less_than = 1;
   */
  lessThan?: number;

  /**
   * The lower bound value (included)
   *
   * @generated from field: google.protobuf.DoubleValue greater_or_equal_than = 2;
   */
  greaterOrEqualThan?: number;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.StaticDataDoubleRange.
 * Use `create(StaticDataDoubleRangeSchema)` to create a new message.
 */
export const StaticDataDoubleRangeSchema: GenMessage<StaticDataDoubleRange> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 4);

/**
 * @generated from message systemathics.apis.services.static_data.v1.StaticDataInt
 */
export type StaticDataInt = Message<"systemathics.apis.services.static_data.v1.StaticDataInt"> & {
  /**
   * @generated from oneof systemathics.apis.services.static_data.v1.StaticDataInt.oneof
   */
  oneof: {
    /**
     * @generated from field: int64 exact = 1;
     */
    value: bigint;
    case: "exact";
  } | {
    /**
     * @generated from field: systemathics.apis.services.static_data.v1.StaticDataIntRange range = 2;
     */
    value: StaticDataIntRange;
    case: "range";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.StaticDataInt.
 * Use `create(StaticDataIntSchema)` to create a new message.
 */
export const StaticDataIntSchema: GenMessage<StaticDataInt> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 5);

/**
 * Used to specify either a specific date od a date range
 *
 * @generated from message systemathics.apis.services.static_data.v1.StaticDataIntRange
 */
export type StaticDataIntRange = Message<"systemathics.apis.services.static_data.v1.StaticDataIntRange"> & {
  /**
   * The upper bound value (excluded)
   *
   * @generated from field: google.protobuf.Int64Value less_than = 1;
   */
  lessThan?: bigint;

  /**
   * The lower bound value (included)
   *
   * @generated from field: google.protobuf.Int64Value greater_or_equal_than = 2;
   */
  greaterOrEqualThan?: bigint;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.StaticDataIntRange.
 * Use `create(StaticDataIntRangeSchema)` to create a new message.
 */
export const StaticDataIntRangeSchema: GenMessage<StaticDataIntRange> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 6);

/**
 * Represents a reference data response grouped by asset type.
 *
 * @generated from message systemathics.apis.services.static_data.v1.StaticDataResponse
 */
export type StaticDataResponse = Message<"systemathics.apis.services.static_data.v1.StaticDataResponse"> & {
  /**
   * The reference data for futures: the future array
   *
   * @generated from field: systemathics.apis.services.static_data.v1.FutureResponse future = 1;
   */
  future?: FutureResponse;

  /**
   * The reference data for equities: the equity array
   *
   * @generated from field: systemathics.apis.services.static_data.v1.EquityResponse equity = 2;
   */
  equity?: EquityResponse;

  /**
   * The reference data for crypto / crypto currencies: the crypto array
   *
   * @generated from field: systemathics.apis.services.static_data.v1.CryptoResponse crypto = 3;
   */
  crypto?: CryptoResponse;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.StaticDataResponse.
 * Use `create(StaticDataResponseSchema)` to create a new message.
 */
export const StaticDataResponseSchema: GenMessage<StaticDataResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 7);

/**
 * Contain data about Crypto
 *
 * @generated from message systemathics.apis.services.static_data.v1.CryptoResponse
 */
export type CryptoResponse = Message<"systemathics.apis.services.static_data.v1.CryptoResponse"> & {
  /**
   * The reference data for cryptos: the cryptos array
   *
   * @generated from field: repeated systemathics.apis.services.static_data.v1.CryptoEntry assets = 1;
   */
  assets: CryptoEntry[];

  /**
   * The total count of cryptos entry available
   *
   * @generated from field: int64 total_count = 2;
   */
  totalCount: bigint;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.CryptoResponse.
 * Use `create(CryptoResponseSchema)` to create a new message.
 */
export const CryptoResponseSchema: GenMessage<CryptoResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 8);

/**
 * Contain data about equities
 *
 * @generated from message systemathics.apis.services.static_data.v1.EquityResponse
 */
export type EquityResponse = Message<"systemathics.apis.services.static_data.v1.EquityResponse"> & {
  /**
   * The reference data for equities: the equities array
   *
   * @generated from field: repeated systemathics.apis.services.static_data.v1.EquityEntry assets = 1;
   */
  assets: EquityEntry[];

  /**
   * The total count of equities entry available
   *
   * @generated from field: int64 total_count = 2;
   */
  totalCount: bigint;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.EquityResponse.
 * Use `create(EquityResponseSchema)` to create a new message.
 */
export const EquityResponseSchema: GenMessage<EquityResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 9);

/**
 * Contain data about futures
 *
 * @generated from message systemathics.apis.services.static_data.v1.FutureResponse
 */
export type FutureResponse = Message<"systemathics.apis.services.static_data.v1.FutureResponse"> & {
  /**
   * The reference data for futures: the futures array
   *
   * @generated from field: repeated systemathics.apis.services.static_data.v1.FutureEntry assets = 1;
   */
  assets: FutureEntry[];

  /**
   * The total count of futures entry available
   *
   * @generated from field: int64 total_count = 2;
   */
  totalCount: bigint;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.FutureResponse.
 * Use `create(FutureResponseSchema)` to create a new message.
 */
export const FutureResponseSchema: GenMessage<FutureResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 10);

/**
 * Contains the reference data for equities.	
 *
 * @generated from message systemathics.apis.services.static_data.v1.EquityEntry
 */
export type EquityEntry = Message<"systemathics.apis.services.static_data.v1.EquityEntry"> & {
  /**
   * Identifiers: The instrument identifier. It consists of a ticker and an exchange code. (ISO 10383)
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * Date of the data.
   *
   * @generated from field: google.type.Date date = 2;
   */
  date?: Date;

  /**
   * General information: The instrument class.
   *
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * General information: Indicates if the financial instrument is currently active.
   *
   * @generated from field: bool active = 4;
   */
  active: boolean;

  /**
   * General information: The Market Identifier Code (MIC) of the assigned primary exchange on which this specific instrument is traded. (ISO 10383)
   *
   * @generated from field: string primary = 5;
   */
  primary: string;

  /**
   * General information: The entity operating an exchange/market/trade reporting facility in a specific market/country (ISO 10383).
   *
   * @generated from field: string operating = 6;
   */
  operating: string;

  /**
   * General information: Name of the company or brief description of the instrument. The name of an instrument may change in conjunction with corporate actions.
   *
   * @generated from field: string name = 7;
   */
  name: string;

  /**
   * General information: Currency in which the instrument was issued. (ISO 4217)
   *
   * @generated from field: string currency = 8;
   */
  currency: string;

  /**
   * General information: Specifies the  country or territory code of where the instrument trades. (ISO 3166)
   *
   * @generated from field: string country = 9;
   */
  country: string;

  /**
   * General information: The minimum amount by which the price of the instrument can change.  Data is represented as a table where there are different tick sizes for different price ranges.
   *
   * @generated from field: repeated systemathics.apis.services.static_data.v1.TickSize tick_size_rule = 10;
   */
  tickSizeRule: TickSize[];

  /**
   * General information: The different indices to which this instrument belongs The output is presented as a collection Ticker-Exchange identifying indices.
   *
   * @generated from field: repeated string index = 11;
   */
  index: string[];

  /**
   * General information: The Market Identifier Code (MIC) to use in order to retrieve the calendar for that instrument.
   *
   * @generated from field: string calendar = 12;
   */
  calendar: string;

  /**
   * General information: A brief description of the instrument.
   *
   * @generated from field: string description = 13;
   */
  description: string;

  /**
   * Trading hours: Hours the exchange opens for continuous trading, reported in the time zone of the exchange.
   *
   * @generated from field: google.type.TimeOfDay open = 14;
   */
  open?: TimeOfDay;

  /**
   * Trading hours: Hours the exchange closes for continuous  trading, reported in the time zone of the exchange.
   *
   * @generated from field: google.type.TimeOfDay close = 15;
   */
  close?: TimeOfDay;

  /**
   * Trading hours: The time zone.
   *
   * @generated from field: string time_zone = 16;
   */
  timeZone: string;

  /**
   * Specifications: Specifies the minimum number of shares that can be purchased, as regulated by an exchange.
   *
   * @generated from field: int64 lot_size = 17;
   */
  lotSize: bigint;

  /**
   * Specifications: The amount value of one point basis on a price.
   *
   * @generated from field: double point_value = 18;
   */
  pointValue: number;

  /**
   * Reference data: Reference price for the instrument.
   *
   * @generated from field: double price = 19;
   */
  price: number;

  /**
   * Reference data: Reference volume for the instrument.
   *
   * @generated from field: int64 volume = 20;
   */
  volume: bigint;

  /**
   * Mapping: List of sources contributing to the instrument fields description.
   *
   * @generated from field: int32 sources = 21;
   */
  sources: number;

  /**
   * Mapping: The different codes used to identify the instrument represented in a single string. The output is presented as a collection of pairs of mapping name (ISIN, RIC, SEDOL, FIGI, etc) with its code.
   *
   * @generated from field: map<string, string> mapping = 22;
   */
  mapping: { [key: string]: string };

  /**
   * Mapping: The bloomberg ticker.
   *
   * @generated from field: string bloomberg = 23;
   */
  bloomberg: string;

  /**
   * Mapping: The Reuters Instrument Code (RIC) is a ticker-like code used to identify financial instruments and indices. The RIC is made up primarily of the security's ticker symbol, optionally followed by a period and exchange code based on the name of the stock exchange using that ticker.
   *
   * @generated from field: string reuters = 24;
   */
  reuters: string;

  /**
   * Mapping: The Morningstar ticker used to identify an instrument.
   *
   * @generated from field: string morning_star = 25;
   */
  morningStar: string;

  /**
   * Mapping: The Markit code, also known as RED Code.
   *
   * @generated from field: string markit = 26;
   */
  markit: string;

  /**
   * Mapping: The Financial Instrument Global Identifier (FIGI) is an established global standard of the Object Management Group (www.OMG.org, an international non-profit technology standards consortium founded in 1989) and an identification standard adopted by the American National Committee X9. The FIGI standard is issued and distributed by Bloomberg L.P. as a Registration Authority and Certified Provider under the auspice of OMG. The Financial Instrument Global Identifier (FIGI) is a twelve character, alphanumeric identifier. The first 2 characters are upper-case consonants (including "Y"), the third character is the upper-case "G", characters 4 -11 are any upper-case consonant (including "Y") or integer between 0 and 9, and the last character is a check-digit.
   *
   * @generated from field: string figi = 27;
   */
  figi: string;

  /**
   * Mapping: The Composite Financial Instrument Global Identifier (FIGI) enables users to link multiple FIGIs at the Trading Venue-level within the same country or market in order to obtain an aggregated view for that instrument.
   *
   * @generated from field: string composite_figi = 28;
   */
  compositeFigi: string;

  /**
   * Mapping: The International Securities Identification Number (ISIN) is a twelve-character number assigned by the local national numbering agency. It consists of a two-letter country code, followed by the nine character alphanumerical national security identifier, and a check digit.
   *
   * @generated from field: string isin = 29;
   */
  isin: string;

  /**
   * Mapping: The Committee on Uniform Security Identification Procedures (CUSIP) number is aSecurity identification number for the U.S. and Canada.  It consists of nine alpha-numeric characters. The first six characters identify the issuer, the following two identify the issue, and the final character is a check digit.
   *
   * @generated from field: string cusip = 30;
   */
  cusip: string;

  /**
   * Mapping: The Stock Exchange Daily Official List number (SEDOL) identifier. Numbers issued prior to March 8, 2004 consist of 7 digits.  SEDOLs issued after this date consist of 7 alphanumeric characters, where the first character is always a letter.
   *
   * @generated from field: string sedol = 31;
   */
  sedol: string;

  /**
   * Mapping: The Classification of Financial Instruments (CFI), is a six-letter-code used in the financial services industry to classify and describe the structure and function of a financial instrument. (ISO 10962)
   *
   * @generated from field: string classification = 32;
   */
  classification: string;

  /**
   * Specific values for the equity: The Central Index Key (CIK) number is a unique number assigned to an individual, company, filing agent or foreign government by the United States Securities and Exchange Commission.  The numbers are up to ten digits in length and are permanent identifiers that may not be changed
   *
   * @generated from field: string cik = 33;
   */
  cik: string;

  /**
   * Specific values for the equity:  sectors definitions: The market sector assigned to the instrument in the commonly used market sector classification.  The output is presented as a collection of pairs of classification description (BICS, SIC, GICS, TRBC, etc) with its code.
   *
   * @generated from field: map<string, string> sectors = 34;
   */
  sectors: { [key: string]: string };

  /**
   * Specific values for the equity:  market capitalization:
   *
   * @generated from field: int64 capitalization = 35;
   */
  capitalization: bigint;

  /**
   * Specific values for the equity: Company address associated with the company's domicile which is determined by the location of senior management.
   *
   * @generated from field: string address = 36;
   */
  address: string;

  /**
   * Specific values for the equity: The issuer's phone number at corporate headquarters.
   *
   * @generated from field: string phone = 37;
   */
  phone: string;

  /**
   * Specific values for the equity: The main email of the company.
   *
   * @generated from field: string email = 38;
   */
  email: string;

  /**
   * Specific values for the equity: The website link of the company.
   *
   * @generated from field: string url = 39;
   */
  url: string;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.EquityEntry.
 * Use `create(EquityEntrySchema)` to create a new message.
 */
export const EquityEntrySchema: GenMessage<EquityEntry> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 11);

/**
 * Contains the reference data for futures.
 *
 * @generated from message systemathics.apis.services.static_data.v1.FutureEntry
 */
export type FutureEntry = Message<"systemathics.apis.services.static_data.v1.FutureEntry"> & {
  /**
   * Identifiers: The instrument identifier. It consists of a ticker and an exchange code. (ISO 10383)
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * Date of the data.
   *
   * @generated from field: google.type.Date date = 2;
   */
  date?: Date;

  /**
   * General information: The instrument class.
   *
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * General information: Indicates if the financial instrument is currently active.
   *
   * @generated from field: bool active = 4;
   */
  active: boolean;

  /**
   * General information: The Market Identifier Code (MIC) of the assigned primary exchange on which this specific instrument is traded. (ISO 10383)
   *
   * @generated from field: string primary = 5;
   */
  primary: string;

  /**
   * General information: The entity operating an exchange/market/trade reporting facility in a specific market/country (ISO 10383).
   *
   * @generated from field: string operating = 6;
   */
  operating: string;

  /**
   * General information: Name of the company or brief description of the instrument. The name of an instrument may change in conjunction with corporate actions.
   *
   * @generated from field: string name = 7;
   */
  name: string;

  /**
   * General information: Currency in which the instrument was issued. (ISO 4217)
   *
   * @generated from field: string currency = 8;
   */
  currency: string;

  /**
   * General information: Specifies the  country or territory code of where the instrument trades. (ISO 3166)
   *
   * @generated from field: string country = 9;
   */
  country: string;

  /**
   * General information: The minimum amount by which the price of the instrument can change.  Data is represented as a table where there are different tick sizes for different price ranges.
   *
   * @generated from field: repeated systemathics.apis.services.static_data.v1.TickSize tick_size_rule = 10;
   */
  tickSizeRule: TickSize[];

  /**
   * General information: The different indices to which this instrument belongs The output is presented as a collection Ticker-Exchange identifying indices.
   *
   * @generated from field: repeated string index = 11;
   */
  index: string[];

  /**
   * General information: The Market Identifier Code (MIC) to use in order to retrieve the calendar for that instrument.
   *
   * @generated from field: string calendar = 12;
   */
  calendar: string;

  /**
   * General information: A brief description of the instrument.
   *
   * @generated from field: string description = 13;
   */
  description: string;

  /**
   * Trading hours: Hours the exchange opens for continuous trading, reported in the time zone of the exchange.
   *
   * @generated from field: google.type.TimeOfDay open = 14;
   */
  open?: TimeOfDay;

  /**
   * Trading hours: Hours the exchange closes for continuous  trading, reported in the time zone of the exchange.
   *
   * @generated from field: google.type.TimeOfDay close = 15;
   */
  close?: TimeOfDay;

  /**
   * Trading hours: The time zone.
   *
   * @generated from field: string time_zone = 16;
   */
  timeZone: string;

  /**
   * Specifications: Specifies the minimum number of shares that can be purchased, as regulated by an exchange.
   *
   * @generated from field: int64 lot_size = 17;
   */
  lotSize: bigint;

  /**
   * Specifications: The amount value of one point basis on a price.
   *
   * @generated from field: double point_value = 18;
   */
  pointValue: number;

  /**
   * Reference data: Reference price for the instrument.
   *
   * @generated from field: double price = 19;
   */
  price: number;

  /**
   * Reference data: Reference volume for the instrument.
   *
   * @generated from field: int64 volume = 20;
   */
  volume: bigint;

  /**
   * Mapping: List of sources contributing to the instrument fields description.
   *
   * @generated from field: int32 sources = 21;
   */
  sources: number;

  /**
   * Mapping: The different codes used to identify the instrument represented in a single string. The output is presented as a collection of pairs of mapping name (ISIN, RIC, SEDOL, FIGI, etc) with its code.
   *
   * @generated from field: map<string, string> mapping = 22;
   */
  mapping: { [key: string]: string };

  /**
   * Mapping: The bloomberg ticker.
   *
   * @generated from field: string bloomberg = 23;
   */
  bloomberg: string;

  /**
   * Mapping: The Reuters Instrument Code (RIC) is a ticker-like code used to identify financial instruments and indices. The RIC is made up primarily of the security's ticker symbol, optionally followed by a period and exchange code based on the name of the stock exchange using that ticker.
   *
   * @generated from field: string reuters = 24;
   */
  reuters: string;

  /**
   * Mapping: The Morningstar ticker used to identify an instrument.
   *
   * @generated from field: string morning_star = 25;
   */
  morningStar: string;

  /**
   * Mapping: The Markit code, also known as RED Code.
   *
   * @generated from field: string markit = 26;
   */
  markit: string;

  /**
   * Mapping: The Financial Instrument Global Identifier (FIGI) is an established global standard of the Object Management Group (www.OMG.org, an international non-profit technology standards consortium founded in 1989) and an identification standard adopted by the American National Committee X9. The FIGI standard is issued and distributed by Bloomberg L.P. as a Registration Authority and Certified Provider under the auspice of OMG. The Financial Instrument Global Identifier (FIGI) is a twelve character, alphanumeric identifier. The first 2 characters are upper-case consonants (including "Y"), the third character is the upper-case "G", characters 4 -11 are any upper-case consonant (including "Y") or integer between 0 and 9, and the last character is a check-digit.
   *
   * @generated from field: string figi = 27;
   */
  figi: string;

  /**
   * Mapping: The Composite Financial Instrument Global Identifier (FIGI) enables users to link multiple FIGIs at the Trading Venue-level within the same country or market in order to obtain an aggregated view for that instrument.
   *
   * @generated from field: string composite_figi = 28;
   */
  compositeFigi: string;

  /**
   * Mapping: The International Securities Identification Number (ISIN) is a twelve-character number assigned by the local national numbering agency. It consists of a two-letter country code, followed by the nine character alphanumerical national security identifier, and a check digit.
   *
   * @generated from field: string isin = 29;
   */
  isin: string;

  /**
   * Mapping: The Committee on Uniform Security Identification Procedures (CUSIP) number is aSecurity identification number for the U.S. and Canada.  It consists of nine alpha-numeric characters. The first six characters identify the issuer, the following two identify the issue, and the final character is a check digit.
   *
   * @generated from field: string cusip = 30;
   */
  cusip: string;

  /**
   * Mapping: The Stock Exchange Daily Official List number (SEDOL) identifier. Numbers issued prior to March 8, 2004 consist of 7 digits.  SEDOLs issued after this date consist of 7 alphanumeric characters, where the first character is always a letter.
   *
   * @generated from field: string sedol = 31;
   */
  sedol: string;

  /**
   * Mapping: The Classification of Financial Instruments (CFI), is a six-letter-code used in the financial services industry to classify and describe the structure and function of a financial instrument. (ISO 10962)
   *
   * @generated from field: string classification = 32;
   */
  classification: string;

  /**
   * Specific values for the future: Ticker of the underling instrument.
   *
   * @generated from field: string underlying = 33;
   */
  underlying: string;

  /**
   * Specific values for the future: Contract symbol code to identify the product. The format of a full ticker is generally composed of the contract symbol code, followed by the maturity month letter, and the last two digits of the maturity year.
   *
   * @generated from field: string contract = 34;
   */
  contract: string;

  /**
   * Specific values for the future: Category group (Energies, Metals, Agriculture, etc.)  where belongs the future contract.
   *
   * @generated from field: map<string, string> category = 35;
   */
  category: { [key: string]: string };

  /**
   * Specific values for the future: The contract months  for a specific futures contract.
   *
   * @generated from field: string chain = 36;
   */
  chain: string;

  /**
   * Specific values for the future: Date the principal of the instrument is due and payable.
   *
   * @generated from field: google.type.Date maturity = 37;
   */
  maturity?: Date;

  /**
   * Specific values for the future: Month the principal of the instrument is due and payable, coded as a letter.
   *
   * @generated from field: string month = 38;
   */
  month: string;

  /**
   * Specific values for the future: Year the principal of the instrument is due and payable.
   *
   * @generated from field: int32 year = 39;
   */
  year: number;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.FutureEntry.
 * Use `create(FutureEntrySchema)` to create a new message.
 */
export const FutureEntrySchema: GenMessage<FutureEntry> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 12);

/**
 * Contains the reference data for crypto / crypto currencies.	
 *
 * @generated from message systemathics.apis.services.static_data.v1.CryptoEntry
 */
export type CryptoEntry = Message<"systemathics.apis.services.static_data.v1.CryptoEntry"> & {
  /**
   * Identifiers: The instrument identifier. It consists of a ticker and an exchange code. (ISO 10383)
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * Date of the data.
   *
   * @generated from field: google.type.Date date = 2;
   */
  date?: Date;

  /**
   * General information: The instrument class.
   *
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * General information: Indicates if the financial instrument is currently active.
   *
   * @generated from field: bool active = 4;
   */
  active: boolean;

  /**
   * General information: The Market Identifier Code (MIC) of the assigned primary exchange on which this specific instrument is traded. (ISO 10383)
   *
   * @generated from field: string primary = 5;
   */
  primary: string;

  /**
   * General information: The entity operating an exchange/market/trade reporting facility in a specific market/country (ISO 10383).
   *
   * @generated from field: string operating = 6;
   */
  operating: string;

  /**
   * General information: Name of the company or brief description of the instrument. The name of an instrument may change in conjunction with corporate actions.
   *
   * @generated from field: string name = 7;
   */
  name: string;

  /**
   * General information: Currency in which the instrument was issued (ISO 4217)
   *
   * @generated from field: string base_currency = 8;
   */
  baseCurrency: string;

  /**
   * General information: Specifies the  country or territory code of where the instrument trades. (ISO 3166)
   *
   * @generated from field: string country = 9;
   */
  country: string;

  /**
   * General information: The minimum amount by which the price of the instrument can change.  Data is represented as a table where there are different tick sizes for different price ranges.
   *
   * @generated from field: repeated systemathics.apis.services.static_data.v1.TickSize tick_size_rule = 10;
   */
  tickSizeRule: TickSize[];

  /**
   * General information: The different indices to which this instrument belongs The output is presented as a collection Ticker-Exchange identifying indices.
   *
   * @generated from field: repeated string index = 11;
   */
  index: string[];

  /**
   * General information: The Market Identifier Code (MIC) to use in order to retrieve the calendar for that instrument.
   *
   * @generated from field: string calendar = 12;
   */
  calendar: string;

  /**
   * General information: A brief description of the instrument.
   *
   * @generated from field: string description = 13;
   */
  description: string;

  /**
   * Trading hours: Hours the exchange opens for continuous trading, reported in the time zone of the exchange.
   *
   * @generated from field: google.type.TimeOfDay open = 14;
   */
  open?: TimeOfDay;

  /**
   * Trading hours: Hours the exchange closes for continuous  trading, reported in the time zone of the exchange.
   *
   * @generated from field: google.type.TimeOfDay close = 15;
   */
  close?: TimeOfDay;

  /**
   * Trading hours: The time zone.
   *
   * @generated from field: string time_zone = 16;
   */
  timeZone: string;

  /**
   * Specifications: Specifies the minimum number of shares that can be purchased, as regulated by an exchange.
   *
   * @generated from field: int64 lot_size = 17;
   */
  lotSize: bigint;

  /**
   * Specifications: The amount value of one point basis on a price.
   *
   * @generated from field: double point_value = 18;
   */
  pointValue: number;

  /**
   * Reference data: Reference price for the instrument.
   *
   * @generated from field: double price = 19;
   */
  price: number;

  /**
   * Reference data: Reference volume for the instrument.
   *
   * @generated from field: int64 volume = 20;
   */
  volume: bigint;

  /**
   * Mapping: List of sources contributing to the instrument fields description.
   *
   * @generated from field: int32 sources = 21;
   */
  sources: number;

  /**
   * Mapping: The different codes used to identify the instrument represented in a single string. The output is presented as a collection of pairs of mapping name (ISIN, RIC, SEDOL, FIGI, etc) with its code.
   *
   * @generated from field: map<string, string> mapping = 22;
   */
  mapping: { [key: string]: string };

  /**
   * Mapping: The bloomberg ticker.
   *
   * @generated from field: string bloomberg = 23;
   */
  bloomberg: string;

  /**
   * Mapping: The Reuters Instrument Code (RIC) is a ticker-like code used to identify financial instruments and indices. The RIC is made up primarily of the security's ticker symbol, optionally followed by a period and exchange code based on the name of the stock exchange using that ticker.
   *
   * @generated from field: string reuters = 24;
   */
  reuters: string;

  /**
   * Mapping: The Morningstar ticker used to identify an instrument.
   *
   * @generated from field: string morning_star = 25;
   */
  morningStar: string;

  /**
   * Mapping: The Markit code, also known as RED Code.
   *
   * @generated from field: string markit = 26;
   */
  markit: string;

  /**
   * Mapping: The Financial Instrument Global Identifier (FIGI) is an established global standard of the Object Management Group (www.OMG.org, an international non-profit technology standards consortium founded in 1989) and an identification standard adopted by the American National Committee X9. The FIGI standard is issued and distributed by Bloomberg L.P. as a Registration Authority and Certified Provider under the auspice of OMG. The Financial Instrument Global Identifier (FIGI) is a twelve character, alphanumeric identifier. The first 2 characters are upper-case consonants (including "Y"), the third character is the upper-case "G", characters 4 -11 are any upper-case consonant (including "Y") or integer between 0 and 9, and the last character is a check-digit.
   *
   * @generated from field: string figi = 27;
   */
  figi: string;

  /**
   * Mapping: The Composite Financial Instrument Global Identifier (FIGI) enables users to link multiple FIGIs at the Trading Venue-level within the same country or market in order to obtain an aggregated view for that instrument.
   *
   * @generated from field: string composite_figi = 28;
   */
  compositeFigi: string;

  /**
   * Mapping: The International Securities Identification Number (ISIN) is a twelve-character number assigned by the local national numbering agency. It consists of a two-letter country code, followed by the nine character alphanumerical national security identifier, and a check digit.
   *
   * @generated from field: string isin = 29;
   */
  isin: string;

  /**
   * Mapping: The Committee on Uniform Security Identification Procedures (CUSIP) number is aSecurity identification number for the U.S. and Canada.  It consists of nine alpha-numeric characters. The first six characters identify the issuer, the following two identify the issue, and the final character is a check digit.
   *
   * @generated from field: string cusip = 30;
   */
  cusip: string;

  /**
   * Mapping: The Stock Exchange Daily Official List number (SEDOL) identifier. Numbers issued prior to March 8, 2004 consist of 7 digits.  SEDOLs issued after this date consist of 7 alphanumeric characters, where the first character is always a letter.
   *
   * @generated from field: string sedol = 31;
   */
  sedol: string;

  /**
   * Mapping: The Classification of Financial Instruments (CFI), is a six-letter-code used in the financial services industry to classify and describe the structure and function of a financial instrument. (ISO 10962)
   *
   * @generated from field: string classification = 32;
   */
  classification: string;

  /**
   * Specific values for the crypto: Currency in which the instrument is priced (ISO 4217)
   *
   * @generated from field: string quote_currency = 33;
   */
  quoteCurrency: string;

  /**
   * Specific values for the crypto: The program used in blockchain systems to achieve distributed agreement about the ledger's state.
   *
   * @generated from field: repeated string consensus = 34;
   */
  consensus: string[];

  /**
   * Specific values for the crypto: Date the instrument is issued.
   *
   * @generated from field: google.type.Date issue_date = 35;
   */
  issueDate?: Date;

  /**
   * Specific values for the crypto: The total value of a publicly traded company's outstanding common shares owned by stockholders.   Market capitalization is equal to the market price per common share multiplied by the number of common shares outstanding.
   *
   * @generated from field: int64 capitalization = 36;
   */
  capitalization: bigint;

  /**
   * The number of coins that are circulating in the market and in the general public's hands
   *
   * @generated from field: int64 circulating_supply = 37;
   */
  circulatingSupply: bigint;

  /**
   * Specific values for the crypto: The maximum amount of coins that will ever exist in the lifetime of the cryptocurrency
   *
   * @generated from field: int64 max_supply = 38;
   */
  maxSupply: bigint;

  /**
   * Specific values for the crypto: The total amount of coins in existence right now (minus any coins that have been verifiably burned)
   *
   * @generated from field: int64 total_supply = 39;
   */
  totalSupply: bigint;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.CryptoEntry.
 * Use `create(CryptoEntrySchema)` to create a new message.
 */
export const CryptoEntrySchema: GenMessage<CryptoEntry> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 13);

/**
 * @generated from message systemathics.apis.services.static_data.v1.StaticDataIdentifiers
 */
export type StaticDataIdentifiers = Message<"systemathics.apis.services.static_data.v1.StaticDataIdentifiers"> & {
  /**
   * [Mandatory] The Identifiers
   *
   * @generated from field: repeated systemathics.apis.services.static_data.v1.StaticDataIdentifier identifiers = 1;
   */
  identifiers: StaticDataIdentifier[];
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.StaticDataIdentifiers.
 * Use `create(StaticDataIdentifiersSchema)` to create a new message.
 */
export const StaticDataIdentifiersSchema: GenMessage<StaticDataIdentifiers> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 14);

/**
 * @generated from message systemathics.apis.services.static_data.v1.StaticDataIdentifier
 */
export type StaticDataIdentifier = Message<"systemathics.apis.services.static_data.v1.StaticDataIdentifier"> & {
  /**
   * [Mandatory] Identifier
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date associated with identifier. Latest version is used if missing.
   *
   * @generated from field: google.type.Date date = 2;
   */
  date?: Date;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.StaticDataIdentifier.
 * Use `create(StaticDataIdentifierSchema)` to create a new message.
 */
export const StaticDataIdentifierSchema: GenMessage<StaticDataIdentifier> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 15);

/**
 * Contains the tick size rule item : price and tick.
 *
 * @generated from message systemathics.apis.services.static_data.v1.TickSize
 */
export type TickSize = Message<"systemathics.apis.services.static_data.v1.TickSize"> & {
  /**
   * The price level
   *
   * @generated from field: double price = 1;
   */
  price: number;

  /**
   * The tick size
   *
   * @generated from field: double tick = 2;
   */
  tick: number;
};

/**
 * Describes the message systemathics.apis.services.static_data.v1.TickSize.
 * Use `create(TickSizeSchema)` to create a new message.
 */
export const TickSizeSchema: GenMessage<TickSize> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_static_data_v1_static_data, 16);

/**
 * Contains the frequency types.
 *
 * @generated from enum systemathics.apis.services.static_data.v1.FrequencyType
 */
export enum FrequencyType {
  /**
   * Not specified ?
   *
   * @generated from enum value: FREQUENCY_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * None
   *
   * @generated from enum value: FREQUENCY_TYPE_NONE = 1;
   */
  NONE = 1,

  /**
   * Daily
   *
   * @generated from enum value: FREQUENCY_TYPE_DAY = 2;
   */
  DAY = 2,

  /**
   * Weekly
   *
   * @generated from enum value: FREQUENCY_TYPE_WEEK = 3;
   */
  WEEK = 3,

  /**
   * Monthly
   *
   * @generated from enum value: FREQUENCY_TYPE_MONTH = 4;
   */
  MONTH = 4,

  /**
   * Quarterly
   *
   * @generated from enum value: FREQUENCY_TYPE_QUARTER = 5;
   */
  QUARTER = 5,

  /**
   * Semi-Annually
   *
   * @generated from enum value: FREQUENCY_TYPE_SEMIANNUAL = 6;
   */
  SEMIANNUAL = 6,

  /**
   * Annually
   *
   * @generated from enum value: FREQUENCY_TYPE_ANNUAL = 7;
   */
  ANNUAL = 7,

  /**
   * Bi-Annually
   *
   * @generated from enum value: FREQUENCY_TYPE_BIANNUAL = 8;
   */
  BIANNUAL = 8,
}

/**
 * Describes the enum systemathics.apis.services.static_data.v1.FrequencyType.
 */
export const FrequencyTypeSchema: GenEnum<FrequencyType> = /*@__PURE__*/
  enumDesc(file_systemathics_apis_services_static_data_v1_static_data, 0);

/**
 * Contains the option exercise types : Determines when, how, and under what circumstances, the option holder may exercise it.
 *
 * @generated from enum systemathics.apis.services.static_data.v1.ExerciseType
 */
export enum ExerciseType {
  /**
   * Not specified ?
   *
   * @generated from enum value: EXERCISE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The American-style option contracts can be exercised at any time up to the option's expiration.
   *
   * @generated from enum value: EXERCISE_TYPE_AMERICAN = 1;
   */
  AMERICAN = 1,

  /**
   * The European-style option contracts may only be exercised at the option's expiration date.
   *
   * @generated from enum value: EXERCISE_TYPE_EUROPEAN = 2;
   */
  EUROPEAN = 2,

  /**
   * The Bermudan-style options contracts may only be exercised on specified dates.
   *
   * @generated from enum value: EXERCISE_TYPE_BERMUDAN = 3;
   */
  BERMUDAN = 3,
}

/**
 * Describes the enum systemathics.apis.services.static_data.v1.ExerciseType.
 */
export const ExerciseTypeSchema: GenEnum<ExerciseType> = /*@__PURE__*/
  enumDesc(file_systemathics_apis_services_static_data_v1_static_data, 1);

/**
 * Describe a coupon frequency.
 *
 * @generated from enum systemathics.apis.services.static_data.v1.CouponFrequency
 */
export enum CouponFrequency {
  /**
   * Not specified coupon frequency
   *
   * @generated from enum value: COUPON_FREQUENCY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Annual coupon frequency
   *
   * @generated from enum value: COUPON_FREQUENCY_ANNUAL = 1;
   */
  ANNUAL = 1,

  /**
   * SemiAnnual coupon frequency
   *
   * @generated from enum value: COUPON_FREQUENCY_SEMI_ANNUAL = 2;
   */
  SEMI_ANNUAL = 2,

  /**
   * Quaterly coupon frequency
   *
   * @generated from enum value: COUPON_FREQUENCY_QUATERLY = 4;
   */
  QUATERLY = 4,

  /**
   * BiMonthly coupon frequency
   *
   * @generated from enum value: COUPON_FREQUENCY_BI_MONTHLY = 6;
   */
  BI_MONTHLY = 6,

  /**
   * Monthly coupon frequency
   *
   * @generated from enum value: COUPON_FREQUENCY_MONTHLY = 12;
   */
  MONTHLY = 12,

  /**
   * Weekly coupon frequency
   *
   * @generated from enum value: COUPON_FREQUENCY_WEEKLY = 52;
   */
  WEEKLY = 52,
}

/**
 * Describes the enum systemathics.apis.services.static_data.v1.CouponFrequency.
 */
export const CouponFrequencySchema: GenEnum<CouponFrequency> = /*@__PURE__*/
  enumDesc(file_systemathics_apis_services_static_data_v1_static_data, 2);

/**
 * @generated from enum systemathics.apis.services.static_data.v1.DayCount
 */
export enum DayCount {
  /**
   * Not specified day count
   *
   * @generated from enum value: DAY_COUNT_UNSPECIFIED = 0;
   */
  DAY_COUNT_UNSPECIFIED = 0,

  /**
   * ACT/ACT day count
   *
   * @generated from enum value: DAY_COUNT_ACT_ACT = 1;
   */
  DAY_COUNT_ACT_ACT = 1,

  /**
   * ACT/360 day count
   *
   * @generated from enum value: DAY_COUNT_ACT_360 = 2;
   */
  DAY_COUNT_ACT_360 = 2,

  /**
   * ACT/365 day count
   *
   * @generated from enum value: DAY_COUNT_ACT_365 = 3;
   */
  DAY_COUNT_ACT_365 = 3,

  /**
   * 30/ACT day count
   *
   * @generated from enum value: DAY_COUNT_30_ACT = 4;
   */
  DAY_COUNT_30_ACT = 4,

  /**
   * 30/360 day count
   *
   * @generated from enum value: DAY_COUNT_30_360 = 5;
   */
  DAY_COUNT_30_360 = 5,

  /**
   * 30/365 day count
   *
   * @generated from enum value: DAY_COUNT_30_365 = 6;
   */
  DAY_COUNT_30_365 = 6,

  /**
   * NL/ACT day count
   *
   * @generated from enum value: DAY_COUNT_NL_ACT = 7;
   */
  DAY_COUNT_NL_ACT = 7,

  /**
   * NL/360 day count
   *
   * @generated from enum value: DAY_COUNT_NL_360 = 8;
   */
  DAY_COUNT_NL_360 = 8,

  /**
   * NL/365 day count
   *
   * @generated from enum value: DAY_COUNT_NL_365 = 9;
   */
  DAY_COUNT_NL_365 = 9,

  /**
   * ACT/ACT NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_ACT_ACT_NON_EOM = 10;
   */
  DAY_COUNT_ACT_ACT_NON_EOM = 10,

  /**
   * ACT/360 NON-EOM  day count
   *
   * @generated from enum value: DAY_COUNT_ACT_360_NON_EOM = 11;
   */
  DAY_COUNT_ACT_360_NON_EOM = 11,

  /**
   * ACT/365 NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_ACT_365_NON_EOM = 12;
   */
  DAY_COUNT_ACT_365_NON_EOM = 12,

  /**
   * 30/ACT NON-EOM  day count
   *
   * @generated from enum value: DAY_COUNT_30_ACT_NON_EOM = 13;
   */
  DAY_COUNT_30_ACT_NON_EOM = 13,

  /**
   * 30/360 NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_30_360_NON_EOM = 14;
   */
  DAY_COUNT_30_360_NON_EOM = 14,

  /**
   * 30/365 NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_30_365_NON_EOM = 15;
   */
  DAY_COUNT_30_365_NON_EOM = 15,

  /**
   * NL/ACT NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_NL_ACT_NON_EOM = 16;
   */
  DAY_COUNT_NL_ACT_NON_EOM = 16,

  /**
   * NL/360 NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_NL_360_NON_EOM = 17;
   */
  DAY_COUNT_NL_360_NON_EOM = 17,

  /**
   * NL/365 NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_NL_365_NON_EOM = 18;
   */
  DAY_COUNT_NL_365_NON_EOM = 18,

  /**
   * ISMA-30/ACT day count
   *
   * @generated from enum value: DAY_COUNT_ISMA_30_ACT = 19;
   */
  DAY_COUNT_ISMA_30_ACT = 19,

  /**
   * ISMA-30/360 day count
   *
   * @generated from enum value: DAY_COUNT_ISMA_30_360 = 20;
   */
  DAY_COUNT_ISMA_30_360 = 20,

  /**
   * ISMA-30/365 day count
   *
   * @generated from enum value: DAY_COUNT_ISMA_30_365 = 21;
   */
  DAY_COUNT_ISMA_30_365 = 21,

  /**
   * ISMA30/ACT NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_ISMA30_ACT_NON_EOM = 22;
   */
  DAY_COUNT_ISMA30_ACT_NON_EOM = 22,

  /**
   * ISMA-30/360 NONEOM day count
   *
   * @generated from enum value: DAY_COUNT_ISMA_30_360_NONEOM = 23;
   */
  DAY_COUNT_ISMA_30_360_NONEOM = 23,

  /**
   * ISMA30/365 NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_ISMA30_365_NON_EOM = 24;
   */
  DAY_COUNT_ISMA30_365_NON_EOM = 24,

  /**
   * ACT/364 day count
   *
   * @generated from enum value: DAY_COUNT_ACT_364 = 27;
   */
  DAY_COUNT_ACT_364 = 27,

  /**
   * ACT/365-66 day count
   *
   * @generated from enum value: DAY_COUNT_ACT_365_66 = 28;
   */
  DAY_COUNT_ACT_365_66 = 28,

  /**
   * US MUNI: 30/360 day count
   *
   * @generated from enum value: DAY_COUNT_US_MUNI_30_360 = 29;
   */
  DAY_COUNT_US_MUNI_30_360 = 29,

  /**
   * ACT/364 NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_ACT_364_NON_EOM = 30;
   */
  DAY_COUNT_ACT_364_NON_EOM = 30,

  /**
   * MUNI30/360 NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_MUNI30_360_NON_EOM = 32;
   */
  DAY_COUNT_MUNI30_360_NON_EOM = 32,

  /**
   * BUS DAYS/252 day count
   *
   * @generated from enum value: DAY_COUNT_BUS_DAYS_252 = 33;
   */
  DAY_COUNT_BUS_DAYS_252 = 33,

  /**
   * GERMAN:30/360 day count
   *
   * @generated from enum value: DAY_COUNT_GERMAN_30_360 = 35;
   */
  DAY_COUNT_GERMAN_30_360 = 35,

  /**
   * BUS DAY/252NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_BUS_DAY_252NON_EOM = 36;
   */
  DAY_COUNT_BUS_DAY_252NON_EOM = 36,

  /**
   * ACT/365-66 NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_ACT_365_66_NON_EOM = 37;
   */
  DAY_COUNT_ACT_365_66_NON_EOM = 37,

  /**
   * GER:�30/360�NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_GER_30_360_NON_EOM = 38;
   */
  DAY_COUNT_GER_30_360_NON_EOM = 38,

  /**
   * US:WIT ACT/ACT day count
   *
   * @generated from enum value: DAY_COUNT_US_WIT_ACT_ACT = 40;
   */
  DAY_COUNT_US_WIT_ACT_ACT = 40,

  /**
   * US:WIB ACT/360 day count
   *
   * @generated from enum value: DAY_COUNT_US_WIB_ACT_360 = 41;
   */
  DAY_COUNT_US_WIB_ACT_360 = 41,

  /**
   * ISDA SWAPS:30/360 day count
   *
   * @generated from enum value: DAY_COUNT_ISDA_SWAPS_30_360 = 44;
   */
  DAY_COUNT_ISDA_SWAPS_30_360 = 44,

  /**
   * ISDA SWAPS:30/365 day count
   *
   * @generated from enum value: DAY_COUNT_ISDA_SWAPS_30_365 = 45;
   */
  DAY_COUNT_ISDA_SWAPS_30_365 = 45,

  /**
   * ISDA30/360 NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_ISDA30_360_NON_EOM = 47;
   */
  DAY_COUNT_ISDA30_360_NON_EOM = 47,

  /**
   * ISDA30/365 NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_ISDA30_365_NON_EOM = 48;
   */
  DAY_COUNT_ISDA30_365_NON_EOM = 48,

  /**
   * ISDA30/ACT NON-EOM day count
   *
   * @generated from enum value: DAY_COUNT_ISDA30_ACT_NON_EOM = 49;
   */
  DAY_COUNT_ISDA30_ACT_NON_EOM = 49,

  /**
   * ISDA 30E/360 day count
   *
   * @generated from enum value: DAY_COUNT_ISDA_30E_360 = 50;
   */
  DAY_COUNT_ISDA_30E_360 = 50,

  /**
   * ISDA 30E/365 day count
   *
   * @generated from enum value: DAY_COUNT_ISDA_30E_365 = 51;
   */
  DAY_COUNT_ISDA_30E_365 = 51,

  /**
   * ISDA 30E/ACT day count
   *
   * @generated from enum value: DAY_COUNT_ISDA_30E_ACT = 52;
   */
  DAY_COUNT_ISDA_30E_ACT = 52,

  /**
   * ISDA 30E/360 N-EOM day count
   *
   * @generated from enum value: DAY_COUNT_ISDA_30E_360_N_EOM = 53;
   */
  DAY_COUNT_ISDA_30E_360_N_EOM = 53,

  /**
   * ISDA 30E/365 N-EOM day count
   *
   * @generated from enum value: DAY_COUNT_ISDA_30E_365_N_EOM = 54;
   */
  DAY_COUNT_ISDA_30E_365_N_EOM = 54,

  /**
   * ISDA�ACT/ACT day count
   *
   * @generated from enum value: DAY_COUNT_ISDA_ACT_ACT = 58;
   */
  DAY_COUNT_ISDA_ACT_ACT = 58,

  /**
   * ISDA ACT/ACT N-EOM day count
   *
   * @generated from enum value: DAY_COUNT_ISDA_ACT_ACT_N_EOM = 61;
   */
  DAY_COUNT_ISDA_ACT_ACT_N_EOM = 61,

  /**
   * 28/360 day count
   *
   * @generated from enum value: DAY_COUNT_28_360 = 62;
   */
  DAY_COUNT_28_360 = 62,

  /**
   * BD/252 day count
   *
   * @generated from enum value: DAY_COUNT_BD_252 = 99;
   */
  DAY_COUNT_BD_252 = 99,

  /**
   * ACT/ACT(101) day count
   *
   * @generated from enum value: DAY_COUNT_ACT_ACT_101 = 101;
   */
  DAY_COUNT_ACT_ACT_101 = 101,

  /**
   * ACT/360(102) day count
   *
   * @generated from enum value: DAY_COUNT_ACT_360_102 = 102;
   */
  DAY_COUNT_ACT_360_102 = 102,

  /**
   * ACT/365(103) day count
   *
   * @generated from enum value: DAY_COUNT_ACT_365_103 = 103;
   */
  DAY_COUNT_ACT_365_103 = 103,

  /**
   * 30/360(104) day count
   *
   * @generated from enum value: DAY_COUNT_30_360_104 = 104;
   */
  DAY_COUNT_30_360_104 = 104,

  /**
   * ACT/ACT NOM(105) day count
   *
   * @generated from enum value: DAY_COUNT_ACT_ACT_NOM_105 = 105;
   */
  DAY_COUNT_ACT_ACT_NOM_105 = 105,

  /**
   * ACT/360 NOM(106) day count
   *
   * @generated from enum value: DAY_COUNT_ACT_360_NOM_106 = 106;
   */
  DAY_COUNT_ACT_360_NOM_106 = 106,

  /**
   * ACT/365 NOM(107) day count
   *
   * @generated from enum value: DAY_COUNT_ACT_365_NOM_107 = 107;
   */
  DAY_COUNT_ACT_365_NOM_107 = 107,

  /**
   * ISMA 30/360(131) day count
   *
   * @generated from enum value: DAY_COUNT_ISMA_30_360_131 = 131;
   */
  DAY_COUNT_ISMA_30_360_131 = 131,

  /**
   * ISDA ACT/ACT(201) day count
   *
   * @generated from enum value: DAY_COUNT_ISDA_ACT_ACT_201 = 201;
   */
  DAY_COUNT_ISDA_ACT_ACT_201 = 201,

  /**
   * AFB ACT/ACT(202) day count
   *
   * @generated from enum value: DAY_COUNT_AFB_ACT_ACT_202 = 202;
   */
  DAY_COUNT_AFB_ACT_ACT_202 = 202,

  /**
   * ISDA ACT/ACT NOM(203) day count
   *
   * @generated from enum value: DAY_COUNT_ISDA_ACT_ACT_NOM_203 = 203;
   */
  DAY_COUNT_ISDA_ACT_ACT_NOM_203 = 203,

  /**
   * AFB ACT/ACT NOM(204) day count
   *
   * @generated from enum value: DAY_COUNT_AFB_ACT_ACT_NOM_204 = 204;
   */
  DAY_COUNT_AFB_ACT_ACT_NOM_204 = 204,

  /**
   * ISMA ACT/ACT (206) day count
   *
   * @generated from enum value: DAY_COUNT_ISMA_ACT_ACT__206 = 206;
   */
  DAY_COUNT_ISMA_ACT_ACT__206 = 206,

  /**
   * ISMA ACT/ACT NOM(207) day count
   *
   * @generated from enum value: DAY_COUNT_ISMA_ACT_ACT_NOM_207 = 207;
   */
  DAY_COUNT_ISMA_ACT_ACT_NOM_207 = 207,

  /**
   * BUSINESS/252 day count
   *
   * @generated from enum value: DAY_COUNT_BUSINESS_252 = 252;
   */
  DAY_COUNT_BUSINESS_252 = 252,

  /**
   * 30E/360 day count
   *
   * @generated from enum value: DAY_COUNT_30E_360 = 990;
   */
  DAY_COUNT_30E_360 = 990,

  /**
   * 30E/365 day count
   *
   * @generated from enum value: DAY_COUNT_30E_365 = 991;
   */
  DAY_COUNT_30E_365 = 991,

  /**
   * 30E/ACT day count
   *
   * @generated from enum value: DAY_COUNT_30E_ACT = 992;
   */
  DAY_COUNT_30E_ACT = 992,

  /**
   * 30G/360 day count
   *
   * @generated from enum value: DAY_COUNT_30G_360 = 993;
   */
  DAY_COUNT_30G_360 = 993,

  /**
   * 301/360 day count
   *
   * @generated from enum value: DAY_COUNT_301_360 = 994;
   */
  DAY_COUNT_301_360 = 994,

  /**
   * 301/365 day count
   *
   * @generated from enum value: DAY_COUNT_301_365 = 995;
   */
  DAY_COUNT_301_365 = 995,

  /**
   * 30I/ACT day count
   *
   * @generated from enum value: DAY_COUNT_30I_ACT = 996;
   */
  DAY_COUNT_30I_ACT = 996,

  /**
   * 30M/360 day count
   *
   * @generated from enum value: DAY_COUNT_30M_360 = 997;
   */
  DAY_COUNT_30M_360 = 997,
}

/**
 * Describes the enum systemathics.apis.services.static_data.v1.DayCount.
 */
export const DayCountSchema: GenEnum<DayCount> = /*@__PURE__*/
  enumDesc(file_systemathics_apis_services_static_data_v1_static_data, 3);

/**
 * @generated from enum systemathics.apis.services.static_data.v1.SwaptionType
 */
export enum SwaptionType {
  /**
   * @generated from enum value: SWAPTION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SWAPTION_TYPE_PAYER = 1;
   */
  PAYER = 1,

  /**
   * @generated from enum value: SWAPTION_TYPE_RECEIVER = 2;
   */
  RECEIVER = 2,
}

/**
 * Describes the enum systemathics.apis.services.static_data.v1.SwaptionType.
 */
export const SwaptionTypeSchema: GenEnum<SwaptionType> = /*@__PURE__*/
  enumDesc(file_systemathics_apis_services_static_data_v1_static_data, 4);

/**
 * Called to request reference data.
 *
 * @generated from service systemathics.apis.services.static_data.v1.StaticDataService
 */
export const StaticDataService: GenService<{
  /**
   * Gets reference data
   *
   * @generated from rpc systemathics.apis.services.static_data.v1.StaticDataService.Search
   */
  search: {
    methodKind: "unary";
    input: typeof StaticDataSearchRequestSchema;
    output: typeof StaticDataResponseSchema;
  },
  /**
   * Get a Static data asset by Identifiers
   *
   * @generated from rpc systemathics.apis.services.static_data.v1.StaticDataService.GetByIdentifiers
   */
  getByIdentifiers: {
    methodKind: "unary";
    input: typeof StaticDataIdentifiersSchema;
    output: typeof StaticDataResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_static_data_v1_static_data, 0);

