// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Up-to-date symbol changes annoucements including effective date, old and new symbols.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/corporate_actions/v1/changes.proto (package systemathics.apis.services.corporate_actions.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_type_date } from "../../../../../google/type/date_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";

/**
 * Describes the file systemathics/apis/services/corporate_actions/v1/changes.proto.
 */
export const file_systemathics_apis_services_corporate_actions_v1_changes = /*@__PURE__*/
  fileDesc("Cj1zeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9jb3Jwb3JhdGVfYWN0aW9ucy92MS9jaGFuZ2VzLnByb3RvEi9zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5jb3Jwb3JhdGVfYWN0aW9ucy52MSKZAQoOQ2hhbmdlc1JlcXVlc3QSQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISRQoNZGF0ZV9pbnRlcnZhbBgCIAEoCzIuLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLkRhdGVJbnRlcnZhbCJYCg9DaGFuZ2VzUmVzcG9uc2USRQoEZGF0YRgBIAMoCzI3LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmNvcnBvcmF0ZV9hY3Rpb25zLnYxLkNoYW5nZSJgCgZDaGFuZ2USHwoEZGF0ZRgBIAEoCzIRLmdvb2dsZS50eXBlLkRhdGUSEgoKbmV3X3N5bWJvbBgCIAEoCRISCgpvbGRfc3ltYm9sGAMgASgJEg0KBXNjb3JlGAQgASgBMsYBCg5DaGFuZ2VzU2VydmljZRKzAQoHQ2hhbmdlcxI/LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmNvcnBvcmF0ZV9hY3Rpb25zLnYxLkNoYW5nZXNSZXF1ZXN0GkAuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuY29ycG9yYXRlX2FjdGlvbnMudjEuQ2hhbmdlc1Jlc3BvbnNlIiWC0+STAh8SHS92MS9jb3Jwb3JhdGUtYWN0aW9ucy9jaGFuZ2VzYgZwcm90bzM", [file_google_api_annotations, file_google_type_date, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval]);

/**
 * Describes the message systemathics.apis.services.corporate_actions.v1.ChangesRequest.
 * Use `create(ChangesRequestSchema)` to create a new message.
 */
export const ChangesRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_corporate_actions_v1_changes, 0);

/**
 * Describes the message systemathics.apis.services.corporate_actions.v1.ChangesResponse.
 * Use `create(ChangesResponseSchema)` to create a new message.
 */
export const ChangesResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_corporate_actions_v1_changes, 1);

/**
 * Describes the message systemathics.apis.services.corporate_actions.v1.Change.
 * Use `create(ChangeSchema)` to create a new message.
 */
export const ChangeSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_corporate_actions_v1_changes, 2);

/**
 * Called to request symbol changes data.
 *
 * @generated from service systemathics.apis.services.corporate_actions.v1.ChangesService
 */
export const ChangesService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_corporate_actions_v1_changes, 0);

