// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Up-to-date split annoucements including effective date, old and new shares.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/corporate_actions/v1/splits.proto (package systemathics.apis.services.corporate_actions.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { Date } from "../../../../../google/type/date_pb";

/**
 * Describes the file systemathics/apis/services/corporate_actions/v1/splits.proto.
 */
export declare const file_systemathics_apis_services_corporate_actions_v1_splits: GenFile;

/**
 * The required input to request the SplitsService
 *
 * @generated from message systemathics.apis.services.corporate_actions.v1.SplitsRequest
 */
export declare type SplitsRequest = Message<"systemathics.apis.services.corporate_actions.v1.SplitsRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Optional] The date interval used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 2;
   */
  dateInterval?: DateInterval;
};

/**
 * Describes the message systemathics.apis.services.corporate_actions.v1.SplitsRequest.
 * Use `create(SplitsRequestSchema)` to create a new message.
 */
export declare const SplitsRequestSchema: GenMessage<SplitsRequest>;

/**
 * Represents a split response.
 *
 * @generated from message systemathics.apis.services.corporate_actions.v1.SplitsResponse
 */
export declare type SplitsResponse = Message<"systemathics.apis.services.corporate_actions.v1.SplitsResponse"> & {
  /**
   * The splits: an array of Split objects
   *
   * @generated from field: repeated systemathics.apis.services.corporate_actions.v1.Split data = 1;
   */
  data: Split[];
};

/**
 * Describes the message systemathics.apis.services.corporate_actions.v1.SplitsResponse.
 * Use `create(SplitsResponseSchema)` to create a new message.
 */
export declare const SplitsResponseSchema: GenMessage<SplitsResponse>;

/**
 * Contains the splits data: date, old and new shares.
 *
 * @generated from message systemathics.apis.services.corporate_actions.v1.Split
 */
export declare type Split = Message<"systemathics.apis.services.corporate_actions.v1.Split"> & {
  /**
   * Effective date
   *
   * @generated from field: google.type.Date date = 1;
   */
  date?: Date;

  /**
   * New shares
   *
   * @generated from field: double new_shares = 2;
   */
  newShares: number;

  /**
   * Old shares
   *
   * @generated from field: double old_shares = 3;
   */
  oldShares: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 4;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.corporate_actions.v1.Split.
 * Use `create(SplitSchema)` to create a new message.
 */
export declare const SplitSchema: GenMessage<Split>;

/**
 * Called to request splits data.
 *
 * @generated from service systemathics.apis.services.corporate_actions.v1.SplitsService
 */
export declare const SplitsService: GenService<{
  /**
   * Gets splits historical data
   *
   * @generated from rpc systemathics.apis.services.corporate_actions.v1.SplitsService.Splits
   */
  splits: {
    methodKind: "unary";
    input: typeof SplitsRequestSchema;
    output: typeof SplitsResponseSchema;
  },
}>;

