// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The Relative Strength Index</i>, developed by J. Welles Wilder measures the speed and change of price movements.
// <br>RSI oscillates between zero and 100. Traditionally the RSI is considered <i>overbought</i> when above 70 and <i>oversold</i> when below 30.
// <br><br>RSI is computed as follows: $$ RSI = 100 - \frac{100}{1 + RS} $$ Where:
// <br>- <i>RS = AvgU/AvgD</i> is the <i>relative strength
// <br>- <i>AvgU</i> average of last <i>N close prices</i> up moves
// <br>- <i>AvgD</i> average of last <i>N close prices</i> down moves
// <br>- <i>N</i> is the period of the RSI

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/intraday_analytics/v1/intraday_rsi.proto (package systemathics.apis.services.intraday_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/intraday_analytics/v1/intraday_rsi.proto.
 */
export const file_systemathics_apis_services_intraday_analytics_v1_intraday_rsi: GenFile = /*@__PURE__*/
  fileDesc("CkNzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheV9hbmFseXRpY3MvdjEvaW50cmFkYXlfcnNpLnByb3RvEjBzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheV9hbmFseXRpY3MudjEi/wEKEkludHJhZGF5UnNpUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchI8CghzYW1wbGluZxgCIAEoDjIqLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLlNhbXBsaW5nEkUKDWRhdGVfaW50ZXJ2YWwYAyABKAsyLi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5EYXRlSW50ZXJ2YWwSDgoGbGVuZ3RoGAQgASgFEhIKCmFkanVzdG1lbnQYBSABKAgiZgoTSW50cmFkYXlSc2lSZXNwb25zZRJPCgRkYXRhGAEgAygLMkEuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXlfYW5hbHl0aWNzLnYxLkludHJhZGF5UnNpRGF0YSJdCg9JbnRyYWRheVJzaURhdGESLgoKdGltZV9zdGFtcBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDQoFdmFsdWUYAiABKAESCwoDcnNpGAMgASgBMssBChJJbnRyYWRheVJzaVNlcnZpY2UStAEKC0ludHJhZGF5UnNpEkQuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXlfYW5hbHl0aWNzLnYxLkludHJhZGF5UnNpUmVxdWVzdBpFLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5X2FuYWx5dGljcy52MS5JbnRyYWRheVJzaVJlc3BvbnNlIhiC0+STAhISEC92MS9pbnRyYWRheS9yc2liBnByb3RvMw", [file_google_api_annotations, file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * The required input to request the IntradayRsiService.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayRsiRequest
 */
export type IntradayRsiRequest = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayRsiRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Mandatory] The relative strength index window length (period: points number)
   *
   * @generated from field: int32 length = 4;
   */
  length: number;

  /**
   * [Optional] The corporate action adjustment (dividends and splits).
   * By default the value is set to false
   *
   * @generated from field: bool adjustment = 5;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayRsiRequest.
 * Use `create(IntradayRsiRequestSchema)` to create a new message.
 */
export const IntradayRsiRequestSchema: GenMessage<IntradayRsiRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_rsi, 0);

/**
 * Represents a intraday relative strength index response.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayRsiResponse
 */
export type IntradayRsiResponse = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayRsiResponse"> & {
  /**
   * The intraday relative strength index: an array of IntradayRsiData objects
   *
   * @generated from field: repeated systemathics.apis.services.intraday_analytics.v1.IntradayRsiData data = 1;
   */
  data: IntradayRsiData[];
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayRsiResponse.
 * Use `create(IntradayRsiResponseSchema)` to create a new message.
 */
export const IntradayRsiResponseSchema: GenMessage<IntradayRsiResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_rsi, 1);

/**
 * Contains the intraday relative strength index data: date and value.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayRsiData
 */
export type IntradayRsiData = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayRsiData"> & {
  /**
   * Time stamp of the relative strength index : open time of the sampling interval
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * The data used to calculate the relative strength index of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * Relative strength index value of the day
   *
   * @generated from field: double rsi = 3;
   */
  rsi: number;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayRsiData.
 * Use `create(IntradayRsiDataSchema)` to create a new message.
 */
export const IntradayRsiDataSchema: GenMessage<IntradayRsiData> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_rsi, 2);

/**
 * Called to request intraday relative strength index data. 
 *
 * @generated from service systemathics.apis.services.intraday_analytics.v1.IntradayRsiService
 */
export const IntradayRsiService: GenService<{
  /**
   * Gets intraday relative strength index data
   *
   * @generated from rpc systemathics.apis.services.intraday_analytics.v1.IntradayRsiService.IntradayRsi
   */
  intradayRsi: {
    methodKind: "unary";
    input: typeof IntradayRsiRequestSchema;
    output: typeof IntradayRsiResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_rsi, 0);

