// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>Moving Average Convergence/Divergence Oscillator</i> was developed by Gerald Appel and represents the difference between two moving averages of different lengths.
// <br>As its name implies, MACD is all about convergence and divergence of the two moving averages. MACD oscilaltes around the zero line as follows:
// <br>- positive values increase as the shorter moving average diverges further from the longer one
// <br>- negative values indicate that the shorter moving average is below the longer one
// <br><br>MACD is computed as follows: $$ MACD = short EMA - long EMA $$

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday_analytics/v1/intraday_macd.proto (package systemathics.apis.services.intraday_analytics.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";

/**
 * Describes the file systemathics/apis/services/intraday_analytics/v1/intraday_macd.proto.
 */
export const file_systemathics_apis_services_intraday_analytics_v1_intraday_macd = /*@__PURE__*/
  fileDesc("CkRzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheV9hbmFseXRpY3MvdjEvaW50cmFkYXlfbWFjZC5wcm90bxIwc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXlfYW5hbHl0aWNzLnYxIo0CChNJbnRyYWRheU1hY2RSZXF1ZXN0EkAKCmlkZW50aWZpZXIYASABKAsyLC5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5JZGVudGlmaWVyEjwKCHNhbXBsaW5nGAIgASgOMiouc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuU2FtcGxpbmcSRQoNZGF0ZV9pbnRlcnZhbBgDIAEoCzIuLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLkRhdGVJbnRlcnZhbBIMCgRsb25nGAQgASgFEg0KBXNob3J0GAUgASgFEhIKCmFkanVzdG1lbnQYBiABKAgiaAoUSW50cmFkYXlNYWNkUmVzcG9uc2USUAoEZGF0YRgBIAMoCzJCLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5X2FuYWx5dGljcy52MS5JbnRyYWRheU1hY2REYXRhInwKEEludHJhZGF5TWFjZERhdGESLgoKdGltZV9zdGFtcBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDQoFdmFsdWUYAiABKAESDAoEbWFjZBgDIAEoARINCgVzaG9ydBgEIAEoARIMCgRsb25nGAUgASgBMtABChNJbnRyYWRheU1hY2RTZXJ2aWNlErgBCgxJbnRyYWRheU1hY2QSRS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheV9hbmFseXRpY3MudjEuSW50cmFkYXlNYWNkUmVxdWVzdBpGLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5X2FuYWx5dGljcy52MS5JbnRyYWRheU1hY2RSZXNwb25zZSIZgtPkkwITEhEvdjEvaW50cmFkYXkvbWFjZGIGcHJvdG8z", [file_google_api_annotations, file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayMacdRequest.
 * Use `create(IntradayMacdRequestSchema)` to create a new message.
 */
export const IntradayMacdRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_macd, 0);

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayMacdResponse.
 * Use `create(IntradayMacdResponseSchema)` to create a new message.
 */
export const IntradayMacdResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_macd, 1);

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayMacdData.
 * Use `create(IntradayMacdDataSchema)` to create a new message.
 */
export const IntradayMacdDataSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_macd, 2);

/**
 * Called to request intraday moving average convergence divergence data. 
 *
 * @generated from service systemathics.apis.services.intraday_analytics.v1.IntradayMacdService
 */
export const IntradayMacdService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_macd, 0);

