// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// SMA is formed by computing the average price of a security over a specific number of points. 
// <br>As its name implies, simple moving average is an average that moves. Old data is dropped and new data becomes available, causing the average to move along the time.
// <br><i>N-points SMA data point</i> is computed by adding up the last N period's trade prices and then dividing by N as follows: $$ SMA = \frac{\Sigma Close_n}{N} $$
// <br>Where:
// <br>- <i>Close n</i> is the close price of the <i>period n</i>
// <br>- <i>N</i> is the count of time periods

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/intraday_analytics/v1/intraday_sma.proto (package systemathics.apis.services.intraday_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/intraday_analytics/v1/intraday_sma.proto.
 */
export const file_systemathics_apis_services_intraday_analytics_v1_intraday_sma: GenFile = /*@__PURE__*/
  fileDesc("CkNzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheV9hbmFseXRpY3MvdjEvaW50cmFkYXlfc21hLnByb3RvEjBzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheV9hbmFseXRpY3MudjEi/wEKEkludHJhZGF5U21hUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchI8CghzYW1wbGluZxgCIAEoDjIqLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLlNhbXBsaW5nEkUKDWRhdGVfaW50ZXJ2YWwYAyABKAsyLi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5EYXRlSW50ZXJ2YWwSDgoGbGVuZ3RoGAQgASgFEhIKCmFkanVzdG1lbnQYBSABKAgiZgoTSW50cmFkYXlTbWFSZXNwb25zZRJPCgRkYXRhGAEgAygLMkEuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXlfYW5hbHl0aWNzLnYxLkludHJhZGF5U21hRGF0YSJ/Cg9JbnRyYWRheVNtYURhdGESLgoKdGltZV9zdGFtcBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDQoFdmFsdWUYAiABKAESLQoHYXZlcmFnZRgDIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5Eb3VibGVWYWx1ZTLLAQoSSW50cmFkYXlTbWFTZXJ2aWNlErQBCgtJbnRyYWRheVNtYRJELnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5X2FuYWx5dGljcy52MS5JbnRyYWRheVNtYVJlcXVlc3QaRS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheV9hbmFseXRpY3MudjEuSW50cmFkYXlTbWFSZXNwb25zZSIYgtPkkwISEhAvdjEvaW50cmFkYXkvc21hYgZwcm90bzM", [file_google_api_annotations, file_google_protobuf_timestamp, file_google_protobuf_wrappers, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * The required input to request the IntradaySmaService.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradaySmaRequest
 */
export type IntradaySmaRequest = Message<"systemathics.apis.services.intraday_analytics.v1.IntradaySmaRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Mandatory] The simple moving average window length (period : points number)
   *
   * @generated from field: int32 length = 4;
   */
  length: number;

  /**
   * [Optional] The corporate action adjustment (dividends and splits).
   * By default the value is set to false
   *
   * @generated from field: bool adjustment = 5;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradaySmaRequest.
 * Use `create(IntradaySmaRequestSchema)` to create a new message.
 */
export const IntradaySmaRequestSchema: GenMessage<IntradaySmaRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_sma, 0);

/**
 * Represents a intraday simple moving average response.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradaySmaResponse
 */
export type IntradaySmaResponse = Message<"systemathics.apis.services.intraday_analytics.v1.IntradaySmaResponse"> & {
  /**
   * The intraday simple moving averages: an array of IntradaySmaData objects
   *
   * @generated from field: repeated systemathics.apis.services.intraday_analytics.v1.IntradaySmaData data = 1;
   */
  data: IntradaySmaData[];
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradaySmaResponse.
 * Use `create(IntradaySmaResponseSchema)` to create a new message.
 */
export const IntradaySmaResponseSchema: GenMessage<IntradaySmaResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_sma, 1);

/**
 * Contains the intraday simple moving average data: date and value.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradaySmaData
 */
export type IntradaySmaData = Message<"systemathics.apis.services.intraday_analytics.v1.IntradaySmaData"> & {
  /**
   * Time stamp of the simple moving average : open time of the sampling interval
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * The data used to calculate the average of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * The simple moving average value of the day for the last n data points (length)
   *
   * @generated from field: google.protobuf.DoubleValue average = 3;
   */
  average?: number;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradaySmaData.
 * Use `create(IntradaySmaDataSchema)` to create a new message.
 */
export const IntradaySmaDataSchema: GenMessage<IntradaySmaData> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_sma, 2);

/**
 * Called to request intraday simple moving average data. 
 *
 * @generated from service systemathics.apis.services.intraday_analytics.v1.IntradaySmaService
 */
export const IntradaySmaService: GenService<{
  /**
   * Gets intraday simple moving average data
   *
   * @generated from rpc systemathics.apis.services.intraday_analytics.v1.IntradaySmaService.IntradaySma
   */
  intradaySma: {
    methodKind: "unary";
    input: typeof IntradaySmaRequestSchema;
    output: typeof IntradaySmaResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_sma, 0);

