// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// EMA reduces the lag by applying greater weight to recent data points.
// <br>The weighting applied to the most recent price depends on the number of points in the moving average; The smaller the point count is, the more weight is applied to the most recent price.
// <br><i>N-points EMA data point</i> is computed using the previous' EMA value and the weighting multiplier as follows: $$ EMA = (Close-EMAp)*k+EMAp $$ Where:
// <br>- <i>Close</i> is the close price
// <br>- <i>EMAp</i> is the previous point' EMA value; SMA is used as the EMAp in the first calculation
// <br>- <i>N</i> is the count of points
// <br>- <i>k = 2 / N+1</i> is the Weighting Multiplier

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday_analytics/v1/intraday_ema.proto (package systemathics.apis.services.intraday_analytics.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";

/**
 * Describes the file systemathics/apis/services/intraday_analytics/v1/intraday_ema.proto.
 */
export const file_systemathics_apis_services_intraday_analytics_v1_intraday_ema = /*@__PURE__*/
  fileDesc("CkNzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheV9hbmFseXRpY3MvdjEvaW50cmFkYXlfZW1hLnByb3RvEjBzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheV9hbmFseXRpY3MudjEi/wEKEkludHJhZGF5RW1hUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchI8CghzYW1wbGluZxgCIAEoDjIqLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLlNhbXBsaW5nEkUKDWRhdGVfaW50ZXJ2YWwYAyABKAsyLi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5EYXRlSW50ZXJ2YWwSDgoGbGVuZ3RoGAQgASgFEhIKCmFkanVzdG1lbnQYBSABKAgiZgoTSW50cmFkYXlFbWFSZXNwb25zZRJPCgRkYXRhGAEgAygLMkEuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXlfYW5hbHl0aWNzLnYxLkludHJhZGF5RW1hRGF0YSJhCg9JbnRyYWRheUVtYURhdGESLgoKdGltZV9zdGFtcBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDQoFdmFsdWUYAiABKAESDwoHYXZlcmFnZRgDIAEoATLLAQoSSW50cmFkYXlFbWFTZXJ2aWNlErQBCgtJbnRyYWRheUVtYRJELnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5X2FuYWx5dGljcy52MS5JbnRyYWRheUVtYVJlcXVlc3QaRS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheV9hbmFseXRpY3MudjEuSW50cmFkYXlFbWFSZXNwb25zZSIYgtPkkwISEhAvdjEvaW50cmFkYXkvZW1hYgZwcm90bzM", [file_google_api_annotations, file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayEmaRequest.
 * Use `create(IntradayEmaRequestSchema)` to create a new message.
 */
export const IntradayEmaRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_ema, 0);

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayEmaResponse.
 * Use `create(IntradayEmaResponseSchema)` to create a new message.
 */
export const IntradayEmaResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_ema, 1);

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayEmaData.
 * Use `create(IntradayEmaDataSchema)` to create a new message.
 */
export const IntradayEmaDataSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_ema, 2);

/**
 * Called to request intraday exponential moving average data. 
 *
 * @generated from service systemathics.apis.services.intraday_analytics.v1.IntradayEmaService
 */
export const IntradayEmaService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_ema, 0);

