// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// EMA reduces the lag by applying greater weight to recent data points.
// <br>The weighting applied to the most recent price depends on the number of points in the moving average; The smaller the point count is, the more weight is applied to the most recent price.
// <br><i>N-points EMA data point</i> is computed using the previous' EMA value and the weighting multiplier as follows: $$ EMA = (Close-EMAp)*k+EMAp $$ Where:
// <br>- <i>Close</i> is the close price
// <br>- <i>EMAp</i> is the previous point' EMA value; SMA is used as the EMAp in the first calculation
// <br>- <i>N</i> is the count of points
// <br>- <i>k = 2 / N+1</i> is the Weighting Multiplier

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/intraday_analytics/v1/intraday_ema.proto (package systemathics.apis.services.intraday_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/intraday_analytics/v1/intraday_ema.proto.
 */
export const file_systemathics_apis_services_intraday_analytics_v1_intraday_ema: GenFile = /*@__PURE__*/
  fileDesc("CkNzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheV9hbmFseXRpY3MvdjEvaW50cmFkYXlfZW1hLnByb3RvEjBzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheV9hbmFseXRpY3MudjEi/wEKEkludHJhZGF5RW1hUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchI8CghzYW1wbGluZxgCIAEoDjIqLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLlNhbXBsaW5nEkUKDWRhdGVfaW50ZXJ2YWwYAyABKAsyLi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5EYXRlSW50ZXJ2YWwSDgoGbGVuZ3RoGAQgASgFEhIKCmFkanVzdG1lbnQYBSABKAgiZgoTSW50cmFkYXlFbWFSZXNwb25zZRJPCgRkYXRhGAEgAygLMkEuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXlfYW5hbHl0aWNzLnYxLkludHJhZGF5RW1hRGF0YSJhCg9JbnRyYWRheUVtYURhdGESLgoKdGltZV9zdGFtcBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDQoFdmFsdWUYAiABKAESDwoHYXZlcmFnZRgDIAEoATLLAQoSSW50cmFkYXlFbWFTZXJ2aWNlErQBCgtJbnRyYWRheUVtYRJELnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5X2FuYWx5dGljcy52MS5JbnRyYWRheUVtYVJlcXVlc3QaRS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheV9hbmFseXRpY3MudjEuSW50cmFkYXlFbWFSZXNwb25zZSIYgtPkkwISEhAvdjEvaW50cmFkYXkvZW1hYgZwcm90bzM", [file_google_api_annotations, file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * The required input to request the IntradayEmaService.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayEmaRequest
 */
export type IntradayEmaRequest = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayEmaRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Mandatory] The exponential moving average window length (period : points number)
   *
   * @generated from field: int32 length = 4;
   */
  length: number;

  /**
   * [Optional] The corporate action adjustment (dividends and splits).
   * By default the value is set to false
   *
   * @generated from field: bool adjustment = 5;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayEmaRequest.
 * Use `create(IntradayEmaRequestSchema)` to create a new message.
 */
export const IntradayEmaRequestSchema: GenMessage<IntradayEmaRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_ema, 0);

/**
 * Represents a intraday exponential moving average response.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayEmaResponse
 */
export type IntradayEmaResponse = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayEmaResponse"> & {
  /**
   * The intraday exponential moving averages: an array of IntradayEmaData objects
   *
   * @generated from field: repeated systemathics.apis.services.intraday_analytics.v1.IntradayEmaData data = 1;
   */
  data: IntradayEmaData[];
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayEmaResponse.
 * Use `create(IntradayEmaResponseSchema)` to create a new message.
 */
export const IntradayEmaResponseSchema: GenMessage<IntradayEmaResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_ema, 1);

/**
 * Contains the intraday exponential moving average data: date and value.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayEmaData
 */
export type IntradayEmaData = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayEmaData"> & {
  /**
   * Time stamp of the exponential moving average : open time of the sampling interval
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * The data used to calculate the average of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * The exponential moving average value of the day
   *
   * @generated from field: double average = 3;
   */
  average: number;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayEmaData.
 * Use `create(IntradayEmaDataSchema)` to create a new message.
 */
export const IntradayEmaDataSchema: GenMessage<IntradayEmaData> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_ema, 2);

/**
 * Called to request intraday exponential moving average data. 
 *
 * @generated from service systemathics.apis.services.intraday_analytics.v1.IntradayEmaService
 */
export const IntradayEmaService: GenService<{
  /**
   * Gets intraday exponential moving average data
   *
   * @generated from rpc systemathics.apis.services.intraday_analytics.v1.IntradayEmaService.IntradayEma
   */
  intradayEma: {
    methodKind: "unary";
    input: typeof IntradayEmaRequestSchema;
    output: typeof IntradayEmaResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_ema, 0);

