// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Moving averages smooth the price movements by filtering out the "noise" caused by short-term price fluctuations. 
// <br>They also form the building blocks for a wide range of technical indicators. Computing moving averages over a defined number of time periods is useful to:
// <br>- identify the trend direction
// <br>- determine support and resistance levels
// <br>CMA is the average of all the data points.

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/intraday_analytics/v1/intraday_cma.proto (package systemathics.apis.services.intraday_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/intraday_analytics/v1/intraday_cma.proto.
 */
export const file_systemathics_apis_services_intraday_analytics_v1_intraday_cma: GenFile = /*@__PURE__*/
  fileDesc("CkNzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheV9hbmFseXRpY3MvdjEvaW50cmFkYXlfY21hLnByb3RvEjBzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheV9hbmFseXRpY3MudjEi7wEKEkludHJhZGF5Q21hUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchI8CghzYW1wbGluZxgCIAEoDjIqLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLlNhbXBsaW5nEkUKDWRhdGVfaW50ZXJ2YWwYAyABKAsyLi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5EYXRlSW50ZXJ2YWwSEgoKYWRqdXN0bWVudBgEIAEoCCJmChNJbnRyYWRheUNtYVJlc3BvbnNlEk8KBGRhdGEYASADKAsyQS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheV9hbmFseXRpY3MudjEuSW50cmFkYXlDbWFEYXRhImEKD0ludHJhZGF5Q21hRGF0YRIuCgp0aW1lX3N0YW1wGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBINCgV2YWx1ZRgCIAEoARIPCgdhdmVyYWdlGAMgASgBMrEBChJJbnRyYWRheUNtYVNlcnZpY2USmgEKC0ludHJhZGF5Q21hEkQuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXlfYW5hbHl0aWNzLnYxLkludHJhZGF5Q21hUmVxdWVzdBpFLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5X2FuYWx5dGljcy52MS5JbnRyYWRheUNtYVJlc3BvbnNlYgZwcm90bzM", [file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * The required input to request the IntradayCmaService.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayCmaRequest
 */
export type IntradayCmaRequest = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayCmaRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The corporate action adjustment (dividends and splits).
   * By default the value is set to false
   *
   * @generated from field: bool adjustment = 4;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayCmaRequest.
 * Use `create(IntradayCmaRequestSchema)` to create a new message.
 */
export const IntradayCmaRequestSchema: GenMessage<IntradayCmaRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_cma, 0);

/**
 * Represents a intraday cumulative moving average response.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayCmaResponse
 */
export type IntradayCmaResponse = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayCmaResponse"> & {
  /**
   * The intraday cumulative moving averages: an array of IntradayCmaData objects
   *
   * @generated from field: repeated systemathics.apis.services.intraday_analytics.v1.IntradayCmaData data = 1;
   */
  data: IntradayCmaData[];
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayCmaResponse.
 * Use `create(IntradayCmaResponseSchema)` to create a new message.
 */
export const IntradayCmaResponseSchema: GenMessage<IntradayCmaResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_cma, 1);

/**
 * Contains the intraday cumulative moving average data: date and value.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayCmaData
 */
export type IntradayCmaData = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayCmaData"> & {
  /**
   * Time stamp of the cumulative moving average : open time of the sampling interval
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * The data used to calculate the average of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * The cumulative moving average value of the day for all the data points
   *
   * @generated from field: double average = 3;
   */
  average: number;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayCmaData.
 * Use `create(IntradayCmaDataSchema)` to create a new message.
 */
export const IntradayCmaDataSchema: GenMessage<IntradayCmaData> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_cma, 2);

/**
 * Called to request intraday cumulative moving average data. 
 *
 * @generated from service systemathics.apis.services.intraday_analytics.v1.IntradayCmaService
 */
export const IntradayCmaService: GenService<{
  /**
   * Gets intraday cumulative moving average data
   *
   * @generated from rpc systemathics.apis.services.intraday_analytics.v1.IntradayCmaService.IntradayCma
   */
  intradayCma: {
    methodKind: "unary";
    input: typeof IntradayCmaRequestSchema;
    output: typeof IntradayCmaResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_cma, 0);

