// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <br>N-points volatility is computed as follows: $$ Volatility_N = \sqrt \frac{\sum_{i=1}^N(P_a - P_i)^2}{N}$$
// <br>Where:
// <br>- <i>$$P_a$$</i> is the average price of the N prices
// <br>- <i>$$P_i$$</i> is price i

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday_analytics/v1/intraday_volatility.proto (package systemathics.apis.services.intraday_analytics.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";

/**
 * Describes the file systemathics/apis/services/intraday_analytics/v1/intraday_volatility.proto.
 */
export const file_systemathics_apis_services_intraday_analytics_v1_intraday_volatility = /*@__PURE__*/
  fileDesc("CkpzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheV9hbmFseXRpY3MvdjEvaW50cmFkYXlfdm9sYXRpbGl0eS5wcm90bxIwc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXlfYW5hbHl0aWNzLnYxIvYBChlJbnRyYWRheVZvbGF0aWxpdHlSZXF1ZXN0EkAKCmlkZW50aWZpZXIYASABKAsyLC5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5JZGVudGlmaWVyEjwKCHNhbXBsaW5nGAIgASgOMiouc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuU2FtcGxpbmcSRQoNZGF0ZV9pbnRlcnZhbBgDIAEoCzIuLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLkRhdGVJbnRlcnZhbBISCgphZGp1c3RtZW50GAQgASgIIisKGkludHJhZGF5Vm9sYXRpbGl0eVJlc3BvbnNlEg0KBXZhbHVlGAEgASgBMu4BChlJbnRyYWRheVZvbGF0aWxpdHlTZXJ2aWNlEtABChJJbnRyYWRheVZvbGF0aWxpdHkSSy5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheV9hbmFseXRpY3MudjEuSW50cmFkYXlWb2xhdGlsaXR5UmVxdWVzdBpMLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5X2FuYWx5dGljcy52MS5JbnRyYWRheVZvbGF0aWxpdHlSZXNwb25zZSIfgtPkkwIZEhcvdjEvaW50cmFkYXkvdm9sYXRpbGl0eWIGcHJvdG8z", [file_google_api_annotations, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayVolatilityRequest.
 * Use `create(IntradayVolatilityRequestSchema)` to create a new message.
 */
export const IntradayVolatilityRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_volatility, 0);

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayVolatilityResponse.
 * Use `create(IntradayVolatilityResponseSchema)` to create a new message.
 */
export const IntradayVolatilityResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_volatility, 1);

/**
 * Called to request intraday volatility data. 
 *
 * @generated from service systemathics.apis.services.intraday_analytics.v1.IntradayVolatilityService
 */
export const IntradayVolatilityService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_analytics_v1_intraday_volatility, 0);

