// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>Moving Average Convergence/Divergence Oscillator</i> was developed by Gerald Appel and represents the difference between two moving averages of different lengths.
// <br>As its name implies, MACD is all about convergence and divergence of the two moving averages. MACD oscilaltes around the zero line as follows:
// <br>- positive values increase as the shorter moving average diverges further from the longer one
// <br>- negative values indicate that the shorter moving average is below the longer one
// <br><br>MACD is computed as follows: $$ MACD = short EMA - long EMA $$

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday_analytics/v1/intraday_macd.proto (package systemathics.apis.services.intraday_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file systemathics/apis/services/intraday_analytics/v1/intraday_macd.proto.
 */
export declare const file_systemathics_apis_services_intraday_analytics_v1_intraday_macd: GenFile;

/**
 * The required input to request the IntradayMacdService.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayMacdRequest
 */
export declare type IntradayMacdRequest = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayMacdRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Mandatory] The long EMA window length (period : points number)
   *
   * @generated from field: int32 long = 4;
   */
  long: number;

  /**
   * [Mandatory] The short EMA window length (period : points number)
   *
   * @generated from field: int32 short = 5;
   */
  short: number;

  /**
   * [Optional] The corporate action adjustment (dividends and splits).
   * By default the value is set to false
   *
   * @generated from field: bool adjustment = 6;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayMacdRequest.
 * Use `create(IntradayMacdRequestSchema)` to create a new message.
 */
export declare const IntradayMacdRequestSchema: GenMessage<IntradayMacdRequest>;

/**
 * Represents a intraday moving average convergence divergence response.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayMacdResponse
 */
export declare type IntradayMacdResponse = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayMacdResponse"> & {
  /**
   * The intraday moving average convergence/divergence: an array of IntradayMacdData objects
   *
   * @generated from field: repeated systemathics.apis.services.intraday_analytics.v1.IntradayMacdData data = 1;
   */
  data: IntradayMacdData[];
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayMacdResponse.
 * Use `create(IntradayMacdResponseSchema)` to create a new message.
 */
export declare const IntradayMacdResponseSchema: GenMessage<IntradayMacdResponse>;

/**
 * Contains the intraday moving average convergence/divergence data: date and value.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayMacdData
 */
export declare type IntradayMacdData = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayMacdData"> & {
  /**
   * Time stamp of the moving average convergence/divergence : open time of the sampling interval
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * The data used to calculate the average convergence/divergence of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * The moving average convergence/divergence value of the day
   *
   * @generated from field: double macd = 3;
   */
  macd: number;

  /**
   * The short exponential moving average value of the day
   *
   * @generated from field: double short = 4;
   */
  short: number;

  /**
   * The long exponential moving average value of the day
   *
   * @generated from field: double long = 5;
   */
  long: number;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayMacdData.
 * Use `create(IntradayMacdDataSchema)` to create a new message.
 */
export declare const IntradayMacdDataSchema: GenMessage<IntradayMacdData>;

/**
 * Called to request intraday moving average convergence divergence data. 
 *
 * @generated from service systemathics.apis.services.intraday_analytics.v1.IntradayMacdService
 */
export declare const IntradayMacdService: GenService<{
  /**
   * Gets intraday moving average convergence divergence data
   *
   * @generated from rpc systemathics.apis.services.intraday_analytics.v1.IntradayMacdService.IntradayMacd
   */
  intradayMacd: {
    methodKind: "unary";
    input: typeof IntradayMacdRequestSchema;
    output: typeof IntradayMacdResponseSchema;
  },
}>;

