// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// SMA is formed by computing the average price of a security over a specific number of points. 
// <br>As its name implies, simple moving average is an average that moves. Old data is dropped and new data becomes available, causing the average to move along the time.
// <br><i>N-points SMA data point</i> is computed by adding up the last N period's trade prices and then dividing by N as follows: $$ SMA = \frac{\Sigma Close_n}{N} $$
// <br>Where:
// <br>- <i>Close n</i> is the close price of the <i>period n</i>
// <br>- <i>N</i> is the count of time periods

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday_analytics/v1/intraday_sma.proto (package systemathics.apis.services.intraday_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file systemathics/apis/services/intraday_analytics/v1/intraday_sma.proto.
 */
export declare const file_systemathics_apis_services_intraday_analytics_v1_intraday_sma: GenFile;

/**
 * The required input to request the IntradaySmaService.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradaySmaRequest
 */
export declare type IntradaySmaRequest = Message<"systemathics.apis.services.intraday_analytics.v1.IntradaySmaRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Mandatory] The simple moving average window length (period : points number)
   *
   * @generated from field: int32 length = 4;
   */
  length: number;

  /**
   * [Optional] The corporate action adjustment (dividends and splits).
   * By default the value is set to false
   *
   * @generated from field: bool adjustment = 5;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradaySmaRequest.
 * Use `create(IntradaySmaRequestSchema)` to create a new message.
 */
export declare const IntradaySmaRequestSchema: GenMessage<IntradaySmaRequest>;

/**
 * Represents a intraday simple moving average response.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradaySmaResponse
 */
export declare type IntradaySmaResponse = Message<"systemathics.apis.services.intraday_analytics.v1.IntradaySmaResponse"> & {
  /**
   * The intraday simple moving averages: an array of IntradaySmaData objects
   *
   * @generated from field: repeated systemathics.apis.services.intraday_analytics.v1.IntradaySmaData data = 1;
   */
  data: IntradaySmaData[];
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradaySmaResponse.
 * Use `create(IntradaySmaResponseSchema)` to create a new message.
 */
export declare const IntradaySmaResponseSchema: GenMessage<IntradaySmaResponse>;

/**
 * Contains the intraday simple moving average data: date and value.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradaySmaData
 */
export declare type IntradaySmaData = Message<"systemathics.apis.services.intraday_analytics.v1.IntradaySmaData"> & {
  /**
   * Time stamp of the simple moving average : open time of the sampling interval
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * The data used to calculate the average of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * The simple moving average value of the day for the last n data points (length)
   *
   * @generated from field: google.protobuf.DoubleValue average = 3;
   */
  average?: number;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradaySmaData.
 * Use `create(IntradaySmaDataSchema)` to create a new message.
 */
export declare const IntradaySmaDataSchema: GenMessage<IntradaySmaData>;

/**
 * Called to request intraday simple moving average data. 
 *
 * @generated from service systemathics.apis.services.intraday_analytics.v1.IntradaySmaService
 */
export declare const IntradaySmaService: GenService<{
  /**
   * Gets intraday simple moving average data
   *
   * @generated from rpc systemathics.apis.services.intraday_analytics.v1.IntradaySmaService.IntradaySma
   */
  intradaySma: {
    methodKind: "unary";
    input: typeof IntradaySmaRequestSchema;
    output: typeof IntradaySmaResponseSchema;
  },
}>;

