// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Bollinger bands were created by John Bollinger, they are envelopes and plotted around the moving average. 
// <br> The width of the bands is based on the standard deviaton of the closing prices from a moving average as follows:
// <br><i>- Middle band = n-period moving average</i>
// <br><i>- Upper band = Middle band + (k * n-period standard deviation)</i>
// <br><i>- Lower band = Middle band - (k * n-period standard deviation)</i>
// <br><i> Where n is the number of periods and k is factor to apply to the standard deviation value, k=2 as default value.</i>

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday_analytics/v1/intraday_bollinger.proto (package systemathics.apis.services.intraday_analytics.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file systemathics/apis/services/intraday_analytics/v1/intraday_bollinger.proto.
 */
export declare const file_systemathics_apis_services_intraday_analytics_v1_intraday_bollinger: GenFile;

/**
 * The required input to request the IntradayBollingerService.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayBollingerRequest
 */
export declare type IntradayBollingerRequest = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayBollingerRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Mandatory] The simple moving average window length (period: data points number)
   *
   * @generated from field: int32 length = 4;
   */
  length: number;

  /**
   * [Mandatory] The standard deviation window length
   *
   * @generated from field: double deviation = 5;
   */
  deviation: number;

  /**
   * [Optional] The corporate action adjustment (dividends and splits).
   * By default the value is set to false
   *
   * @generated from field: bool adjustment = 6;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayBollingerRequest.
 * Use `create(IntradayBollingerRequestSchema)` to create a new message.
 */
export declare const IntradayBollingerRequestSchema: GenMessage<IntradayBollingerRequest>;

/**
 * The intraday bars response contains an array of Bollinger bands.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayBollingerResponse
 */
export declare type IntradayBollingerResponse = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayBollingerResponse"> & {
  /**
   * The intraday Bollinger bands: an array of IntradayBollingerData objects
   *
   * @generated from field: repeated systemathics.apis.services.intraday_analytics.v1.IntradayBollingerData data = 1;
   */
  data: IntradayBollingerData[];
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayBollingerResponse.
 * Use `create(IntradayBollingerResponseSchema)` to create a new message.
 */
export declare const IntradayBollingerResponseSchema: GenMessage<IntradayBollingerResponse>;

/**
 * Contains the intraday Bollinger bands data: date, lower, middle and upper.
 *
 * @generated from message systemathics.apis.services.intraday_analytics.v1.IntradayBollingerData
 */
export declare type IntradayBollingerData = Message<"systemathics.apis.services.intraday_analytics.v1.IntradayBollingerData"> & {
  /**
   * Time stamp of Bollinger bands : open time of the sampling interval
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * The data used to calculate the Bollinger bands of the day
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * Bollinger lower band value of the day
   * <br><i>Lower band = Middle band - (k * n-period standard deviation)</i>
   *
   * @generated from field: google.protobuf.DoubleValue lower = 3;
   */
  lower?: number;

  /**
   * Bollinger upper band value of the day
   * <br><i>Upper band = Middle band + (k * n-period standard deviation)</i>
   *
   * @generated from field: google.protobuf.DoubleValue upper = 4;
   */
  upper?: number;

  /**
   * Bollinger middle band value of the day
   * <br><i>Middle band = n-period moving average</i>
   *
   * @generated from field: google.protobuf.DoubleValue middle = 5;
   */
  middle?: number;
};

/**
 * Describes the message systemathics.apis.services.intraday_analytics.v1.IntradayBollingerData.
 * Use `create(IntradayBollingerDataSchema)` to create a new message.
 */
export declare const IntradayBollingerDataSchema: GenMessage<IntradayBollingerData>;

/**
 * Called to request intraday Bollinger bands data. 
 *
 * @generated from service systemathics.apis.services.intraday_analytics.v1.IntradayBollingerService
 */
export declare const IntradayBollingerService: GenService<{
  /**
   * Gets intraday Bollinger bands data
   *
   * @generated from rpc systemathics.apis.services.intraday_analytics.v1.IntradayBollingerService.IntradayBollinger
   */
  intradayBollinger: {
    methodKind: "unary";
    input: typeof IntradayBollingerRequestSchema;
    output: typeof IntradayBollingerResponseSchema;
  },
}>;

