// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This service provides access to an intraday bars market data service,
// enabling users to retrieve historical bar data for various financial instruments.
// Intraday bars represent aggregated price and volume information over discrete time intervals,
// such as minutes or hours. This service facilitates comprehensive intraday trading analysis
// by offering granularity in market movements, allowing users to derive insights from the
// open, high, low, and close prices within specified time periods.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v1/intraday_bars.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_bars.proto.
 */
export const file_systemathics_apis_services_intraday_v1_intraday_bars = /*@__PURE__*/
  fileDesc("CjpzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheS92MS9pbnRyYWRheV9iYXJzLnByb3RvEiZzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MSLwAQoTSW50cmFkYXlCYXJzUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchI8CghzYW1wbGluZxgCIAEoDjIqLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLlNhbXBsaW5nEkUKDWRhdGVfaW50ZXJ2YWwYAyABKAsyLi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5EYXRlSW50ZXJ2YWwSEgoKYWRqdXN0bWVudBgEIAEoCCJZChRJbnRyYWRheUJhcnNSZXNwb25zZRJBCgRkYXRhGAEgAygLMjMuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXkudjEuSW50cmFkYXlCYXIisQEKC0ludHJhZGF5QmFyEi4KCnRpbWVfc3RhbXAYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEgwKBG9wZW4YAiABKAESDAoEaGlnaBgDIAEoARILCgNsb3cYBCABKAESDQoFY2xvc2UYBSABKAESDgoGdm9sdW1lGAYgASgBEg0KBWNvdW50GAcgASgFEgwKBHZ3YXAYCCABKAESDQoFc2NvcmUYCSABKAEy4gIKE0ludHJhZGF5QmFyc1NlcnZpY2USpAEKDEludHJhZGF5QmFycxI7LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxLkludHJhZGF5QmFyc1JlcXVlc3QaPC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MS5JbnRyYWRheUJhcnNSZXNwb25zZSIZgtPkkwITEhEvdjEvaW50cmFkYXkvYmFycxKjAQoSSW50cmFkYXlCYXJzU3RyZWFtEjsuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXkudjEuSW50cmFkYXlCYXJzUmVxdWVzdBozLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxLkludHJhZGF5QmFyIhmC0+STAhMSES92MS9pbnRyYWRheS9iYXJzMAFiBnByb3RvMw", [file_google_api_annotations, file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayBarsRequest.
 * Use `create(IntradayBarsRequestSchema)` to create a new message.
 */
export const IntradayBarsRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_bars, 0);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayBarsResponse.
 * Use `create(IntradayBarsResponseSchema)` to create a new message.
 */
export const IntradayBarsResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_bars, 1);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayBar.
 * Use `create(IntradayBarSchema)` to create a new message.
 */
export const IntradayBarSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_bars, 2);

/**
 * Called to request intraday bars data. 
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradayBarsService
 */
export const IntradayBarsService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_v1_intraday_bars, 0);

