// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This service provides access to an intraday bars market data service,
// enabling users to retrieve historical bar data for various financial instruments.
// Intraday bars represent aggregated price and volume information over discrete time intervals,
// such as minutes or hours. This service facilitates comprehensive intraday trading analysis
// by offering granularity in market movements, allowing users to derive insights from the
// open, high, low, and close prices within specified time periods.

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/intraday/v1/intraday_bars.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_bars.proto.
 */
export const file_systemathics_apis_services_intraday_v1_intraday_bars: GenFile = /*@__PURE__*/
  fileDesc("CjpzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheS92MS9pbnRyYWRheV9iYXJzLnByb3RvEiZzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MSLwAQoTSW50cmFkYXlCYXJzUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchI8CghzYW1wbGluZxgCIAEoDjIqLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLlNhbXBsaW5nEkUKDWRhdGVfaW50ZXJ2YWwYAyABKAsyLi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5EYXRlSW50ZXJ2YWwSEgoKYWRqdXN0bWVudBgEIAEoCCJZChRJbnRyYWRheUJhcnNSZXNwb25zZRJBCgRkYXRhGAEgAygLMjMuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXkudjEuSW50cmFkYXlCYXIisQEKC0ludHJhZGF5QmFyEi4KCnRpbWVfc3RhbXAYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEgwKBG9wZW4YAiABKAESDAoEaGlnaBgDIAEoARILCgNsb3cYBCABKAESDQoFY2xvc2UYBSABKAESDgoGdm9sdW1lGAYgASgBEg0KBWNvdW50GAcgASgFEgwKBHZ3YXAYCCABKAESDQoFc2NvcmUYCSABKAEyvAEKE0ludHJhZGF5QmFyc1NlcnZpY2USpAEKDEludHJhZGF5QmFycxI7LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxLkludHJhZGF5QmFyc1JlcXVlc3QaPC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MS5JbnRyYWRheUJhcnNSZXNwb25zZSIZgtPkkwITEhEvdjEvaW50cmFkYXkvYmFyc2IGcHJvdG8z", [file_google_api_annotations, file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * The required input to request the IntradayBarsService.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayBarsRequest
 */
export type IntradayBarsRequest = Message<"systemathics.apis.services.intraday.v1.IntradayBarsRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The corporate action adjustment (dividends and splits).
   * By default the value is set to false
   *
   * @generated from field: bool adjustment = 4;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayBarsRequest.
 * Use `create(IntradayBarsRequestSchema)` to create a new message.
 */
export const IntradayBarsRequestSchema: GenMessage<IntradayBarsRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_bars, 0);

/**
 * The intraday bars response contains an array of intraday bars.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayBarsResponse
 */
export type IntradayBarsResponse = Message<"systemathics.apis.services.intraday.v1.IntradayBarsResponse"> & {
  /**
   * The intraday bars: an array of IntradayBar objects
   *
   * @generated from field: repeated systemathics.apis.services.intraday.v1.IntradayBar data = 1;
   */
  data: IntradayBar[];
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayBarsResponse.
 * Use `create(IntradayBarsResponseSchema)` to create a new message.
 */
export const IntradayBarsResponseSchema: GenMessage<IntradayBarsResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_bars, 1);

/**
 * Contains the intraday bar's data: date, open, high, low, close, volume, count, vwap and score.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayBar
 */
export type IntradayBar = Message<"systemathics.apis.services.intraday.v1.IntradayBar"> & {
  /**
   * UTC time stamp of the intraday bar : open time of the sampling interval
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * Open price of the sampling period
   *
   * @generated from field: double open = 2;
   */
  open: number;

  /**
   * Highest price of the sampling period
   *
   * @generated from field: double high = 3;
   */
  high: number;

  /**
   * Lowest price of the sampling period
   *
   * @generated from field: double low = 4;
   */
  low: number;

  /**
   * Close price of the sampling period
   *
   * @generated from field: double close = 5;
   */
  close: number;

  /**
   * Total traded volume of the sampling period
   *
   * @generated from field: double volume = 6;
   */
  volume: number;

  /**
   * Tick count of the sampling period
   *
   * @generated from field: int32 count = 7;
   */
  count: number;

  /**
   * Volume weighted average price of the sampling period
   *
   * @generated from field: double vwap = 8;
   */
  vwap: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 9;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayBar.
 * Use `create(IntradayBarSchema)` to create a new message.
 */
export const IntradayBarSchema: GenMessage<IntradayBar> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_bars, 2);

/**
 * Called to request intraday bars data. 
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradayBarsService
 */
export const IntradayBarsService: GenService<{
  /**
   * Gets intraday historical data: date, open, high, low, close and volume
   *
   * @generated from rpc systemathics.apis.services.intraday.v1.IntradayBarsService.IntradayBars
   */
  intradayBars: {
    methodKind: "unary";
    input: typeof IntradayBarsRequestSchema;
    output: typeof IntradayBarsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_v1_intraday_bars, 0);

