// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This service provides access to an intraday marketdata market data service,
// enabling users to retrieve historical market data for various financial instruments.
// MarketData represents a comprehensive aggregation of all pertinent market information, 
// encompassing various data points such as bar data, best limit data, Greeks, and more.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v1/intraday_market_data.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { TimeInterval } from "../../../type/shared/v1/time_interval_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_market_data.proto.
 */
export declare const file_systemathics_apis_services_intraday_v1_intraday_market_data: GenFile;

/**
 * The required input to request the IntradayMarketDataService.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayMarketDataRequest
 */
export declare type IntradayMarketDataRequest = Message<"systemathics.apis.services.intraday.v1.IntradayMarketDataRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If missing, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.TimeInterval time_interval = 4;
   */
  timeInterval?: TimeInterval;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayMarketDataRequest.
 * Use `create(IntradayMarketDataRequestSchema)` to create a new message.
 */
export declare const IntradayMarketDataRequestSchema: GenMessage<IntradayMarketDataRequest>;

/**
 * The intraday marketdata response contains an array of intraday marketdata.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayMarketDataResponse
 */
export declare type IntradayMarketDataResponse = Message<"systemathics.apis.services.intraday.v1.IntradayMarketDataResponse"> & {
  /**
   * The intraday marketdata: an array of IntradayMarketData objects
   *
   * @generated from field: repeated systemathics.apis.services.intraday.v1.IntradayMarketData data = 1;
   */
  data: IntradayMarketData[];
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayMarketDataResponse.
 * Use `create(IntradayMarketDataResponseSchema)` to create a new message.
 */
export declare const IntradayMarketDataResponseSchema: GenMessage<IntradayMarketDataResponse>;

/**
 * Contains the intraday market data information.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayMarketData
 */
export declare type IntradayMarketData = Message<"systemathics.apis.services.intraday.v1.IntradayMarketData"> & {
  /**
   * UTC time stamp of the intraday market data
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * Open price of the sampling period
   *
   * @generated from field: double open = 2;
   */
  open: number;

  /**
   * Highest price of the sampling period
   *
   * @generated from field: double high = 3;
   */
  high: number;

  /**
   * Lowest price of the sampling period
   *
   * @generated from field: double low = 4;
   */
  low: number;

  /**
   * Close price of the sampling period
   *
   * @generated from field: double close = 5;
   */
  close: number;

  /**
   * Total traded volume of the sampling period
   *
   * @generated from field: double volume = 6;
   */
  volume: number;

  /**
   * The best bid price of the sampling period
   *
   * @generated from field: double bid_price = 7;
   */
  bidPrice: number;

  /**
   * The best bid size of the sampling period
   *
   * @generated from field: double bid_size = 8;
   */
  bidSize: number;

  /**
   * The best ask price of the sampling period
   *
   * @generated from field: double ask_price = 9;
   */
  askPrice: number;

  /**
   * The best ask size of the sampling period
   *
   * @generated from field: double ask_size = 10;
   */
  askSize: number;

  /**
   * Measures the sensitivity of an option's theoretical value to a change in the price of the underlying asset.
   * <br>It indicates the expected change in the option price for a one-point change in the underlying asset. 
   * <br>For example, if an option has a delta of 0.7, it suggests that the option's price will increase by $0.70 for every $1 increase in the underlying asset.
   *
   * @generated from field: double delta = 11;
   */
  delta: number;

  /**
   * Measeure sthe rate of change in the delta for each one-point increase in the underlying asset.
   * <br>It measures how much the delta of an option will change as the price of the underlying asset changes. 
   * <br>Gamma is particularly important for assessing how delta might change as the underlying asset's price fluctuates.
   *
   * @generated from field: double gamma = 12;
   */
  gamma: number;

  /**
   * A measure of the time decay on an option, the amount that an option willl lose each day due to the passage of time.
   * <br>It represents the change in the option price for a one-day decrease in the time to expiration. 
   * <br>Theta is often referred to as time decay. As the expiration date approaches, the time value of an option tends to decrease, and theta quantifies that decay.
   *
   * @generated from field: double theta = 13;
   */
  theta: number;

  /**
   * Measures the sensitivity of the price of an option to changes in implied volatility. 
   * <br>Implied volatility reflects the market's expectations for future price fluctuations. 
   * <br>Vega indicates how much the option price is expected to change for a one-percentage-point change in implied volatility.
   *
   * @generated from field: double vega = 14;
   */
  vega: number;

  /**
   * The rate at which the price of a derivative changes relative to a change in the risk-free rate of interest. 
   * <br>It represents the change in the option price for a one-percentage-point change in interest rates. 
   * <br>Rho is more relevant for options with longer time to expiration.
   *
   * @generated from field: double rho = 15;
   */
  rho: number;

  /**
   * ImpliedVolatility value of the sampling period
   *
   * @generated from field: double implied_volatility = 16;
   */
  impliedVolatility: number;

  /**
   * OpenInterest value of the sampling period
   *
   * @generated from field: double open_interest = 17;
   */
  openInterest: number;

  /**
   * Underlying value of the sampling period
   *
   * @generated from field: double underlying = 18;
   */
  underlying: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 19;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayMarketData.
 * Use `create(IntradayMarketDataSchema)` to create a new message.
 */
export declare const IntradayMarketDataSchema: GenMessage<IntradayMarketData>;

/**
 * Called to request intraday marketdata data. 
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradayMarketDataService
 */
export declare const IntradayMarketDataService: GenService<{
  /**
   * Gets intraday historical data
   *
   * @generated from rpc systemathics.apis.services.intraday.v1.IntradayMarketDataService.IntradayMarketData
   */
  intradayMarketData: {
    methodKind: "unary";
    input: typeof IntradayMarketDataRequestSchema;
    output: typeof IntradayMarketDataResponseSchema;
  },
}>;

