// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The Open interest</i> is the total number of contracts (futures or options) that are currently held by market participants and have not been offset by an opposite transaction (i.e., by closing the position).

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v1/intraday_open_interest.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_open_interest.proto.
 */
export declare const file_systemathics_apis_services_intraday_v1_intraday_open_interest: GenFile;

/**
 * The required input to request the IntradayOpenInterestsService
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayOpenInterestsRequest
 */
export declare type IntradayOpenInterestsRequest = Message<"systemathics.apis.services.intraday.v1.IntradayOpenInterestsRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayOpenInterestsRequest.
 * Use `create(IntradayOpenInterestsRequestSchema)` to create a new message.
 */
export declare const IntradayOpenInterestsRequestSchema: GenMessage<IntradayOpenInterestsRequest>;

/**
 * Represents a intraday OpenInterests response.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayOpenInterestsResponse
 */
export declare type IntradayOpenInterestsResponse = Message<"systemathics.apis.services.intraday.v1.IntradayOpenInterestsResponse"> & {
  /**
   * The intraday openinterests: an array of IntradayOpenInterest objects
   *
   * @generated from field: repeated systemathics.apis.services.intraday.v1.IntradayOpenInterest data = 1;
   */
  data: IntradayOpenInterest[];
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayOpenInterestsResponse.
 * Use `create(IntradayOpenInterestsResponseSchema)` to create a new message.
 */
export declare const IntradayOpenInterestsResponseSchema: GenMessage<IntradayOpenInterestsResponse>;

/**
 * Contains the intraday openinterests data: date, openinterest value.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayOpenInterest
 */
export declare type IntradayOpenInterest = Message<"systemathics.apis.services.intraday.v1.IntradayOpenInterest"> & {
  /**
   * UTC time stamp of the intraday openinterest : open time of the sampling interval
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * OpenInterest value of the sampling period
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 3;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayOpenInterest.
 * Use `create(IntradayOpenInterestSchema)` to create a new message.
 */
export declare const IntradayOpenInterestSchema: GenMessage<IntradayOpenInterest>;

/**
 * Called to request intraday OpenInterest data. 
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradayOpenInterestsService
 */
export declare const IntradayOpenInterestsService: GenService<{
  /**
   * Gets intraday historical OpenInterests
   *
   * @generated from rpc systemathics.apis.services.intraday.v1.IntradayOpenInterestsService.IntradayOpenInterests
   */
  intradayOpenInterests: {
    methodKind: "unary";
    input: typeof IntradayOpenInterestsRequestSchema;
    output: typeof IntradayOpenInterestsResponseSchema;
  },
}>;

