// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The Open interest</i> is the total number of contracts (futures or options) that are currently held by market participants and have not been offset by an opposite transaction (i.e., by closing the position).

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v1/intraday_open_interest.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_time_interval } from "../../../type/shared/v1/time_interval_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_open_interest.proto.
 */
export const file_systemathics_apis_services_intraday_v1_intraday_open_interest = /*@__PURE__*/
  fileDesc("CkNzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheS92MS9pbnRyYWRheV9vcGVuX2ludGVyZXN0LnByb3RvEiZzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MSKsAgocSW50cmFkYXlPcGVuSW50ZXJlc3RzUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchI8CghzYW1wbGluZxgCIAEoDjIqLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLlNhbXBsaW5nEkUKDWRhdGVfaW50ZXJ2YWwYAyABKAsyLi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5EYXRlSW50ZXJ2YWwSRQoNdGltZV9pbnRlcnZhbBgEIAEoCzIuLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLlRpbWVJbnRlcnZhbCJrCh1JbnRyYWRheU9wZW5JbnRlcmVzdHNSZXNwb25zZRJKCgRkYXRhGAEgAygLMjwuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXkudjEuSW50cmFkYXlPcGVuSW50ZXJlc3QiZAoUSW50cmFkYXlPcGVuSW50ZXJlc3QSLgoKdGltZV9zdGFtcBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDQoFdmFsdWUYAiABKAESDQoFc2NvcmUYAyABKAEy6QEKHEludHJhZGF5T3BlbkludGVyZXN0c1NlcnZpY2USyAEKFUludHJhZGF5T3BlbkludGVyZXN0cxJELnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxLkludHJhZGF5T3BlbkludGVyZXN0c1JlcXVlc3QaRS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MS5JbnRyYWRheU9wZW5JbnRlcmVzdHNSZXNwb25zZSIigtPkkwIcEhovdjEvaW50cmFkYXkvb3BlbmludGVyZXN0c2IGcHJvdG8z", [file_google_api_annotations, file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_time_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayOpenInterestsRequest.
 * Use `create(IntradayOpenInterestsRequestSchema)` to create a new message.
 */
export const IntradayOpenInterestsRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_open_interest, 0);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayOpenInterestsResponse.
 * Use `create(IntradayOpenInterestsResponseSchema)` to create a new message.
 */
export const IntradayOpenInterestsResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_open_interest, 1);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayOpenInterest.
 * Use `create(IntradayOpenInterestSchema)` to create a new message.
 */
export const IntradayOpenInterestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_open_interest, 2);

/**
 * Called to request intraday OpenInterest data. 
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradayOpenInterestsService
 */
export const IntradayOpenInterestsService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_v1_intraday_open_interest, 0);

