// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// The <i>Greeks</i> are a set of risk measures or sensitivities used in options trading to assess the various factors that can influence the price of an option.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v1/intraday_greeks.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { TimeInterval } from "../../../type/shared/v1/time_interval_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_greeks.proto.
 */
export declare const file_systemathics_apis_services_intraday_v1_intraday_greeks: GenFile;

/**
 * The required input to request the IntradayGreeksService.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayGreeksRequest
 */
export declare type IntradayGreeksRequest = Message<"systemathics.apis.services.intraday.v1.IntradayGreeksRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If missing, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.TimeInterval time_interval = 4;
   */
  timeInterval?: TimeInterval;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayGreeksRequest.
 * Use `create(IntradayGreeksRequestSchema)` to create a new message.
 */
export declare const IntradayGreeksRequestSchema: GenMessage<IntradayGreeksRequest>;

/**
 * The intraday greeks response contains an array of intraday greeks.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayGreeksResponse
 */
export declare type IntradayGreeksResponse = Message<"systemathics.apis.services.intraday.v1.IntradayGreeksResponse"> & {
  /**
   * The intraday greeks: an array of IntradayGreeks objects
   *
   * @generated from field: repeated systemathics.apis.services.intraday.v1.IntradayGreeks data = 1;
   */
  data: IntradayGreeks[];
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayGreeksResponse.
 * Use `create(IntradayGreeksResponseSchema)` to create a new message.
 */
export declare const IntradayGreeksResponseSchema: GenMessage<IntradayGreeksResponse>;

/**
 * Contains the intraday greeks data.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayGreeks
 */
export declare type IntradayGreeks = Message<"systemathics.apis.services.intraday.v1.IntradayGreeks"> & {
  /**
   * UTC time stamp of the intraday greeks
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * Measures the sensitivity of an option's theoretical value to a change in the price of the underlying asset.
   * <br>It indicates the expected change in the option price for a one-point change in the underlying asset. 
   * <br>For example, if an option has a delta of 0.7, it suggests that the option's price will increase by $0.70 for every $1 increase in the underlying asset.
   *
   * @generated from field: double delta = 2;
   */
  delta: number;

  /**
   * Measeure sthe rate of change in the delta for each one-point increase in the underlying asset.
   * <br>It measures how much the delta of an option will change as the price of the underlying asset changes. 
   * <br>Gamma is particularly important for assessing how delta might change as the underlying asset's price fluctuates.
   *
   * @generated from field: double gamma = 3;
   */
  gamma: number;

  /**
   * A measure of the time decay on an option, the amount that an option willl lose each day due to the passage of time.
   * <br>It represents the change in the option price for a one-day decrease in the time to expiration. 
   * <br>Theta is often referred to as time decay. As the expiration date approaches, the time value of an option tends to decrease, and theta quantifies that decay.
   *
   * @generated from field: double theta = 4;
   */
  theta: number;

  /**
   * Measures the sensitivity of the price of an option to changes in implied volatility. 
   * <br>Implied volatility reflects the market's expectations for future price fluctuations. 
   * <br>Vega indicates how much the option price is expected to change for a one-percentage-point change in implied volatility.
   *
   * @generated from field: double vega = 5;
   */
  vega: number;

  /**
   * The rate at which the price of a derivative changes relative to a change in the risk-free rate of interest. 
   * <br>It represents the change in the option price for a one-percentage-point change in interest rates. 
   * <br>Rho is more relevant for options with longer time to expiration.
   *
   * @generated from field: double rho = 6;
   */
  rho: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 7;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayGreeks.
 * Use `create(IntradayGreeksSchema)` to create a new message.
 */
export declare const IntradayGreeksSchema: GenMessage<IntradayGreeks>;

/**
 * Called to request intraday greeks data. 
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradayGreeksService
 */
export declare const IntradayGreeksService: GenService<{
  /**
   * Gets intraday historical greeks data.
   *
   * @generated from rpc systemathics.apis.services.intraday.v1.IntradayGreeksService.IntradayGreeks
   */
  intradayGreeks: {
    methodKind: "unary";
    input: typeof IntradayGreeksRequestSchema;
    output: typeof IntradayGreeksResponseSchema;
  },
}>;

