// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Best limit data represent the highest bid and lowest ask prices in the market at any given time, providing valuable insights into the current state of supply and demand.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v1/intraday_best_limit.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_time_interval } from "../../../type/shared/v1/time_interval_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_best_limit.proto.
 */
export const file_systemathics_apis_services_intraday_v1_intraday_best_limit = /*@__PURE__*/
  fileDesc("CkBzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheS92MS9pbnRyYWRheV9iZXN0X2xpbWl0LnByb3RvEiZzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MSK9AgoZSW50cmFkYXlCZXN0TGltaXRzUmVxdWVzdBJACgppZGVudGlmaWVyGAEgASgLMiwuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuSWRlbnRpZmllchI8CghzYW1wbGluZxgCIAEoDjIqLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLlNhbXBsaW5nEkUKDWRhdGVfaW50ZXJ2YWwYAyABKAsyLi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5EYXRlSW50ZXJ2YWwSEgoKYWRqdXN0bWVudBgEIAEoCBJFCg10aW1lX2ludGVydmFsGAUgASgLMi4uc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuVGltZUludGVydmFsImUKGkludHJhZGF5QmVzdExpbWl0c1Jlc3BvbnNlEkcKBGRhdGEYASADKAsyOS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MS5JbnRyYWRheUJlc3RMaW1pdCKcAQoRSW50cmFkYXlCZXN0TGltaXQSLgoKdGltZV9zdGFtcBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASEQoJYmlkX3ByaWNlGAIgASgBEhAKCGJpZF9zaXplGAMgASgBEhEKCWFza19wcmljZRgEIAEoARIQCghhc2tfc2l6ZRgFIAEoARINCgVzY29yZRgGIAEoATLaAQoZSW50cmFkYXlCZXN0TGltaXRzU2VydmljZRK8AQoSSW50cmFkYXlCZXN0TGltaXRzEkEuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXkudjEuSW50cmFkYXlCZXN0TGltaXRzUmVxdWVzdBpCLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxLkludHJhZGF5QmVzdExpbWl0c1Jlc3BvbnNlIh+C0+STAhkSFy92MS9pbnRyYWRheS9iZXN0bGltaXRzYgZwcm90bzM", [file_google_api_annotations, file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_time_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayBestLimitsRequest.
 * Use `create(IntradayBestLimitsRequestSchema)` to create a new message.
 */
export const IntradayBestLimitsRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_best_limit, 0);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayBestLimitsResponse.
 * Use `create(IntradayBestLimitsResponseSchema)` to create a new message.
 */
export const IntradayBestLimitsResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_best_limit, 1);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayBestLimit.
 * Use `create(IntradayBestLimitSchema)` to create a new message.
 */
export const IntradayBestLimitSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_best_limit, 2);

/**
 * This service serves as a gateway to an intraday Best Limit market data service, allowing users to access historical data on the best limit order levels for various financial instruments. 
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradayBestLimitsService
 */
export const IntradayBestLimitsService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_v1_intraday_best_limit, 0);

