// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The settlement price </i>is the official price at which a financial instrument is settled at the end of a trading day.
//<br> The settlement refers to the process of transferring securities or funds to fulfill the terms of a trade.
//<br> In futures and options markets, the settlement price is often determined by a specific mechanism outlined by the exchange and may not necessarily be the same as the closing price.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v1/intraday_settlement.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_settlement.proto.
 */
export declare const file_systemathics_apis_services_intraday_v1_intraday_settlement: GenFile;

/**
 * The required input to request the IntradaySettlementsService
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradaySettlementsRequest
 */
export declare type IntradaySettlementsRequest = Message<"systemathics.apis.services.intraday.v1.IntradaySettlementsRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The corporate action adjustment (dividends and splits).
   * By default the value is set to false
   *
   * @generated from field: bool adjustment = 4;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradaySettlementsRequest.
 * Use `create(IntradaySettlementsRequestSchema)` to create a new message.
 */
export declare const IntradaySettlementsRequestSchema: GenMessage<IntradaySettlementsRequest>;

/**
 * Represents a intraday Settlements response.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradaySettlementsResponse
 */
export declare type IntradaySettlementsResponse = Message<"systemathics.apis.services.intraday.v1.IntradaySettlementsResponse"> & {
  /**
   * The intraday settlements: an array of IntradaySettlement objects
   *
   * @generated from field: repeated systemathics.apis.services.intraday.v1.IntradaySettlement data = 1;
   */
  data: IntradaySettlement[];
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradaySettlementsResponse.
 * Use `create(IntradaySettlementsResponseSchema)` to create a new message.
 */
export declare const IntradaySettlementsResponseSchema: GenMessage<IntradaySettlementsResponse>;

/**
 * Contains the intraday settlements data: date, settlement value and volume.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradaySettlement
 */
export declare type IntradaySettlement = Message<"systemathics.apis.services.intraday.v1.IntradaySettlement"> & {
  /**
   * UTC time stamp of the intraday settlement : open time of the sampling interval
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * Settlement value of the sampling period
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * Total traded volume of the sampling period
   *
   * @generated from field: double volume = 3;
   */
  volume: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 4;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradaySettlement.
 * Use `create(IntradaySettlementSchema)` to create a new message.
 */
export declare const IntradaySettlementSchema: GenMessage<IntradaySettlement>;

/**
 *  This service provides access to an intraday settlement market data, 
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradaySettlementsService
 */
export declare const IntradaySettlementsService: GenService<{
  /**
   * Gets intraday historical Settlements
   *
   * @generated from rpc systemathics.apis.services.intraday.v1.IntradaySettlementsService.IntradaySettlements
   */
  intradaySettlements: {
    methodKind: "unary";
    input: typeof IntradaySettlementsRequestSchema;
    output: typeof IntradaySettlementsResponseSchema;
  },
}>;

