// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The Volume Weighted Average Price</i> is similar to a moving average, except volume is included to weight the average price over a one trading day period.
// <br>It serves as a reference point for one trading day prices. Comparing current prices with the VWAP values enables to:
// <br>- mesure trading efficiency by comparing individual trades to VWAP
// <br>- highlight liquidity points as vwap reflects prices levels weighted by volume
// <br>- determine the market trend, etc.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v1/intraday_vwap.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { TimeInterval } from "../../../type/shared/v1/time_interval_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_vwap.proto.
 */
export declare const file_systemathics_apis_services_intraday_v1_intraday_vwap: GenFile;

/**
 * Represents a request object for intraday VWAP (Volume-Weighted Average Price) market data.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayVwapsRequest
 */
export declare type IntradayVwapsRequest = Message<"systemathics.apis.services.intraday.v1.IntradayVwapsRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The corporate action adjustment (dividends and splits).
   * By default the value is set to false
   *
   * @generated from field: bool adjustment = 4;
   */
  adjustment: boolean;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If missing, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.TimeInterval time_interval = 5;
   */
  timeInterval?: TimeInterval;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayVwapsRequest.
 * Use `create(IntradayVwapsRequestSchema)` to create a new message.
 */
export declare const IntradayVwapsRequestSchema: GenMessage<IntradayVwapsRequest>;

/**
 * Represents the response object for an intraday VWAP (Volume-Weighted Average Price) market data request.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayVwapsResponse
 */
export declare type IntradayVwapsResponse = Message<"systemathics.apis.services.intraday.v1.IntradayVwapsResponse"> & {
  /**
   * A time series of intraday VWAP (Volume-Weighted Average Price) market data.
   *
   * @generated from field: repeated systemathics.apis.services.intraday.v1.IntradayVwap data = 1;
   */
  data: IntradayVwap[];
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayVwapsResponse.
 * Use `create(IntradayVwapsResponseSchema)` to create a new message.
 */
export declare const IntradayVwapsResponseSchema: GenMessage<IntradayVwapsResponse>;

/**
 * Represents an individual data item for intraday VWAP (Volume-Weighted Average Price) market data.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayVwap
 */
export declare type IntradayVwap = Message<"systemathics.apis.services.intraday.v1.IntradayVwap"> & {
  /**
   * UTC time stamp of the intraday vwap : open time of the sampling interval
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * Vwap of the sampling period
   *
   * @generated from field: double price = 2;
   */
  price: number;

  /**
   * Total traded volume of the sampling period
   *
   * @generated from field: double volume = 3;
   */
  volume: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 4;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayVwap.
 * Use `create(IntradayVwapSchema)` to create a new message.
 */
export declare const IntradayVwapSchema: GenMessage<IntradayVwap>;

/**
 * This service provides access to an intraday VWAP (Volume-Weighted Average Price) market data,
 * allowing users to retrieve historical VWAP data for various financial instruments.
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradayVwapsService
 */
export declare const IntradayVwapsService: GenService<{
  /**
   * Gets intraday historical VWAPs
   *
   * @generated from rpc systemathics.apis.services.intraday.v1.IntradayVwapsService.IntradayVwaps
   */
  intradayVwaps: {
    methodKind: "unary";
    input: typeof IntradayVwapsRequestSchema;
    output: typeof IntradayVwapsResponseSchema;
  },
}>;

