// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The Volume Weighted Average Price</i> is similar to a moving average, except volume is included to weight the average price over a one trading day period.
// <br>It serves as a reference point for one trading day prices. Comparing current prices with the VWAP values enables to:
// <br>- mesure trading efficiency by comparing individual trades to VWAP
// <br>- highlight liquidity points as vwap reflects prices levels weighted by volume
// <br>- determine the market trend, etc.

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/intraday/v1/intraday_vwap.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_vwap.proto.
 */
export const file_systemathics_apis_services_intraday_v1_intraday_vwap: GenFile = /*@__PURE__*/
  fileDesc("CjpzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheS92MS9pbnRyYWRheV92d2FwLnByb3RvEiZzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MSLxAQoUSW50cmFkYXlWd2Fwc1JlcXVlc3QSQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISPAoIc2FtcGxpbmcYAiABKA4yKi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5TYW1wbGluZxJFCg1kYXRlX2ludGVydmFsGAMgASgLMi4uc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuRGF0ZUludGVydmFsEhIKCmFkanVzdG1lbnQYBCABKAgiWwoVSW50cmFkYXlWd2Fwc1Jlc3BvbnNlEkIKBGRhdGEYASADKAsyNC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MS5JbnRyYWRheVZ3YXAibAoMSW50cmFkYXlWd2FwEi4KCnRpbWVfc3RhbXAYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEg0KBXByaWNlGAIgASgBEg4KBnZvbHVtZRgDIAEoARINCgVzY29yZRgEIAEoATLBAQoUSW50cmFkYXlWd2Fwc1NlcnZpY2USqAEKDUludHJhZGF5VndhcHMSPC5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MS5JbnRyYWRheVZ3YXBzUmVxdWVzdBo9LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxLkludHJhZGF5VndhcHNSZXNwb25zZSIagtPkkwIUEhIvdjEvaW50cmFkYXkvdndhcHNiBnByb3RvMw", [file_google_api_annotations, file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * Represents a request object for intraday VWAP (Volume-Weighted Average Price) market data.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayVwapsRequest
 */
export type IntradayVwapsRequest = Message<"systemathics.apis.services.intraday.v1.IntradayVwapsRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type 
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The corporate action adjustment (dividends and splits).
   * By default the value is set to false
   *
   * @generated from field: bool adjustment = 4;
   */
  adjustment: boolean;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayVwapsRequest.
 * Use `create(IntradayVwapsRequestSchema)` to create a new message.
 */
export const IntradayVwapsRequestSchema: GenMessage<IntradayVwapsRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_vwap, 0);

/**
 * Represents the response object for an intraday VWAP (Volume-Weighted Average Price) market data request.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayVwapsResponse
 */
export type IntradayVwapsResponse = Message<"systemathics.apis.services.intraday.v1.IntradayVwapsResponse"> & {
  /**
   * A time series of intraday VWAP (Volume-Weighted Average Price) market data.
   *
   * @generated from field: repeated systemathics.apis.services.intraday.v1.IntradayVwap data = 1;
   */
  data: IntradayVwap[];
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayVwapsResponse.
 * Use `create(IntradayVwapsResponseSchema)` to create a new message.
 */
export const IntradayVwapsResponseSchema: GenMessage<IntradayVwapsResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_vwap, 1);

/**
 * Represents an individual data item for intraday VWAP (Volume-Weighted Average Price) market data.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayVwap
 */
export type IntradayVwap = Message<"systemathics.apis.services.intraday.v1.IntradayVwap"> & {
  /**
   * UTC time stamp of the intraday vwap : open time of the sampling interval
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * Vwap of the sampling period
   *
   * @generated from field: double price = 2;
   */
  price: number;

  /**
   * Total traded volume of the sampling period
   *
   * @generated from field: double volume = 3;
   */
  volume: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 4;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayVwap.
 * Use `create(IntradayVwapSchema)` to create a new message.
 */
export const IntradayVwapSchema: GenMessage<IntradayVwap> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_vwap, 2);

/**
 * This service provides access to an intraday VWAP (Volume-Weighted Average Price) market data,
 * allowing users to retrieve historical VWAP data for various financial instruments.
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradayVwapsService
 */
export const IntradayVwapsService: GenService<{
  /**
   * Gets intraday historical VWAPs
   *
   * @generated from rpc systemathics.apis.services.intraday.v1.IntradayVwapsService.IntradayVwaps
   */
  intradayVwaps: {
    methodKind: "unary";
    input: typeof IntradayVwapsRequestSchema;
    output: typeof IntradayVwapsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_v1_intraday_vwap, 0);

