// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The settlement price </i>is the official price at which a financial instrument is settled at the end of a trading day.
//<br> The settlement refers to the process of transferring securities or funds to fulfill the terms of a trade.
//<br> In futures and options markets, the settlement price is often determined by a specific mechanism outlined by the exchange and may not necessarily be the same as the closing price.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v1/intraday_settlement.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_time_interval } from "../../../type/shared/v1/time_interval_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_settlement.proto.
 */
export const file_systemathics_apis_services_intraday_v1_intraday_settlement = /*@__PURE__*/
  fileDesc("CkBzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheS92MS9pbnRyYWRheV9zZXR0bGVtZW50LnByb3RvEiZzeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MSK+AgoaSW50cmFkYXlTZXR0bGVtZW50c1JlcXVlc3QSQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISPAoIc2FtcGxpbmcYAiABKA4yKi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5TYW1wbGluZxJFCg1kYXRlX2ludGVydmFsGAMgASgLMi4uc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuRGF0ZUludGVydmFsEhIKCmFkanVzdG1lbnQYBCABKAgSRQoNdGltZV9pbnRlcnZhbBgFIAEoCzIuLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLlRpbWVJbnRlcnZhbCJnChtJbnRyYWRheVNldHRsZW1lbnRzUmVzcG9uc2USSAoEZGF0YRgBIAMoCzI6LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxLkludHJhZGF5U2V0dGxlbWVudCJyChJJbnRyYWRheVNldHRsZW1lbnQSLgoKdGltZV9zdGFtcBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDQoFdmFsdWUYAiABKAESDgoGdm9sdW1lGAMgASgBEg0KBXNjb3JlGAQgASgBMt8BChpJbnRyYWRheVNldHRsZW1lbnRzU2VydmljZRLAAQoTSW50cmFkYXlTZXR0bGVtZW50cxJCLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxLkludHJhZGF5U2V0dGxlbWVudHNSZXF1ZXN0GkMuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXkudjEuSW50cmFkYXlTZXR0bGVtZW50c1Jlc3BvbnNlIiCC0+STAhoSGC92MS9pbnRyYWRheS9zZXR0bGVtZW50c2IGcHJvdG8z", [file_google_api_annotations, file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_time_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradaySettlementsRequest.
 * Use `create(IntradaySettlementsRequestSchema)` to create a new message.
 */
export const IntradaySettlementsRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_settlement, 0);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradaySettlementsResponse.
 * Use `create(IntradaySettlementsResponseSchema)` to create a new message.
 */
export const IntradaySettlementsResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_settlement, 1);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradaySettlement.
 * Use `create(IntradaySettlementSchema)` to create a new message.
 */
export const IntradaySettlementSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_settlement, 2);

/**
 *  This service provides access to an intraday settlement market data, 
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradaySettlementsService
 */
export const IntradaySettlementsService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_v1_intraday_settlement, 0);

