// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// <i>The Implied Volatility</i> is the estimated volatility of the option strike over the period of the option.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v1/intraday_implied_volatility.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_time_interval } from "../../../type/shared/v1/time_interval_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_implied_volatility.proto.
 */
export const file_systemathics_apis_services_intraday_v1_intraday_implied_volatility = /*@__PURE__*/
  fileDesc("CkhzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheS92MS9pbnRyYWRheV9pbXBsaWVkX3ZvbGF0aWxpdHkucHJvdG8SJnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxIrICCiJJbnRyYWRheUltcGxpZWRWb2xhdGlsaXRpZXNSZXF1ZXN0EkAKCmlkZW50aWZpZXIYASABKAsyLC5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5JZGVudGlmaWVyEjwKCHNhbXBsaW5nGAIgASgOMiouc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuU2FtcGxpbmcSRQoNZGF0ZV9pbnRlcnZhbBgDIAEoCzIuLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLkRhdGVJbnRlcnZhbBJFCg10aW1lX2ludGVydmFsGAQgASgLMi4uc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuVGltZUludGVydmFsInYKI0ludHJhZGF5SW1wbGllZFZvbGF0aWxpdGllc1Jlc3BvbnNlEk8KBGRhdGEYASADKAsyQS5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MS5JbnRyYWRheUltcGxpZWRWb2xhdGlsaXR5ImkKGUludHJhZGF5SW1wbGllZFZvbGF0aWxpdHkSLgoKdGltZV9zdGFtcBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDQoFdmFsdWUYAiABKAESDQoFc2NvcmUYAyABKAEyhwIKIkludHJhZGF5SW1wbGllZFZvbGF0aWxpdGllc1NlcnZpY2US4AEKG0ludHJhZGF5SW1wbGllZFZvbGF0aWxpdGllcxJKLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxLkludHJhZGF5SW1wbGllZFZvbGF0aWxpdGllc1JlcXVlc3QaSy5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MS5JbnRyYWRheUltcGxpZWRWb2xhdGlsaXRpZXNSZXNwb25zZSIogtPkkwIiEiAvdjEvaW50cmFkYXkvaW1wbGllZHZvbGF0aWxpdGllc2IGcHJvdG8z", [file_google_api_annotations, file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_time_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayImpliedVolatilitiesRequest.
 * Use `create(IntradayImpliedVolatilitiesRequestSchema)` to create a new message.
 */
export const IntradayImpliedVolatilitiesRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_implied_volatility, 0);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayImpliedVolatilitiesResponse.
 * Use `create(IntradayImpliedVolatilitiesResponseSchema)` to create a new message.
 */
export const IntradayImpliedVolatilitiesResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_implied_volatility, 1);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayImpliedVolatility.
 * Use `create(IntradayImpliedVolatilitySchema)` to create a new message.
 */
export const IntradayImpliedVolatilitySchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_implied_volatility, 2);

/**
 * Called to request intraday ImpliedVolatility data. 
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradayImpliedVolatilitiesService
 */
export const IntradayImpliedVolatilitiesService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_v1_intraday_implied_volatility, 0);

