// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Intraday prices illustrates intraday price movements for an instrument over a look back period.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v1/intraday_prices.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_prices.proto.
 */
export const file_systemathics_apis_services_intraday_v1_intraday_prices = /*@__PURE__*/
  fileDesc("CjxzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheS92MS9pbnRyYWRheV9wcmljZXMucHJvdG8SJnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxIvIBChVJbnRyYWRheVByaWNlc1JlcXVlc3QSQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISPAoIc2FtcGxpbmcYAiABKA4yKi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5TYW1wbGluZxJFCg1kYXRlX2ludGVydmFsGAMgASgLMi4uc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuRGF0ZUludGVydmFsEhIKCmFkanVzdG1lbnQYBCABKAgiXQoWSW50cmFkYXlQcmljZXNSZXNwb25zZRJDCgRkYXRhGAEgAygLMjUuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXkudjEuSW50cmFkYXlQcmljZSJtCg1JbnRyYWRheVByaWNlEi4KCnRpbWVfc3RhbXAYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEg0KBXByaWNlGAIgASgBEg4KBnZvbHVtZRgDIAEoARINCgVzY29yZRgEIAEoATLGAQoVSW50cmFkYXlQcmljZXNTZXJ2aWNlEqwBCg5JbnRyYWRheVByaWNlcxI9LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxLkludHJhZGF5UHJpY2VzUmVxdWVzdBo+LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxLkludHJhZGF5UHJpY2VzUmVzcG9uc2UiG4LT5JMCFRITL3YxL2ludHJhZGF5L3ByaWNlc2IGcHJvdG8z", [file_google_api_annotations, file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayPricesRequest.
 * Use `create(IntradayPricesRequestSchema)` to create a new message.
 */
export const IntradayPricesRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_prices, 0);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayPricesResponse.
 * Use `create(IntradayPricesResponseSchema)` to create a new message.
 */
export const IntradayPricesResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_prices, 1);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayPrice.
 * Use `create(IntradayPriceSchema)` to create a new message.
 */
export const IntradayPriceSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_prices, 2);

/**
 * Called to request intraday prices data. 
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradayPricesService
 */
export const IntradayPricesService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_v1_intraday_prices, 0);

