// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This service provides access to an intraday marketdata market data service,
// enabling users to retrieve historical market data for various financial instruments.
// MarketData represents a comprehensive aggregation of all pertinent market information, 
// encompassing various data points such as bar data, best limit data, Greeks, and more.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v1/intraday_market_data.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_date_interval } from "../../../type/shared/v1/date_interval_pb";
import { file_systemathics_apis_type_shared_v1_sampling } from "../../../type/shared/v1/sampling_pb";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_market_data.proto.
 */
export const file_systemathics_apis_services_intraday_v1_intraday_market_data = /*@__PURE__*/
  fileDesc("CkFzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9pbnRyYWRheS92MS9pbnRyYWRheV9tYXJrZXRfZGF0YS5wcm90bxImc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuaW50cmFkYXkudjEi4gEKGUludHJhZGF5TWFya2V0RGF0YVJlcXVlc3QSQAoKaWRlbnRpZmllchgBIAEoCzIsLnN5c3RlbWF0aGljcy5hcGlzLnR5cGUuc2hhcmVkLnYxLklkZW50aWZpZXISPAoIc2FtcGxpbmcYAiABKA4yKi5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5TYW1wbGluZxJFCg1kYXRlX2ludGVydmFsGAMgASgLMi4uc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuRGF0ZUludGVydmFsImYKGkludHJhZGF5TWFya2V0RGF0YVJlc3BvbnNlEkgKBGRhdGEYASADKAsyOi5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MS5JbnRyYWRheU1hcmtldERhdGEi9AIKEkludHJhZGF5TWFya2V0RGF0YRIuCgp0aW1lX3N0YW1wGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIMCgRvcGVuGAIgASgBEgwKBGhpZ2gYAyABKAESCwoDbG93GAQgASgBEg0KBWNsb3NlGAUgASgBEg4KBnZvbHVtZRgGIAEoARIRCgliaWRfcHJpY2UYByABKAESEAoIYmlkX3NpemUYCCABKAESEQoJYXNrX3ByaWNlGAkgASgBEhAKCGFza19zaXplGAogASgBEg0KBWRlbHRhGAsgASgBEg0KBWdhbW1hGAwgASgBEg0KBXRoZXRhGA0gASgBEgwKBHZlZ2EYDiABKAESCwoDcmhvGA8gASgBEhoKEmltcGxpZWRfdm9sYXRpbGl0eRgQIAEoARIVCg1vcGVuX2ludGVyZXN0GBEgASgBEhIKCnVuZGVybHlpbmcYEiABKAESDQoFc2NvcmUYEyABKAEy2gEKGUludHJhZGF5TWFya2V0RGF0YVNlcnZpY2USvAEKEkludHJhZGF5TWFya2V0RGF0YRJBLnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLmludHJhZGF5LnYxLkludHJhZGF5TWFya2V0RGF0YVJlcXVlc3QaQi5zeXN0ZW1hdGhpY3MuYXBpcy5zZXJ2aWNlcy5pbnRyYWRheS52MS5JbnRyYWRheU1hcmtldERhdGFSZXNwb25zZSIfgtPkkwIZEhcvdjEvaW50cmFkYXkvbWFya2V0ZGF0YWIGcHJvdG8z", [file_google_api_annotations, file_google_protobuf_timestamp, file_systemathics_apis_type_shared_v1_identifier, file_systemathics_apis_type_shared_v1_date_interval, file_systemathics_apis_type_shared_v1_sampling]);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayMarketDataRequest.
 * Use `create(IntradayMarketDataRequestSchema)` to create a new message.
 */
export const IntradayMarketDataRequestSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_market_data, 0);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayMarketDataResponse.
 * Use `create(IntradayMarketDataResponseSchema)` to create a new message.
 */
export const IntradayMarketDataResponseSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_market_data, 1);

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayMarketData.
 * Use `create(IntradayMarketDataSchema)` to create a new message.
 */
export const IntradayMarketDataSchema = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_intraday_v1_intraday_market_data, 2);

/**
 * Called to request intraday marketdata data. 
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradayMarketDataService
 */
export const IntradayMarketDataService = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_intraday_v1_intraday_market_data, 0);

