// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Best limit data represent the highest bid and lowest ask prices in the market at any given time, providing valuable insights into the current state of supply and demand.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v1/intraday_best_limit.proto (package systemathics.apis.services.intraday.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import type { DateInterval } from "../../../type/shared/v1/date_interval_pb";
import type { TimeInterval } from "../../../type/shared/v1/time_interval_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file systemathics/apis/services/intraday/v1/intraday_best_limit.proto.
 */
export declare const file_systemathics_apis_services_intraday_v1_intraday_best_limit: GenFile;

/**
 * The required input to request the IntradayBestLimitsService.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayBestLimitsRequest
 */
export declare type IntradayBestLimitsRequest = Message<"systemathics.apis.services.intraday.v1.IntradayBestLimitsRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If empty, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.DateInterval date_interval = 3;
   */
  dateInterval?: DateInterval;

  /**
   * [Optional] The corporate action adjustment (dividends and splits).
   * By default the value is set to false
   *
   * @generated from field: bool adjustment = 4;
   */
  adjustment: boolean;

  /**
   * [Optional] The time constraints used to define the look-back period.
   * If missing, then all the available data is retrieved.
   *
   * @generated from field: systemathics.apis.type.shared.v1.TimeInterval time_interval = 5;
   */
  timeInterval?: TimeInterval;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayBestLimitsRequest.
 * Use `create(IntradayBestLimitsRequestSchema)` to create a new message.
 */
export declare const IntradayBestLimitsRequestSchema: GenMessage<IntradayBestLimitsRequest>;

/**
 * The intraday bestlimits response contains an array of intraday bestlimits.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayBestLimitsResponse
 */
export declare type IntradayBestLimitsResponse = Message<"systemathics.apis.services.intraday.v1.IntradayBestLimitsResponse"> & {
  /**
   * The intraday bestlimits: an array of IntradayBestLimit objects
   *
   * @generated from field: repeated systemathics.apis.services.intraday.v1.IntradayBestLimit data = 1;
   */
  data: IntradayBestLimit[];
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayBestLimitsResponse.
 * Use `create(IntradayBestLimitsResponseSchema)` to create a new message.
 */
export declare const IntradayBestLimitsResponseSchema: GenMessage<IntradayBestLimitsResponse>;

/**
 * Contains the intraday bar's data: date, bid, ask and score.
 *
 * @generated from message systemathics.apis.services.intraday.v1.IntradayBestLimit
 */
export declare type IntradayBestLimit = Message<"systemathics.apis.services.intraday.v1.IntradayBestLimit"> & {
  /**
   * UTC time stamp of the intraday bar : open time of the sampling interval
   *
   * @generated from field: google.protobuf.Timestamp time_stamp = 1;
   */
  timeStamp?: Timestamp;

  /**
   * The best bid price of the sampling period
   *
   * @generated from field: double bid_price = 2;
   */
  bidPrice: number;

  /**
   * The best bid size of the sampling period
   *
   * @generated from field: double bid_size = 3;
   */
  bidSize: number;

  /**
   * The best ask price of the sampling period
   *
   * @generated from field: double ask_price = 4;
   */
  askPrice: number;

  /**
   * The best ask size of the sampling period
   *
   * @generated from field: double ask_size = 5;
   */
  askSize: number;

  /**
   * The data quality scoring : from 0 (bad) to 100 (good)
   *
   * @generated from field: double score = 6;
   */
  score: number;
};

/**
 * Describes the message systemathics.apis.services.intraday.v1.IntradayBestLimit.
 * Use `create(IntradayBestLimitSchema)` to create a new message.
 */
export declare const IntradayBestLimitSchema: GenMessage<IntradayBestLimit>;

/**
 * This service serves as a gateway to an intraday Best Limit market data service, allowing users to access historical data on the best limit order levels for various financial instruments. 
 *
 * @generated from service systemathics.apis.services.intraday.v1.IntradayBestLimitsService
 */
export declare const IntradayBestLimitsService: GenService<{
  /**
   * Gets intraday historical data: date, bid and ask
   *
   * @generated from rpc systemathics.apis.services.intraday.v1.IntradayBestLimitsService.IntradayBestLimits
   */
  intradayBestLimits: {
    methodKind: "unary";
    input: typeof IntradayBestLimitsRequestSchema;
    output: typeof IntradayBestLimitsResponseSchema;
  },
}>;

