// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// The sustainability provides Environmental, Social, and Corporate Governance data.

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/services/sustainability/v1/sustainability.proto (package systemathics.apis.services.sustainability.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import { file_systemathics_apis_type_shared_v1_identifier } from "../../../type/shared/v1/identifier_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/services/sustainability/v1/sustainability.proto.
 */
export const file_systemathics_apis_services_sustainability_v1_sustainability: GenFile = /*@__PURE__*/
  fileDesc("CkFzeXN0ZW1hdGhpY3MvYXBpcy9zZXJ2aWNlcy9zdXN0YWluYWJpbGl0eS92MS9zdXN0YWluYWJpbGl0eS5wcm90bxIsc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc3VzdGFpbmFiaWxpdHkudjEiWQoVU3VzdGFpbmFiaWxpdHlSZXF1ZXN0EkAKCmlkZW50aWZpZXIYASABKAsyLC5zeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MS5JZGVudGlmaWVyImQKFlN1c3RhaW5hYmlsaXR5UmVzcG9uc2USSgoEZGF0YRgBIAMoCzI8LnN5c3RlbWF0aGljcy5hcGlzLnNlcnZpY2VzLnN1c3RhaW5hYmlsaXR5LnYxLlN1c3RhaW5hYmlsaXR5IooBCg5TdXN0YWluYWJpbGl0eRIQCghwcm92aWRlchgBIAEoCRIMCgRuYW1lGAIgASgJEgoKAmlkGAMgASgJEg4KBnBhcmVudBgEIAEoCRINCgV2YWx1ZRgFIAEoARILCgNtaW4YBiABKAESCwoDbWF4GAcgASgBEhMKC2Rlc2NyaXB0aW9uGAggASgJMtEBChVTdXN0YWluYWJpbGl0eVNlcnZpY2UStwEKDlN1c3RhaW5hYmlsaXR5EkMuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc3VzdGFpbmFiaWxpdHkudjEuU3VzdGFpbmFiaWxpdHlSZXF1ZXN0GkQuc3lzdGVtYXRoaWNzLmFwaXMuc2VydmljZXMuc3VzdGFpbmFiaWxpdHkudjEuU3VzdGFpbmFiaWxpdHlSZXNwb25zZSIagtPkkwIUEhIvdjEvc3VzdGFpbmFiaWxpdHliBnByb3RvMw", [file_google_api_annotations, file_systemathics_apis_type_shared_v1_identifier]);

/**
 * The required inputs to request the SustainabilityService.
 *
 * @generated from message systemathics.apis.services.sustainability.v1.SustainabilityRequest
 */
export type SustainabilityRequest = Message<"systemathics.apis.services.sustainability.v1.SustainabilityRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;
};

/**
 * Describes the message systemathics.apis.services.sustainability.v1.SustainabilityRequest.
 * Use `create(SustainabilityRequestSchema)` to create a new message.
 */
export const SustainabilityRequestSchema: GenMessage<SustainabilityRequest> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_sustainability_v1_sustainability, 0);

/**
 * Represents a sustainability response.
 *
 * @generated from message systemathics.apis.services.sustainability.v1.SustainabilityResponse
 */
export type SustainabilityResponse = Message<"systemathics.apis.services.sustainability.v1.SustainabilityResponse"> & {
  /**
   * The sustainabilities: an array of sustainability objects
   *
   * @generated from field: repeated systemathics.apis.services.sustainability.v1.Sustainability data = 1;
   */
  data: Sustainability[];
};

/**
 * Describes the message systemathics.apis.services.sustainability.v1.SustainabilityResponse.
 * Use `create(SustainabilityResponseSchema)` to create a new message.
 */
export const SustainabilityResponseSchema: GenMessage<SustainabilityResponse> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_sustainability_v1_sustainability, 1);

/**
 * Contains the sustainabilitys's data.
 *
 * @generated from message systemathics.apis.services.sustainability.v1.Sustainability
 */
export type Sustainability = Message<"systemathics.apis.services.sustainability.v1.Sustainability"> & {
  /**
   * The sustainability provider
   *
   * @generated from field: string provider = 1;
   */
  provider: string;

  /**
   * The sustainability name or label
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * The sustainability identifier
   *
   * @generated from field: string id = 3;
   */
  id: string;

  /**
   * The sustainability parent identifier
   *
   * @generated from field: string parent = 4;
   */
  parent: string;

  /**
   * The sustainability value
   *
   * @generated from field: double value = 5;
   */
  value: number;

  /**
   * The sustainability minimum value
   *
   * @generated from field: double min = 6;
   */
  min: number;

  /**
   * The sustainability maximum value
   *
   * @generated from field: double max = 7;
   */
  max: number;

  /**
   * The sustainability description
   *
   * @generated from field: string description = 8;
   */
  description: string;
};

/**
 * Describes the message systemathics.apis.services.sustainability.v1.Sustainability.
 * Use `create(SustainabilitySchema)` to create a new message.
 */
export const SustainabilitySchema: GenMessage<Sustainability> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_services_sustainability_v1_sustainability, 2);

/**
 * Called to request sustainability data.
 *
 * @generated from service systemathics.apis.services.sustainability.v1.SustainabilityService
 */
export const SustainabilityService: GenService<{
  /**
   * Gets sustainability data
   *
   * @generated from rpc systemathics.apis.services.sustainability.v1.SustainabilityService.Sustainability
   */
  sustainability: {
    methodKind: "unary";
    input: typeof SustainabilityRequestSchema;
    output: typeof SustainabilityResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_systemathics_apis_services_sustainability_v1_sustainability, 0);

