// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// The sustainability provides Environmental, Social, and Corporate Governance data.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/sustainability/v1/sustainability.proto (package systemathics.apis.services.sustainability.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";

/**
 * Describes the file systemathics/apis/services/sustainability/v1/sustainability.proto.
 */
export declare const file_systemathics_apis_services_sustainability_v1_sustainability: GenFile;

/**
 * The required inputs to request the SustainabilityService.
 *
 * @generated from message systemathics.apis.services.sustainability.v1.SustainabilityRequest
 */
export declare type SustainabilityRequest = Message<"systemathics.apis.services.sustainability.v1.SustainabilityRequest"> & {
  /**
   * [Mandatory] The instrument identifier: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;
};

/**
 * Describes the message systemathics.apis.services.sustainability.v1.SustainabilityRequest.
 * Use `create(SustainabilityRequestSchema)` to create a new message.
 */
export declare const SustainabilityRequestSchema: GenMessage<SustainabilityRequest>;

/**
 * Represents a sustainability response.
 *
 * @generated from message systemathics.apis.services.sustainability.v1.SustainabilityResponse
 */
export declare type SustainabilityResponse = Message<"systemathics.apis.services.sustainability.v1.SustainabilityResponse"> & {
  /**
   * The sustainabilities: an array of sustainability objects
   *
   * @generated from field: repeated systemathics.apis.services.sustainability.v1.Sustainability data = 1;
   */
  data: Sustainability[];
};

/**
 * Describes the message systemathics.apis.services.sustainability.v1.SustainabilityResponse.
 * Use `create(SustainabilityResponseSchema)` to create a new message.
 */
export declare const SustainabilityResponseSchema: GenMessage<SustainabilityResponse>;

/**
 * Contains the sustainabilitys's data.
 *
 * @generated from message systemathics.apis.services.sustainability.v1.Sustainability
 */
export declare type Sustainability = Message<"systemathics.apis.services.sustainability.v1.Sustainability"> & {
  /**
   * The sustainability provider
   *
   * @generated from field: string provider = 1;
   */
  provider: string;

  /**
   * The sustainability name or label
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * The sustainability identifier
   *
   * @generated from field: string id = 3;
   */
  id: string;

  /**
   * The sustainability parent identifier
   *
   * @generated from field: string parent = 4;
   */
  parent: string;

  /**
   * The sustainability value
   *
   * @generated from field: double value = 5;
   */
  value: number;

  /**
   * The sustainability minimum value
   *
   * @generated from field: double min = 6;
   */
  min: number;

  /**
   * The sustainability maximum value
   *
   * @generated from field: double max = 7;
   */
  max: number;

  /**
   * The sustainability description
   *
   * @generated from field: string description = 8;
   */
  description: string;
};

/**
 * Describes the message systemathics.apis.services.sustainability.v1.Sustainability.
 * Use `create(SustainabilitySchema)` to create a new message.
 */
export declare const SustainabilitySchema: GenMessage<Sustainability>;

/**
 * Called to request sustainability data.
 *
 * @generated from service systemathics.apis.services.sustainability.v1.SustainabilityService
 */
export declare const SustainabilityService: GenService<{
  /**
   * Gets sustainability data
   *
   * @generated from rpc systemathics.apis.services.sustainability.v1.SustainabilityService.Sustainability
   */
  sustainability: {
    methodKind: "unary";
    input: typeof SustainabilityRequestSchema;
    output: typeof SustainabilityResponseSchema;
  },
}>;

