// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Intraday prices illustrates intraday price movements for an instrument over a look back period.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/services/intraday/v2/set_intraday.proto (package systemathics.apis.services.intraday.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Identifier } from "../../../type/shared/v1/identifier_pb";
import type { Sampling } from "../../../type/shared/v1/sampling_pb";
import type { DateTime } from "../../../../../google/type/datetime_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file systemathics/apis/services/intraday/v2/set_intraday.proto.
 */
export declare const file_systemathics_apis_services_intraday_v2_set_intraday: GenFile;

/**
 * The required input to request the SetDailyScalar endpoint
 *
 * @generated from message systemathics.apis.services.intraday.v2.SetIntradayScalarRequest
 */
export declare type SetIntradayScalarRequest = Message<"systemathics.apis.services.intraday.v2.SetIntradayScalarRequest"> & {
  /**
   * [Mandatory] The instrument identifiers: a bloomberg dailyer and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Mandatory] The date used to request data.
   *
   * @generated from field: google.type.DateTime datetime = 3;
   */
  datetime?: DateTime;

  /**
   * [Mandatory] The data with field as a key
   *
   * @generated from field: map<string, double> data = 4;
   */
  data: { [key: string]: number };
};

/**
 * Describes the message systemathics.apis.services.intraday.v2.SetIntradayScalarRequest.
 * Use `create(SetIntradayScalarRequestSchema)` to create a new message.
 */
export declare const SetIntradayScalarRequestSchema: GenMessage<SetIntradayScalarRequest>;

/**
 * The required input to request the SetIntradayScalar endpoint
 *
 * @generated from message systemathics.apis.services.intraday.v2.SetIntradayScalarStreamRequest
 */
export declare type SetIntradayScalarStreamRequest = Message<"systemathics.apis.services.intraday.v2.SetIntradayScalarStreamRequest"> & {
  /**
   * @generated from oneof systemathics.apis.services.intraday.v2.SetIntradayScalarStreamRequest.payload
   */
  payload: {
    /**
     * The intraday info
     *
     * @generated from field: systemathics.apis.services.intraday.v2.SetIntradayInfo info = 1;
     */
    value: SetIntradayInfo;
    case: "info";
  } | {
    /**
     * The mapping data
     *
     * @generated from field: systemathics.apis.services.intraday.v2.SetIntradayScalarData data = 2;
     */
    value: SetIntradayScalarData;
    case: "data";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.services.intraday.v2.SetIntradayScalarStreamRequest.
 * Use `create(SetIntradayScalarStreamRequestSchema)` to create a new message.
 */
export declare const SetIntradayScalarStreamRequestSchema: GenMessage<SetIntradayScalarStreamRequest>;

/**
 * The required input to request the SetIntradayScalar endpoint
 *
 * @generated from message systemathics.apis.services.intraday.v2.SetIntradayVectorRequest
 */
export declare type SetIntradayVectorRequest = Message<"systemathics.apis.services.intraday.v2.SetIntradayVectorRequest"> & {
  /**
   * [Mandatory] The instrument identifiers: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Mandatory] The date used to request data.
   *
   * @generated from field: google.type.DateTime datetime = 3;
   */
  datetime?: DateTime;

  /**
   * [Mandatory] The vector key.
   *
   * @generated from field: string key = 4;
   */
  key: string;

  /**
   * [Mandatory] The data with field as a key
   *
   * @generated from field: map<string, double> data = 5;
   */
  data: { [key: string]: number };
};

/**
 * Describes the message systemathics.apis.services.intraday.v2.SetIntradayVectorRequest.
 * Use `create(SetIntradayVectorRequestSchema)` to create a new message.
 */
export declare const SetIntradayVectorRequestSchema: GenMessage<SetIntradayVectorRequest>;

/**
 * The required input to request the SetIntradayScalar endpoint
 *
 * @generated from message systemathics.apis.services.intraday.v2.SetIntradayVectorStreamRequest
 */
export declare type SetIntradayVectorStreamRequest = Message<"systemathics.apis.services.intraday.v2.SetIntradayVectorStreamRequest"> & {
  /**
   * @generated from oneof systemathics.apis.services.intraday.v2.SetIntradayVectorStreamRequest.payload
   */
  payload: {
    /**
     * The tick info
     *
     * @generated from field: systemathics.apis.services.intraday.v2.SetIntradayInfo info = 1;
     */
    value: SetIntradayInfo;
    case: "info";
  } | {
    /**
     * The mapping data
     *
     * @generated from field: systemathics.apis.services.intraday.v2.SetIntradayVectorData data = 2;
     */
    value: SetIntradayVectorData;
    case: "data";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.services.intraday.v2.SetIntradayVectorStreamRequest.
 * Use `create(SetIntradayVectorStreamRequestSchema)` to create a new message.
 */
export declare const SetIntradayVectorStreamRequestSchema: GenMessage<SetIntradayVectorStreamRequest>;

/**
 * The required input to request DeleteIntradayScalar.
 *
 * @generated from message systemathics.apis.services.intraday.v2.DeleteIntradayScalarRequest
 */
export declare type DeleteIntradayScalarRequest = Message<"systemathics.apis.services.intraday.v2.DeleteIntradayScalarRequest"> & {
  /**
   * [Mandatory] The instrument identifiers: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Mandatory] The fields to be deleted.
   *
   * @generated from field: repeated string fields = 3;
   */
  fields: string[];

  /**
   * [Mandatory] The dates to be deleted.
   *
   * @generated from field: repeated google.type.DateTime dates = 4;
   */
  dates: DateTime[];
};

/**
 * Describes the message systemathics.apis.services.intraday.v2.DeleteIntradayScalarRequest.
 * Use `create(DeleteIntradayScalarRequestSchema)` to create a new message.
 */
export declare const DeleteIntradayScalarRequestSchema: GenMessage<DeleteIntradayScalarRequest>;

/**
 * The required input to request DeleteIntradayScalar.
 *
 * @generated from message systemathics.apis.services.intraday.v2.DeleteIntradayVectorRequest
 */
export declare type DeleteIntradayVectorRequest = Message<"systemathics.apis.services.intraday.v2.DeleteIntradayVectorRequest"> & {
  /**
   * [Mandatory] The instrument identifiers: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Mandatory] The fields to be deleted.
   *
   * @generated from field: repeated string fields = 3;
   */
  fields: string[];

  /**
   * [Mandatory] The keys to be deleted.
   *
   * @generated from field: repeated systemathics.apis.services.intraday.v2.VectorKey keys = 4;
   */
  keys: VectorKey[];
};

/**
 * Describes the message systemathics.apis.services.intraday.v2.DeleteIntradayVectorRequest.
 * Use `create(DeleteIntradayVectorRequestSchema)` to create a new message.
 */
export declare const DeleteIntradayVectorRequestSchema: GenMessage<DeleteIntradayVectorRequest>;

/**
 * The required input to request the GetIntradayByDate endpoint
 *
 * @generated from message systemathics.apis.services.intraday.v2.SetIntradayInfo
 */
export declare type SetIntradayInfo = Message<"systemathics.apis.services.intraday.v2.SetIntradayInfo"> & {
  /**
   * [Mandatory] The instrument identifiers: a bloomberg ticker and an asset type
   *
   * @generated from field: systemathics.apis.type.shared.v1.Identifier identifier = 1;
   */
  identifier?: Identifier;

  /**
   * [Mandatory] The sampling interval
   *
   * @generated from field: systemathics.apis.type.shared.v1.Sampling sampling = 2;
   */
  sampling: Sampling;

  /**
   * [Mandatory] The data names.
   *
   * @generated from field: repeated string fields = 3;
   */
  fields: string[];
};

/**
 * Describes the message systemathics.apis.services.intraday.v2.SetIntradayInfo.
 * Use `create(SetIntradayInfoSchema)` to create a new message.
 */
export declare const SetIntradayInfoSchema: GenMessage<SetIntradayInfo>;

/**
 * Represent the data to be added to the data scalar timeseries.
 *
 * @generated from message systemathics.apis.services.intraday.v2.SetIntradayScalarData
 */
export declare type SetIntradayScalarData = Message<"systemathics.apis.services.intraday.v2.SetIntradayScalarData"> & {
  /**
   * [Mandatory] The date used to request data.
   *
   * @generated from field: google.type.DateTime datetime = 1;
   */
  datetime?: DateTime;

  /**
   * [Mandatory] The date used to request data.
   *
   * @generated from field: repeated double data = 2;
   */
  data: number[];
};

/**
 * Describes the message systemathics.apis.services.intraday.v2.SetIntradayScalarData.
 * Use `create(SetIntradayScalarDataSchema)` to create a new message.
 */
export declare const SetIntradayScalarDataSchema: GenMessage<SetIntradayScalarData>;

/**
 * Represent the key for a vector.
 *
 * @generated from message systemathics.apis.services.intraday.v2.VectorKey
 */
export declare type VectorKey = Message<"systemathics.apis.services.intraday.v2.VectorKey"> & {
  /**
   * [Mandatory] The date used to request data.
   *
   * @generated from field: google.type.DateTime datetime = 1;
   */
  datetime?: DateTime;

  /**
   * [Mandatory] The vector key.
   *
   * @generated from field: string key = 2;
   */
  key: string;
};

/**
 * Describes the message systemathics.apis.services.intraday.v2.VectorKey.
 * Use `create(VectorKeySchema)` to create a new message.
 */
export declare const VectorKeySchema: GenMessage<VectorKey>;

/**
 * Represent the data to be added to the data vector timeseries.
 *
 * @generated from message systemathics.apis.services.intraday.v2.SetIntradayVectorData
 */
export declare type SetIntradayVectorData = Message<"systemathics.apis.services.intraday.v2.SetIntradayVectorData"> & {
  /**
   * [Mandatory] The date used to request data.
   *
   * @generated from field: google.type.DateTime datetime = 1;
   */
  datetime?: DateTime;

  /**
   * [Mandatory] The vector key.
   *
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * [Mandatory] The data.
   *
   * @generated from field: repeated double data = 3;
   */
  data: number[];
};

/**
 * Describes the message systemathics.apis.services.intraday.v2.SetIntradayVectorData.
 * Use `create(SetIntradayVectorDataSchema)` to create a new message.
 */
export declare const SetIntradayVectorDataSchema: GenMessage<SetIntradayVectorData>;

/**
 * Called to set intraday prices data and clear. 
 *
 * @generated from service systemathics.apis.services.intraday.v2.SetIntradayService
 */
export declare const SetIntradayService: GenService<{
  /**
   * Sets intraday scalar timeseries.
   *
   * @generated from rpc systemathics.apis.services.intraday.v2.SetIntradayService.WriteIntradayScalar
   */
  writeIntradayScalar: {
    methodKind: "unary";
    input: typeof SetIntradayScalarRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc systemathics.apis.services.intraday.v2.SetIntradayService.WriteIntradayScalarStream
   */
  writeIntradayScalarStream: {
    methodKind: "client_streaming";
    input: typeof SetIntradayScalarStreamRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Sets intraday vector timeseries.
   *
   * @generated from rpc systemathics.apis.services.intraday.v2.SetIntradayService.WriteIntradayVector
   */
  writeIntradayVector: {
    methodKind: "unary";
    input: typeof SetIntradayVectorRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Sets intraday vector timeseries.
   *
   * @generated from rpc systemathics.apis.services.intraday.v2.SetIntradayService.WriteIntradayVectorStream
   */
  writeIntradayVectorStream: {
    methodKind: "client_streaming";
    input: typeof SetIntradayVectorStreamRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Update intraday scalar timeseries.
   *
   * @generated from rpc systemathics.apis.services.intraday.v2.SetIntradayService.UpdateIntradayScalar
   */
  updateIntradayScalar: {
    methodKind: "unary";
    input: typeof SetIntradayScalarRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Update intraday scalar timeseries.
   *
   * @generated from rpc systemathics.apis.services.intraday.v2.SetIntradayService.UpdateIntradayScalarStream
   */
  updateIntradayScalarStream: {
    methodKind: "client_streaming";
    input: typeof SetIntradayScalarStreamRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Update intraday vectors timeseries.
   *
   * @generated from rpc systemathics.apis.services.intraday.v2.SetIntradayService.UpdateIntradayVector
   */
  updateIntradayVector: {
    methodKind: "unary";
    input: typeof SetIntradayVectorRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Update intraday vectors timeseries.
   *
   * @generated from rpc systemathics.apis.services.intraday.v2.SetIntradayService.UpdateIntradayVectorStream
   */
  updateIntradayVectorStream: {
    methodKind: "client_streaming";
    input: typeof SetIntradayVectorStreamRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Delete intraday scalar timeseries.
   *
   * @generated from rpc systemathics.apis.services.intraday.v2.SetIntradayService.DeleteIntradayScalar
   */
  deleteIntradayScalar: {
    methodKind: "unary";
    input: typeof DeleteIntradayScalarRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Delete intraday scalar timeseries.
   *
   * @generated from rpc systemathics.apis.services.intraday.v2.SetIntradayService.DeleteIntradayVector
   */
  deleteIntradayVector: {
    methodKind: "unary";
    input: typeof DeleteIntradayVectorRequestSchema;
    output: typeof EmptySchema;
  },
}>;

