// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// The asset type

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/type/shared/v1/asset.proto (package systemathics.apis.type.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/type/shared/v1/asset.proto.
 */
export declare const file_systemathics_apis_type_shared_v1_asset: GenFile;

/**
 * Asset Type Request
 *
 * @generated from message systemathics.apis.type.shared.v1.AssetTypeRequest
 */
export declare type AssetTypeRequest = Message<"systemathics.apis.type.shared.v1.AssetTypeRequest"> & {
  /**
   * [Mandatory] The asset type of the static data.
   *
   * @generated from field: systemathics.apis.type.shared.v1.AssetType asset_type = 1;
   */
  assetType: AssetType;
};

/**
 * Describes the message systemathics.apis.type.shared.v1.AssetTypeRequest.
 * Use `create(AssetTypeRequestSchema)` to create a new message.
 */
export declare const AssetTypeRequestSchema: GenMessage<AssetTypeRequest>;

/**
 * Contains all asset types for the static data request.
 *
 * @generated from enum systemathics.apis.type.shared.v1.AssetType
 */
export enum AssetType {
  /**
   * Not specified ?
   *
   * @generated from enum value: ASSET_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * All asset types. Used only for search.
   *
   * @generated from enum value: ASSET_TYPE_ALL = 1;
   */
  ALL = 1,

  /**
   * Equities
   *
   * @generated from enum value: ASSET_TYPE_EQUITY = 2;
   */
  EQUITY = 2,

  /**
   * Futures
   *
   * @generated from enum value: ASSET_TYPE_FUTURE = 3;
   */
  FUTURE = 3,

  /**
   * Exchange Traded Fund
   *
   * @generated from enum value: ASSET_TYPE_ETF = 4;
   */
  ETF = 4,

  /**
   * Index
   *
   * @generated from enum value: ASSET_TYPE_INDEX = 5;
   */
  INDEX = 5,

  /**
   * Forex pairs
   *
   * @generated from enum value: ASSET_TYPE_FOREX = 7;
   */
  FOREX = 7,

  /**
   * Options
   *
   * @generated from enum value: ASSET_TYPE_OPTION = 8;
   */
  OPTION = 8,

  /**
   * Bonds
   *
   * @generated from enum value: ASSET_TYPE_BOND = 9;
   */
  BOND = 9,

  /**
   * Cds
   *
   * @generated from enum value: ASSET_TYPE_CDS = 10;
   */
  CDS = 10,

  /**
   * Cds index 
   *
   * @generated from enum value: ASSET_TYPE_CDS_INDEX = 11;
   */
  CDS_INDEX = 11,

  /**
   * Cds index tranche
   *
   * @generated from enum value: ASSET_TYPE_CDS_INDEX_TRANCHE = 12;
   */
  CDS_INDEX_TRANCHE = 12,

  /**
   * Cds index option
   *
   * @generated from enum value: ASSET_TYPE_CDS_INDEX_OPTION = 13;
   */
  CDS_INDEX_OPTION = 13,
}

/**
 * Describes the enum systemathics.apis.type.shared.v1.AssetType.
 */
export declare const AssetTypeSchema: GenEnum<AssetType>;

