// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Represents a date and time constraint:
// <br>- Time zone is alway implied to be Universal Time Coordinated (UTC)
// <br>- Dates are relative to the Proleptic Gregorian Calendar. 

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/type/shared/v1/constraints.proto (package systemathics.apis.type.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { DateInterval } from "./date_interval_pb";
import type { TimeInterval } from "./time_interval_pb";
import type { Date } from "../../../../../google/type/date_pb";
import type { DayOfWeek } from "../../../../../google/type/dayofweek_pb";

/**
 * Describes the file systemathics/apis/type/shared/v1/constraints.proto.
 */
export declare const file_systemathics_apis_type_shared_v1_constraints: GenFile;

/**
 * <br>- Zero, one or many [Date intervals](#DateInterval). The union of each date interval is used.
 * <br>- Zero, one or many [Time intervals](#TimeInterval). The union of each time interval is used.
 * <br>- Zero, one or many [Excluded dates](#google.type.Date). The union of each excluded dates is used.
 * <br>- Zero, one or many [Excluded days](#google.type.DayOfWeek). The union of each excluded days is used.
 *
 * @generated from message systemathics.apis.type.shared.v1.Constraints
 */
export declare type Constraints = Message<"systemathics.apis.type.shared.v1.Constraints"> & {
  /**
   * Restricts request to an union of date_intervals
   * <br>Providing no date_intervals will return all the stored data
   *
   * @generated from field: repeated systemathics.apis.type.shared.v1.DateInterval date_intervals = 1;
   */
  dateIntervals: DateInterval[];

  /**
   * Restricts request to an union of time_intervals. (ie: Market hours, trading hours, ...)
   * <br>Note: Time intervals including midnight needs to be described as an union of time intervals (ie : [22:00-23:59] U [00:00-04:00])
   *
   * @generated from field: repeated systemathics.apis.type.shared.v1.TimeInterval time_intervals = 2;
   */
  timeIntervals: TimeInterval[];

  /**
   * Restricts request to an union of excluded_dates (ie: closed Days, holidays, ...).
   *
   * @generated from field: repeated google.type.Date excluded_dates = 3;
   */
  excludedDates: Date[];

  /**
   * Restricts request to an union of excluded_days (ie: weekd-end can be represented with Saturday, Sunday)
   *
   * @generated from field: repeated google.type.DayOfWeek excluded_days = 4;
   */
  excludedDays: DayOfWeek[];
};

/**
 * Describes the message systemathics.apis.type.shared.v1.Constraints.
 * Use `create(ConstraintsSchema)` to create a new message.
 */
export declare const ConstraintsSchema: GenMessage<Constraints>;

