// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Represents a date interval used to delimit historical data requests in time. Dates are relative to the Proleptic Gregorian Calendar.

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/type/shared/v1/date_interval.proto (package systemathics.apis.type.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Date } from "../../../../../google/type/date_pb";

/**
 * Describes the file systemathics/apis/type/shared/v1/date_interval.proto.
 */
export declare const file_systemathics_apis_type_shared_v1_date_interval: GenFile;

/**
 * Contains date interval with start date (included) and end date (excluded).
 *
 * @generated from message systemathics.apis.type.shared.v1.DateInterval
 */
export declare type DateInterval = Message<"systemathics.apis.type.shared.v1.DateInterval"> & {
  /**
   * Start date of the date interval. It must always be smaller than end date
   *
   * @generated from field: google.type.Date start_date = 1;
   */
  startDate?: Date;

  /**
   * End date of the date interval. It must always be greater than start date
   *
   * @generated from field: google.type.Date end_date = 2;
   */
  endDate?: Date;
};

/**
 * Describes the message systemathics.apis.type.shared.v1.DateInterval.
 * Use `create(DateIntervalSchema)` to create a new message.
 */
export declare const DateIntervalSchema: GenMessage<DateInterval>;

