// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Date filter supporting exact match or range queries
//
// <p>Use for temporal filtering of instruments (maturity, issue date, etc.)</p>
// <p>Ranges are left-inclusive, right-exclusive: [greater_or_equal_than, less_than)</p>

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/type/shared/v1/filter.proto (package systemathics.apis.type.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Date } from "../../../../../google/type/date_pb";

/**
 * Describes the file systemathics/apis/type/shared/v1/filter.proto.
 */
export declare const file_systemathics_apis_type_shared_v1_filter: GenFile;

/**
 * @generated from message systemathics.apis.type.shared.v1.DateFilter
 */
export declare type DateFilter = Message<"systemathics.apis.type.shared.v1.DateFilter"> & {
  /**
   * @generated from oneof systemathics.apis.type.shared.v1.DateFilter.oneof
   */
  oneof: {
    /**
     * Match exact date
     *
     * Example: Find futures expiring exactly on 2024-12-15
     * Usage: exact { year: 2024, month: 12, day: 15 }
     *
     * @generated from field: google.type.Date exact = 1;
     */
    value: Date;
    case: "exact";
  } | {
    /**
     * Match date range
     *
     * Example: Find all Q1 2024 expirations
     * Usage:
     *   range {
     *     greater_or_equal_than { year: 2024, month: 1, day: 1 },
     *     less_than { year: 2024, month: 4, day: 1 }
     *   }
     *
     * @generated from field: systemathics.apis.type.shared.v1.DateFilterRange range = 2;
     */
    value: DateFilterRange;
    case: "range";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.type.shared.v1.DateFilter.
 * Use `create(DateFilterSchema)` to create a new message.
 */
export declare const DateFilterSchema: GenMessage<DateFilter>;

/**
 * Date range specification for filtering
 *
 * <p>Implements half-open interval: [greater_or_equal_than, less_than)</p>
 * <p>Both bounds are optional; omitting creates open-ended range</p>
 *
 * @generated from message systemathics.apis.type.shared.v1.DateFilterRange
 */
export declare type DateFilterRange = Message<"systemathics.apis.type.shared.v1.DateFilterRange"> & {
  /**
   * Upper bound date (exclusive)
   *
   * Results will have dates strictly before this value.
   * Omit for open-ended upper range (no maximum).
   *
   * @generated from field: google.type.Date less_than = 1;
   */
  lessThan?: Date;

  /**
   * Lower bound date (inclusive)
   *
   * Results will have dates on or after this value.
   * Omit for open-ended lower range (no minimum).
   *
   * @generated from field: google.type.Date greater_or_equal_than = 2;
   */
  greaterOrEqualThan?: Date;
};

/**
 * Describes the message systemathics.apis.type.shared.v1.DateFilterRange.
 * Use `create(DateFilterRangeSchema)` to create a new message.
 */
export declare const DateFilterRangeSchema: GenMessage<DateFilterRange>;

/**
 * Double/decimal filter for numeric values
 *
 * <p>Supports exact matching or range-based filtering.</p>
 * <p>Used for prices, volumes, market caps, and other continuous numeric attributes.</p>
 *
 * @generated from message systemathics.apis.type.shared.v1.DoubleFilter
 */
export declare type DoubleFilter = Message<"systemathics.apis.type.shared.v1.DoubleFilter"> & {
  /**
   * @generated from oneof systemathics.apis.type.shared.v1.DoubleFilter.oneof
   */
  oneof: {
    /**
     * Match exact value
     *
     * Example: Find instruments with price exactly $100.00
     *
     * @generated from field: double exact = 1;
     */
    value: number;
    case: "exact";
  } | {
    /**
     * Match numeric range
     *
     * Example: Find instruments with prices between $50-$200
     * Usage: range { greater_or_equal_than: 50.0, less_than: 200.0 }
     *
     * @generated from field: systemathics.apis.type.shared.v1.DoubleFilterRange range = 2;
     */
    value: DoubleFilterRange;
    case: "range";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.type.shared.v1.DoubleFilter.
 * Use `create(DoubleFilterSchema)` to create a new message.
 */
export declare const DoubleFilterSchema: GenMessage<DoubleFilter>;

/**
 * Double range specification for filtering
 *
 * <p>Half-open interval: [greater_or_equal_than, less_than)</p>
 * <p>Both bounds are optional for open-ended ranges</p>
 *
 * @generated from message systemathics.apis.type.shared.v1.DoubleFilterRange
 */
export declare type DoubleFilterRange = Message<"systemathics.apis.type.shared.v1.DoubleFilterRange"> & {
  /**
   * Upper bound value (exclusive)
   *
   * Results will have values strictly less than this.
   * Omit for no upper limit.
   *
   * @generated from field: google.protobuf.DoubleValue less_than = 1;
   */
  lessThan?: number;

  /**
   * Lower bound value (inclusive)
   *
   * Results will have values greater than or equal to this.
   * Omit for no lower limit.
   *
   * @generated from field: google.protobuf.DoubleValue greater_or_equal_than = 2;
   */
  greaterOrEqualThan?: number;
};

/**
 * Describes the message systemathics.apis.type.shared.v1.DoubleFilterRange.
 * Use `create(DoubleFilterRangeSchema)` to create a new message.
 */
export declare const DoubleFilterRangeSchema: GenMessage<DoubleFilterRange>;

/**
 * Integer filter for whole number values
 *
 * <p>Supports exact matching or range-based filtering.</p>
 * <p>Used for counts, quantities, capitalization, and other integer-valued attributes.</p>
 *
 * @generated from message systemathics.apis.type.shared.v1.IntFilter
 */
export declare type IntFilter = Message<"systemathics.apis.type.shared.v1.IntFilter"> & {
  /**
   * @generated from oneof systemathics.apis.type.shared.v1.IntFilter.oneof
   */
  oneof: {
    /**
     * Match exact integer value
     *
     * Example: Find instruments with market cap exactly 1 billion
     * Usage: exact = 1000000000
     *
     * @generated from field: int64 exact = 1;
     */
    value: bigint;
    case: "exact";
  } | {
    /**
     * Match integer range
     *
     * Example: Find large-cap stocks (market cap $10B-$200B)
     * Usage:
     *   range { 
     *     greater_or_equal_than: 10000000000, 
     *     less_than: 200000000000 
     *   }
     *
     * @generated from field: systemathics.apis.type.shared.v1.IntFilterRange range = 2;
     */
    value: IntFilterRange;
    case: "range";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message systemathics.apis.type.shared.v1.IntFilter.
 * Use `create(IntFilterSchema)` to create a new message.
 */
export declare const IntFilterSchema: GenMessage<IntFilter>;

/**
 * Integer range specification for filtering
 *
 * <p>Half-open interval: [greater_or_equal_than, less_than)</p>
 * <p>Both bounds are optional for open-ended ranges</p>
 *
 * @generated from message systemathics.apis.type.shared.v1.IntFilterRange
 */
export declare type IntFilterRange = Message<"systemathics.apis.type.shared.v1.IntFilterRange"> & {
  /**
   * Upper bound value (exclusive)
   *
   * Results will have values strictly less than this.
   * Omit for no upper limit.
   * Example: less_than = 10000000000 means "values up to but not including 10 billion"
   *
   * @generated from field: google.protobuf.Int64Value less_than = 1;
   */
  lessThan?: bigint;

  /**
   * Lower bound value (inclusive)
   *
   * Results will have values greater than or equal to this.
   * Omit for no lower limit.
   * Example: greater_or_equal_than = 1000000000 means "values 1 billion and above"
   *
   * @generated from field: google.protobuf.Int64Value greater_or_equal_than = 2;
   */
  greaterOrEqualThan?: bigint;
};

/**
 * Describes the message systemathics.apis.type.shared.v1.IntFilterRange.
 * Use `create(IntFilterRangeSchema)` to create a new message.
 */
export declare const IntFilterRangeSchema: GenMessage<IntFilterRange>;

