// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Instrument identifier is built from:
// <br>- An exchange code: MIC
// <br>- A ticker: instrument name given by the exchange
// <br>- An optional provider name if several tick data providers are used

// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file systemathics/apis/type/shared/v1/identifier.proto (package systemathics.apis.type.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { AssetType } from "./asset_pb";
import { file_systemathics_apis_type_shared_v1_asset } from "./asset_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file systemathics/apis/type/shared/v1/identifier.proto.
 */
export const file_systemathics_apis_type_shared_v1_identifier: GenFile = /*@__PURE__*/
  fileDesc("CjFzeXN0ZW1hdGhpY3MvYXBpcy90eXBlL3NoYXJlZC92MS9pZGVudGlmaWVyLnByb3RvEiBzeXN0ZW1hdGhpY3MuYXBpcy50eXBlLnNoYXJlZC52MSK9AQoKSWRlbnRpZmllchI/Cgphc3NldF90eXBlGAEgASgOMisuc3lzdGVtYXRoaWNzLmFwaXMudHlwZS5zaGFyZWQudjEuQXNzZXRUeXBlEg4KBnRpY2tlchgCIAEoCRIuCghleGNoYW5nZRgDIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIuCghwcm92aWRlchgEIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZWIGcHJvdG8z", [file_google_protobuf_wrappers, file_systemathics_apis_type_shared_v1_asset]);

/**
 * Contains the instrument identifier.
 *
 * @generated from message systemathics.apis.type.shared.v1.Identifier
 */
export type Identifier = Message<"systemathics.apis.type.shared.v1.Identifier"> & {
  /**
   * Asset of the identifier
   *
   * @generated from field: systemathics.apis.type.shared.v1.AssetType asset_type = 1;
   */
  assetType: AssetType;

  /**
   * Ticker name, associated with market idenfier code defines a unique asset
   *
   * @generated from field: string ticker = 2;
   */
  ticker: string;

  /**
   * Market idenfier code (MIC), associated with ticker defines a unique asset
   *
   * @generated from field: google.protobuf.StringValue exchange = 3;
   */
  exchange?: string;

  /**
   * Optional provider tick data name if several tick data providers are used
   *
   * @generated from field: google.protobuf.StringValue provider = 4;
   */
  provider?: string;
};

/**
 * Describes the message systemathics.apis.type.shared.v1.Identifier.
 * Use `create(IdentifierSchema)` to create a new message.
 */
export const IdentifierSchema: GenMessage<Identifier> = /*@__PURE__*/
  messageDesc(file_systemathics_apis_type_shared_v1_identifier, 0);

