// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// The asset type

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/type/shared/v1/option_type.proto (package systemathics.apis.type.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file systemathics/apis/type/shared/v1/option_type.proto.
 */
export declare const file_systemathics_apis_type_shared_v1_option_type: GenFile;

/**
 * Contains the option types : call or put.
 *
 * @generated from enum systemathics.apis.type.shared.v1.OptionType
 */
export enum OptionType {
  /**
   * Not specified ?
   *
   * @generated from enum value: OPTION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Call
   *
   * @generated from enum value: OPTION_TYPE_CALL = 1;
   */
  CALL = 1,

  /**
   * Put
   *
   * @generated from enum value: OPTION_TYPE_PUT = 2;
   */
  PUT = 2,
}

/**
 * Describes the enum systemathics.apis.type.shared.v1.OptionType.
 */
export declare const OptionTypeSchema: GenEnum<OptionType>;

