// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Represents a time interval used to delimit historical data requests in time. Time is Universal Time Coordinated (UTC).

// @generated by protoc-gen-es v2.7.0
// @generated from file systemathics/apis/type/shared/v1/time_interval.proto (package systemathics.apis.type.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { TimeOfDay } from "../../../../../google/type/timeofday_pb";

/**
 * Describes the file systemathics/apis/type/shared/v1/time_interval.proto.
 */
export declare const file_systemathics_apis_type_shared_v1_time_interval: GenFile;

/**
 * Contains time interval with start_time (included) and end_time (excluded)
 *
 * @generated from message systemathics.apis.type.shared.v1.TimeInterval
 */
export declare type TimeInterval = Message<"systemathics.apis.type.shared.v1.TimeInterval"> & {
  /**
   * Start time of the time interval. It must always be smaller than end time
   *
   * @generated from field: google.type.TimeOfDay start_time = 1;
   */
  startTime?: TimeOfDay;

  /**
   * End time of the time interval. It must always be greater than start time
   *
   * @generated from field: google.type.TimeOfDay end_time = 2;
   */
  endTime?: TimeOfDay;
};

/**
 * Describes the message systemathics.apis.type.shared.v1.TimeInterval.
 * Use `create(TimeIntervalSchema)` to create a new message.
 */
export declare const TimeIntervalSchema: GenMessage<TimeInterval>;

