name: Publish Package

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.2.3, v2.0.0, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update package.json version
        run: npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version

      - name: Publish to npm
        run: npm publish --tag dev # this is hardcoded. I did not find an easy way to get the branch
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}